### ISSUE TITLE
Memoria RAM - Ubuntu (Virtual Box)

### ISSUE THREAD

**Issue by NicolasCastillo24** [IIC2133-PUC/2020-1#1]
Hola! Estoy creando la maquina virtual de Ubuntu en Virtual Box y me preguntaba cuando seria la "cantidad razonable de RAM y disco duro a la máquina virtual para poder trabajar cómodamente durante todo el semestre"? 

Perdón por crear un issue tan pronto :(

**Comment by vichoeq** [comment]
Ay. El primer issue. Que honor.

Depende totalmente de cuanto tenga tu computador. La memoria RAM va a ser necesaria tanto para correr tu programa como para correr el sistema operativo en sí (y el editor de texto y ese tipo de cosas)

Asique yo recomiendo ponerle lo más que puedas sin que tu computador principal muera. Prueba con el 80% de la memoria y me avisas que tal.

**Comment by NicolasCastillo24** [comment]
Un 80% me dejaría en la zona amarilla de la barrita (esa que ilustra la memoria del computador). Se pone roja en un 90%. Pruebo con 80% igual?

**Comment by vichoeq** [comment]
Hmmmm yo creo que si. Por ultimo si anda muy lento la creas denuevo y le bajas la memoria.

Cuanta memoria tiene tu computador?

**Comment by NicolasCastillo24** [comment]
Mi computador tiene 8G pero dale! me la juego nomas entoncess

**Comment by vichoeq** [comment]
Si, es poquito. Te iba a decir que con que le dejaras 8 deberia andar bien pero no es opción.

Avisame como te va. Si no anda bien y usas Windows trata de configurar el subsystem, y si es Mac puedes usar Parallels en vez de VM que anda harto mejor.

**Comment by vichoeq** [comment]
Hola, al final como anduvo esto? Podríamos coordinar un hangouts con uno de los ayudantes para ayudarte a resolverlo si aun no lo logras.

**Comment by NicolasCastillo24** [comment]
Tuve un problema en la instalación que no he vuelto a revisar. Tenia la duda de que tan recomendable era realizar una partición en lugar de usar una Maquina Virutal? (No es que sepa como hacerle una particion a un mac pero puedo averiguar)

**Comment by arbiocanpion** [comment]
Hola! 
Depende cuanta sea la capacidad de disco de tu computador. Idealmente si es de mas de 128gb no creo que haya problemas en tener una partición de Ubuntu, ademas si planeas tomar mas ramos del DCC es de utilidad que tengas un partición de Ubuntu.
