### ISSUE TITLE
malloc para estructura variable

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#10]
Hola!
¿Como se podría pedir espacio con malloc para una cantidad de N elementos variables que se va actualizando cada cierto tiempo? 
¿Tendría que redefinir el arreglo cada vez que quiera agregar un nuevo elemento? Onda, cada vez que se necesite pedir un malloc más grande para un mismo arreglo ¿debo ir liberando lo que antes tenía después de crear el nuevo y rellenarlo con lo que tenía?

No sé si logro explicarme

**Comment by B-Dominguez** [comment]
Holaa, efectivamente si quieres cambiar el tamaño del malloc debes realizar uno nuevo. Esto tiene sentido si piensas que primero pides un bloque de memoria de tamaño definido, y luego cuando quieras aumentarle el tamaño no es seguro que los espacios de memoria junto a éste sigan disponibles.
Ahora, estar realizando un malloc cada vez que aumentas el tamaño en la unidad puede llegar a ser muy ineficiente en términos de tiempo de ejecución. Al mismo tiempo, asignar una cantidad de memoria totalmente desproporcionada es ineficiente en espacio.
Entonces, puedes pensar en un punto medio. Hint: Que se actualice pero no en cada unidad.

**Comment by Arcoirisky** [comment]
Gracias!

**Comment by santilaguna** [comment]
Sumando a la respuesta, si bien no es recomendable para este caso, existe el método realloc (que para algunos casos si es muy útil). Aún así, debes tener cuidado de que exista el espacio que estas pidiendo. Pueden encontrar un poco más de información sobre este método en la documentación: https://es.cppreference.com/w/c/memory/realloc

**Comment by Arcoirisky** [comment]
Yo lo que hice al final fue una limpieza de estructura con largo N para luego pedir otra de tamaño N + K y liberar la N. Entonces tengo un colchón nuevo con el cual trabajar

**Comment by santilaguna** [comment]
Bien eso debería funcionar!, aunque te recomiendo para un futuro buscar otra alternativa con uso de punteros. Así minimizas el tiempo que tardas en el peor de los casos :)

**Comment by Arcoirisky** [comment]
Oh claro pero es q es un arreglo de punteros, no me es necesario mover los datos ni nada, solo voy moviendo a donde apuntar O: onda, mi nueva “”lista”” apunta a los punteros a los cuales antes apuntaba la “”lista”” anterior. O eso es lo que se supone que hice skndms 

Así solo me meto en el lío de limpiar la memoria y redireccionar en vez de mover todo

**Comment by santilaguna** [comment]
Claro, de todas re-direccionar todos los punteros podría llegar a ser muy costoso

**Comment by Arcoirisky** [comment]
Hmmm siempre pensé q sería a lo más O(n)... aunque ahora que lo pienso, sí, podría llegar a O(n^2) aaaahhh me interesa saber cómo hacerlo mejor pero supongo que tendré que esperar a cuando termine el periodo de la tarea xD

**Comment by B-Dominguez** [comment]
@Arcoirisky con lo que implementaste, puede ser O(n). En general, la eficiencia dependerá de tu N inicial y, a gran escala, de K. 
[HINT: Piensa en cómo afecta un K constante o un K(N).]

Después de eso, te recomendaría no preocuparte más de la eficiencia de esa operación, al menos hasta que tengas todo lo demás listo y quieras seguir experimentando con estructuras más complejas. 

PD: lo que hiciste es el equivalente a realloc, que como bien agrega santilaguna a veces puede ser útil; es un método que intenta (con éxito cuando hay espacio) hacer el equivalente a malloc, memcpy y free, pero se le asocian algunos problemas (como los descritos en  https://www.quora.com/What-are-the-disadvantages-of-using-realloc-function-in-C), por lo que debe usarse con discreción.

Saludos!
