### ISSUE TITLE
Falta de memoria para struct

### ISSUE THREAD

**Issue by Meaylwin** [IIC2133-PUC/2020-1#100]
Buenas tardes:
Estoy teniendo problemas en los test grandes con la **memoria que cada fila de pasajeros** en una puerta tiene asignada. Esto debido a que en estas filas voy guardando los punteros de los pasajeros y cuando es un numero muy grande de pasajeros en una puerta el programa se queda sin memoria y se cae.
Inicialmente, cada vez que instancio una puerta le doy este espacio:
`Gate* gate = malloc(sizeof(Gate) + sizeof(Passenger)*50);`
La solución que encontré fue usar realloc  para una puerta cada 50 pasajeros que entran a la fila:
`int length = spaceTitanic-> terminal[terminal_id]-> gate[gate_id]->length;`
 ` if(length % 50 == 0){ `
   `     spaceTitanic-> terminal[terminal_id]-> gate[gate_id] = realloc(spaceTitanic-> terminal[terminal_id]-> gate[gate_id] ,sizeof(Gate) + sizeof(Passenger)*length);`
 ` }`

Antes se me caía el programa en la linea 800 de test, con este cambio, se cae en la linea 4000, si bien fue una mejora, fue insuficiente.
Agradecería mucho si alguien podría indicarme en que falla mi razonamiento al darle mas memoria a esta estructura.
Muchas gracias!!

**Comment by vichoeq** [comment]
Hola, en primer lugar la memoria que estás asignando para la puerta inicialmente,

```c
Gate* gate = malloc(sizeof(Gate) + sizeof(Passenger)*50);
```

es peligrosa. 

¿Pretendes guardar una puerta en ese puntero? Entonces lo de los pasajeros está demás. 
¿Pretendes usarlo como un arreglo de pasajeros? Entonces deberías definir ese arreglo como parte del struct Gate y no incluirlo en este malloc.

Independiente de las limitaciones de memoria que estés teniendo, mezclar cosas de distinto tipo y tamaño en una dirección de memoria es invitar a los bugs, ya que es muy facil interpretar algo como otra cosa. ¿No has tenido problemas con valgrind?

Si vas haciendo crecer la memoria de las puertas por bloques, es fácil también que se te acabe la memoria porque eventualmente pides mas memoria de la que necesitas. ¿Cuál es la necesidad de hacer las filas como arreglos, y no irlas expandiendo persona a persona como una lista ligada?

Saludos

**Comment by Meaylwin** [comment]
No, no he tenido problemas con valgrind, los test pequeños y medianos que he creado yo han funcionado bien.

> ¿Pretendes guardar una puerta en ese puntero? Entonces lo de los pasajeros está demás.
¿Pretendes usarlo como un arreglo de pasajeros? Entonces deberías definir ese arreglo como parte del struct Gate y no incluirlo en este malloc.

Mi idea era usarlo como un arreglo de pasajeros, podrías explicar mejor lo que mencionas? 

>  Entonces deberías definir ese arreglo como parte del struct Gate y no incluirlo en este malloc.

quizás ahi esta mi problema.

Preferí usar Arrays porque investigando lei que tenian una mejor performance, y para eliminar el primer elemento, en vez de correr todos los elementos en una posición (lo que consumiria muchos recursos), lo que hago es aumentar en uno un puntero que indica donde comienza el array. 
Me ha funcionado bien, a excepción de este problema de memoria.

Muchas gracias Vicho de antemano

**Comment by caespinoza5** [comment]
Ojo que para eliminar el primer o último elemento en una cola, dada una implementación eficiente, tampoco es necesario recorrer todos los elementos. Es más; dada la naturaleza del problema, puede llegar a ser conveniente utilizar colas. Te recomiendo que revises un poco tu modelación del problema, y además, revises el taller 0 de introducción a C (en particular la parte 7_structs).

Lo que mencionaba Vicho se refería a que es conveniente sólo hacer malloc de un objeto cuando lo necesitas. En particular, si por ejemplo tu `gate` no llega a tener más de 50 pasajeros, estarás solicitando memoria extra que no necesitas. Por otro lado, dada la modelación que tienes, es bastante complejo acceder a cada uno de los pasajeros para los que solicitaste memoria en esa línea.

Te dejo un ejemplo de cómo sería tener un arreglo de punteros a objetos, con flores y ramos de flores. En particular, puedes notar que solo hago malloc cuando necesito utilizar dicho espacio en memoria. Quizá pueda serte de utilidad. Puedes probarlo en la página de [onlineGDB](https://www.onlinegdb.com/online_c_compiler).
```c
#include <stdio.h>
#include <stdlib.h>

typedef struct flor Flor;
struct flor{
    int diametro;
};

typedef struct ramo Ramo;
struct ramo{
    Flor* flores[5];
};

Flor* flor_init(int diametro)
{
    Flor* f = malloc(sizeof(Flor));
    f->diametro = diametro;
}

Ramo* ramo_init()
{
    Ramo* r = malloc(sizeof(Ramo));
    for (int i = 0; i < 5; i++)
    {
        r->flores[i] = NULL;
    }
}

void agregar_flor(Ramo* r, int diametro)
{
   for (int i = 0; i < 5; i++)
    {
        if (r->flores[i] == NULL)
        {
            r->flores[i] = flor_init(diametro);
            break;
        }
    } 
}

void imprimir_ramo(Ramo* r)
{
    printf("Imprimiré el ramo de flores\n");
    for (int i = 0; i < 5; i++)
    {
        if (r->flores[i] != NULL)
        {
            printf("Mi diametro es %d\n", r->flores[i]->diametro);
        }
    } 
}

void ramo_destroy(Ramo* r)
{
    for(int i = 0; i < 5; i++)
    {
        if (r->flores[i] != NULL)
        {
            free(r->flores[i]);
        }
    }
    free(r);
}
int main()
{
    Ramo* ramo = ramo_init();
    agregar_flor(ramo, 3);
    agregar_flor(ramo, 4);
    imprimir_ramo(ramo);
    agregar_flor(ramo, 2);
    agregar_flor(ramo, 5);
    imprimir_ramo(ramo);
    ramo_destroy(ramo);
    return 0;
}
```

**Comment by Meaylwin** [comment]
Muchas gracias! Mi modelación de los structs fue basada en el taller 0, pero al darle el espacio de memoria a Gate 
```
Gate* gate_init(int gate_id)
{
  Gate* gate = malloc(sizeof(Gate));
  gate-> id = gate_id;
.
.
 return gate
}
```
Me daba error de memoria (el mismo que estoy teniendo ahora). Esto me ocurría cuando creaba a Gate, incluso antes de agregarle cualquier pasajero, por eso le otorgue mas espacio. Claramente hay algún concepto de malloc que no tengo claro, agradezco a todo aquel que desee iluminarme jajaja

**Comment by santilaguna** [comment]
@Meaylwin te recomiendo modelar tu solucion de manera tal, que ocurra lo siguiente:

Si haces un struct AlgunaCosa y luego haces un a funcion init para este struct de la forma AlgunaCosa* init_alguna_cosa(){...}

Entonces el init es el que se encarga de pedir la memoria (y pide solo un malloc para el tamaño de AlgunaCosa) si necesitas más memoria para otro atributo, entonces crea otra función de init que se encargue de pedir la memoria de ese atributo (que podrías llamar en el primer init si fuera necesario). Esto tal vez te ayudará a tener un mayor orden y evitar problemas por leaks de memoria :)
