### ISSUE TITLE
Duda Informe

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2020-1#102]
Hola!
Tengo una duda con el Informe. Debo calcular el orden de complejidad del número de operaciones de mis funciones de acuerdo a mi implementación? Por ejemplo, para saber la cantidad de niños en una fila alguien podría recorrer la lista u otra persona podría usar memoria adicional para guardar la cantidad de niños como un atributo del struct. 

En mi caso tengo guardados esos datos como atributo y además punteros al inicio y al termino de cada tipo de pasajero.

Muchas Gracias! Saludos.

**Comment by caespinoza5** [comment]
¡Hola!

Efectivamente el cálculo es en función de tu implementación. Si quieres, para ello puedes adjuntar imágenes de tu código (o escribir en pseudocódigo) lo que hace tu función.

¡Saludos!
