### ISSUE TITLE
Problema segmentation fault MAC

### ISSUE THREAD

**Issue by camaruri** [IIC2133-PUC/2020-1#103]
Tengo un problema muy raro, que si corro mi programa en mi terminal de mac se cae con segmentation fault, pero si después lo corro en virtualBox de linux no me tira ningún error.
Nose porque sera este problema

**Comment by yerkko** [comment]
En tu mac intenta hacer `make clean` antes de compilar. Si esto no funciona, puedes mandar qué te dice valgrind?

**Comment by camaruri** [comment]
sisi le hago make clean, pero igual no me funciona.
Los errores son:
- Conditional Jumps or move depends on unitialiazed value
- Use of unitiliiazed value of size 8

**Comment by Arcoirisky** [comment]
@camaruri ¿intentas correrlo con o sin valgrind? 

A un compañero nuestro le pasaba lo mismo al correrlo con valgrind pero era porque tenía funciones sin usar que le estaban causando problemas Bc valgrind revisaba todo.

Quizas, si no estás usando valgrind te pasa algo similar pero para compilar.

**Comment by camaruri** [comment]
en virtual box me funciona con valgrind y sin valgrind de la misma manera.
Hay algun problema en tener funciones sin usar?
