### ISSUE TITLE
Clase 8

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#104]
Hola, podrían subir la Clase 8 del miércoles 15/04. Gracias de antemano

**Comment by rodobkn** [comment]
me gustaría que la subieran también!

**Comment by yerkko** [comment]
Se subirá lo antes posible :)

**Comment by caespinoza5** [comment]
¡Hola!

Acaba de ser subida la clase. La puedes encontrar en el README de la carpeta clases del repositorio, o bien, [aquí](https://youtu.be/qhcdU9GghMM).

¡Saludos!

**Comment by BlancaMunizaga** [comment]
Pero falta subir las lides de rojo o negro. Las van a subir?
