### ISSUE TITLE
Acceder a arreglos de punteros

### ISSUE THREAD

**Issue by camaruri** [IIC2133-PUC/2020-1#105]
Mi duda es mas que nada como acceder en el main a los elementos de un arreglo de punteros.

Para hacer el crucero y el terminal como tenemos el numero de terminales y puertas respectivamente, hize arreglos que contenian **punteros.
De esta forma

```C
Terminal* terminal_init(num_puertas){
	Terminal* terminal = (Terminal*)calloc(1, sizeof(Terminal));
	terminal->num_puertas = num_puertas;
	Puerta** puertas = malloc(num_puertas* sizeof(Puerta));

Crucero* crucero_init(num_terminales){
	Crucero* crucero = (Crucero*)malloc (sizeof(Crucero));
	crucero-> num_terminales = num_terminales;
	Terminal** terminales = malloc(num_terminales* sizeof(Terminal));

```

Que me funciona y no me tira error, pero ahora para acceder a estas listas en el main no he logrado hacerlo, porque me tira segmentation fault. por ejemplo para agregar un nuevo terminal:
con crucero->terminales[term] = &terminal_caso;

Ademas lo otro que me pasa es que si quiero acceder por ejemplo al numero de terminales del crucero, me salen numeros que no son correctos:
printf("%i\n", &crucero->num_terminales); que deberia salir 1 y sale resultado 0.

Gracias

**Comment by santilaguna** [comment]
No entendí muy bien donde terminan los init porque nunca se cierran con {}, de todas formas, al hacer malloc(num_puertas* sizeof(Puerta)); estas pidiendo memoria para num_puertas Puertas y no num_puertas Puertas*. Tal vez, pediste memoria para los structs directamente, siendo que en verdad querías hacer un arreglo de punteros.
