### ISSUE TITLE
output

### ISSUE THREAD

**Issue by dacampos1** [IIC2133-PUC/2020-1#107]
Hola me podrían dar el ouput correcto para este input

6
6
6
3
7
4
6
INGRESO 2 66024706 2
INGRESO 0 37337915 2
INGRESO 1 82138605 2
INGRESO 4 87723078 1
INGRESO 0 13654434 1
INGRESO 4 63731289 1
INGRESO 2 98831381 0
INGRESO 5 199881 1
INGRESO 4 15843361 1
INGRESO 4 15019435 1
INGRESO 0 45869793 2
INGRESO 1 98993234 0
INGRESO 2 26717262 1
INGRESO 0 28622443 1
INGRESO 0 82258317 0
INGRESO 5 98787979 1
INGRESO 0 63457847 2
INGRESO 4 43364541 1
INGRESO 1 59443195 0
INGRESO 1 92432811 2
INGRESO 5 27470607 0
INGRESO 0 45620580 1
INGRESO 3 15791072 1
INGRESO 0 85078335 2
INGRESO 2 31433762 2
INGRESO 1 19630791 2
INGRESO 5 3863521 2
INGRESO 0 950593 2
INGRESO 1 81369105 2
INGRESO 3 28073857 0
INGRESO 4 70133170 0
INGRESO 5 82745457 0
INGRESO 4 54103170 0
INGRESO 1 36080309 0
INGRESO 2 80293327 1
INGRESO 2 90749135 1
INGRESO 3 33569234 0
INGRESO 2 24894232 1
INGRESO 4 30041739 0
INGRESO 0 94015026 2
INGRESO 5 23764690 1
INGRESO 4 98274543 1
INGRESO 4 39231471 1
INGRESO 1 61326581 0
INGRESO 3 97933462 2
INGRESO 3 15033275 2
INGRESO 3 47283812 2
INGRESO 1 40131758 0
LASER 2 2 1
INGRESO 4 40791935 2
INGRESO 1 38960498 1
INGRESO 3 55886649 2
INGRESO 2 51744167 0
INGRESO 4 65008306 1
INGRESO 4 11847241 2
INGRESO 2 1549927 2
INGRESO 4 40657711 1
INGRESO 0 93316400 2
INGRESO 1 17899929 0
INGRESO 0 62213805 0
INGRESO 1 980212 1
INGRESO 4 62507680 1
INGRESO 1 12959002 0
INGRESO 1 28345211 2
INGRESO 5 8396192 0
INGRESO 3 22702861 0
INGRESO 1 40996048 0
INGRESO 1 41886517 0
INGRESO 3 49271468 2
INGRESO 3 12282200 0
INGRESO 5 8026545 0
INGRESO 4 46574356 2
END

**Comment by caespinoza5** [comment]
El output es:
```
TITANIC LOG
TERMINAL 0
GATE 0: 3
82258317
13654434
37337915
GATE 1: 3
62213805
28622443
45869793
GATE 2: 2
45620580
63457847
GATE 3: 2
85078335
93316400
GATE 4: 1
950593
GATE 5: 1
94015026
TERMINAL 1
GATE 0: 4
98993234
12959002
980212
82138605
GATE 1: 3
59443195
40996048
28345211
GATE 2: 3
36080309
41886517
92432811
GATE 3: 2
61326581
19630791
GATE 4: 2
40131758
81369105
GATE 5: 2
17899929
38960498
TERMINAL 2
GATE 0: 3
98831381
90749135
66024706
GATE 1: 3
51744167
26717262
24894232
GATE 2: 2
80293327
1549927
TERMINAL 3
GATE 0: 2
28073857
15791072
GATE 1: 1
33569234
GATE 2: 2
22702861
97933462
GATE 3: 2
12282200
15033275
GATE 4: 1
47283812
GATE 5: 1
55886649
GATE 6: 1
49271468
TERMINAL 4
GATE 0: 4
70133170
87723078
43364541
62507680
GATE 1: 4
54103170
63731289
39231471
46574356
GATE 2: 4
30041739
15843361
65008306
40791935
GATE 3: 4
15019435
98274543
40657711
11847241
TERMINAL 5
GATE 0: 2
27470607
199881
GATE 1: 2
82745457
98787979
GATE 2: 3
8396192
23764690
3863521
GATE 3: 1
8026545
GATE 4: 0
GATE 5: 0
END LOG
```

Recomiendo dejar las issues abiertas ya que pueden ser de ayuda al resto de tus compañeros 😄
