### ISSUE TITLE
liberar memoria

### ISSUE THREAD

**Issue by camaruri** [IIC2133-PUC/2020-1#108]
Si yo libero un arreglo, quedan liberados todas las memorias de sus elementos?
por ejemplo:
num1 = 5
num2 = 7
a[2] = [num1, num2]
free(a)
Se libera el arreglo y las variables num1 y num2?

**Comment by Arcoirisky** [comment]
Si pediste malloc para ellos elementos de a, nope

**Comment by caespinoza5** [comment]
Tal como dice Arcoirisky, necesitas liberar uno a uno todos los bloques de memoria que solicitaste.

Puedes revisar [esta issue](https://github.com/IIC2133-PUC/2020-1/issues/100); en particular, en la discusión se mencionó un ejemplo que ocupa algo similar a lo que planteas: una estructura que ocupa sub-estructuras, y cómo se liberan. Además, te recomiendo que revises en detalle el taller 0 de C.

¡Saludos!
