### ISSUE TITLE
Error output a medio imprimir

### ISSUE THREAD

**Issue by pbyoma** [IIC2133-PUC/2020-1#109]
Cuando corro los test largos, se me quedan pegados antes de terminar (se quedan pegados en la mitad del print de un pod en la mitad de un id de algún pasajero):
POD 3 1 407 LOG
18940487
37715766
442
Lo he dejado corriendo minutos y no sigue.
Cuando lo corro con valgrind y lo cancelo, al cancelarlo aparecen como 100 lineas más.
Hasta lo que me imprime está igual que el output que debería y valgrind no me tira ningún error.
Me imprime entre 3000 y 34000 lineas, dependiendo del test
A que se puede deber esto?

**Comment by cacosandon** [comment]
Hola!

Con qué consola lo estás corriendo? Lo intentaste más de una vez?

**Comment by pbyoma** [comment]
Hola, 
Estoy usando una partición de ubuntu. Lo he intentado muchas veces, he estado hace una semana con el mismo error y pensé que era un problema de optimización de mi programa. Sin embargo, lo hice lo más óptimo posible y sigue igual. 
El test01 si se termina y tiene el output correcto

**Comment by mimunoz11** [comment]
Me pasó algo parecido a lo que describes. Si te funciona solo el test 01 tu problema debe ser que no estas considerando un caso borde de descontar las puertas ya cerradas en el ciclo para mover los niños adultos robots a la puerta auxiliar en la función clausura. A mi sin descontar las puertas cerradas me quedaba en un ciclo infinito y por eso no terminaba el programa. Ojala sea eso, saludos.

**Comment by pbyoma** [comment]
No era precisamente eso, pero me ayudo bastante para solucionarlo, muuuuuchas gracias!!!
