### ISSUE TITLE
Archivos .c y .h en mi main

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#11]
Hola!
si quiero modularizar mejor mi programa creando funciones fuera del main principal es ¡necesario incluir un .h junto a un .c con el mismo nombre o solo el .c basta?

Sobre lo mismo ¿que diferencia hay entre un .h y un .c? a parte de que en el .h declaro todo lo que defino en el .c, en el caso de las funciones. 

Hasta donde sé puedo escribir mis estructuras en el .h y declarar funciones asociadas a estas pero ¿si quiero agregar más sin que se sature el archivo?

**Comment by B-Dominguez** [comment]
Hola! te recomiendo leer esta issue y dime después si todavía te quedan dudas,
#4

**Comment by Arcoirisky** [comment]
aaah entonces si necesito ambos, okay!
