### ISSUE TITLE
problema de memoria

### ISSUE THREAD

**Issue by camaruri** [IIC2133-PUC/2020-1#110]
Hola esta viendo el taller y corriéndolo en valgrind me tira este error para las listas ligadas si las uso en mi programa:
el código es:
List* list_init()
{
  List* list = malloc(sizeof(List));
  list -> head = NULL;
  list -> tail = NULL;

  return list;
}

y el error de valgrind es:

<img width="979" alt="Captura de Pantalla 2020-04-18 a la(s) 12 09 33" src="https://user-images.githubusercontent.com/53882047/79642777-7a360380-816d-11ea-9eb0-47a9e34f4725.png">

La otra duda que tengo con Valgrind es que estuve leyendo las issues y el material que mandaron, pero todavia no se como arreglar los problemas que dicen:
Invalid read of size 8:
todos los errores que tengo son por lo mismo.

**Comment by caespinoza5** [comment]
¿Cómo estás creando una lista cuando la creas? ¿Ocupas lo siguiente?
`List* l = list_init();`

Lo otro, el invalid read of size N ocurre cuando intentas acceder parte de la memoria del Heap de Memoria que nunca guardaste espacio.

Por ejemplo, en ese mismo taller, si tienes el siguiente código:

```c
List* l = list_init();
printf("%d\n", l->head->value);
```

Te tirará un error porque head es nulo, luego head->value es una lectura inválida. Lo mismo si es que tienes un puntero a una lista que nunca inicializaste por ejemplo. En el siguiente código:

```c
  List *l = NULL;
  if (l->head != NULL)
  {
    printf("No tengo head\n");
  }
```
También te daría un error ya que l es nulo, luego l->head es una lectura inválida. En general, para evitar este tipo de cosas, puedes hacer lo siguiente:

```c
  List *l = NULL;
  if (l)
  {
    printf("Tengo una lista\n");
    if(l->head != NULL)
    {
        printf("No tengo head\n");
    }
  }
```

**Comment by camaruri** [comment]
Cómo estás creando una lista cuando la creas? ¿Ocupas lo siguiente?
List* l = list_init();

Si las estaba creando justamente asi. 
Por otro lado, tambien encontre dos invalid write, eso seria que trato de escribir una variable que no defini?

Lo que no entiendo es por que mi programa corre sin caerse aunque tenga estos errores.
Gracias

**Comment by caespinoza5** [comment]
Los invalid write son lo siguiente: intentas escribir en un espacio de memoria que no has solicitado acceso. Aquí te doy un ejemplo:
```c
  int *a = malloc(3 * sizeof(int));
  a[0] = 0;
  a[1] = 1;
  a[2] = 2;
  // Aquí tienes un invalid write porque
  // Solo solicitaste espacio para 3 ints,
  // y escribes un cuarto.
  a[3] = 120;

  // Aquí tienes un invalid read porque
  // estás intentando leer una posición
  // que nunca solicitaste espacio.
  printf("%d\n", a[3]);

  // Podemos revisar si se escribió
  // en el a[3].
  for (int i = 0; i < 4; i++)
  {
    // En el i = 3 tendrás un segundo invalid write.
    printf("%d\n", a[i]);
  }
  free(a);
```

Si corres este código en tu computador, puede ser que al imprimir a[3] efectivamente te imprima 120. Sin embargo, nada te asegura que eso se cumpla en cada ejecución, o en cada máquina distinta. Dado que el comportamiento de la escritura y lectura de la variable a[3] es incierto, es mejor asegurarse no tener ese tipo de errores.

Por lo mismo es que tu programa funciona; en particular, cuando escribes o lees datos para los que no solicitaste espacio en el Heap de memoria, estos efectivamente se escribieron, pero en un test perfectamente podría pasar que el bloque de memoria que justo le sigue al bloque que solicitaste con malloc para la variable a, fue ocupado por otro malloc, por lo que al escribir en a[3] estarías sobreescribiendo algún dato que estaba ahí y que era necesario para tu ejecución.

**Comment by camaruri** [comment]
ya algo entendi parece:
lo que no se porque pasa un error de escritura por ejemplo en lo siguiente:
Casa* casa_init(int num_piezas){
	Casa*  casa = malloc(sizeof(Casa*));
	casa->num_piezas = num_piezas;
	casa->piezas = malloc(num_puertas * sizeof(Pieza*));
	int i;
	for (i = 0; i < num_piezas; i++){
		Pieza* nueva_pieza;
		nueva_pieza = pieza_init();
		casa->piezas[i] = nueva_pieza; 
	}
return casa;

en ese caso me tiraba invalid write en la linea:
casa->piezas = malloc(num_puertas * sizeof(Pieza*));       // tambien probe con sizeof(Puerta**)

y ademas invalid read en la linea:
casa->piezas[i] = nueva_pieza;



* Otra de mis dudas es como hago si quiero que una funcion del init por ejemplo use una variable dada por malloc pero quiero liberarla despues una vez que termina el programa.

**Comment by B-Dominguez** [comment]
Hola @camaruri, creo que tienes una confusión al menos con los malloc. Entiendo que queda poco tiempo para la entrega del código y tal vez te falta mucho, pero te recomiendo fuertemente que estudies con tiempo los materiales que les damos para iniciarse en la programación en C independientemente de esta tarea, pues es la base también para las que vienen. En particular, el taller 0 es fundamental para iniciarse y es muy importante leer cada uno de los archivos que tiene, pues necesitas por ejemplo entender muy bien lo que se explica de punteros y memoria para poder entender bien lo de la matriz. Si tienes dudas particulares sobre el material siempre las puedes subir a las issues (y buscar las que ya están publicadas) o contactarnos a los ayudantes.

De todas formas, una observación importante a tu código es que estás haciendo malloc(sizeof(Casa*)). Esto es pedir memoria con el tamaño para guardar en ella un puntero (que apunta a un struct casa) y no para guardar en ella el struct casa mismo. Luego tienes el mismo problema con Pieza.
