### ISSUE TITLE
Duda formato complejidad en informe

### ISSUE THREAD

**Issue by jcechavarri** [IIC2133-PUC/2020-1#111]
Hola!

Tengo una duda con respecto a la parte de 

> Calcula y justifica la complejidad en notación O para cada uno de los eventos en función de la cantidad de personas, la cantidad de puertas y la cantidad de terminales. Debes simplificar la expresión lo más posible.

A esto se refiera a que si, por ejemplo, tengo M puertas y N pasajeros, y mi algoritmo hace 5M + 7N comparaciones dejar la complejidad como O(M+N) ?

Gracias!

**Comment by B-Dominguez** [comment]
Hola, sí eso sería correcto! Correponde con la notación O de complejidad usado en el resto del curso y en matemáticas discretas.
