### ISSUE TITLE
Error al Compliar: Error 127

### ISSUE THREAD

**Issue by vchadwick** [IIC2133-PUC/2020-1#112]
Hola, 
Me acaba de aparecer un error al compilar. Ahora no puedo compilar ni mi programa ni los archivos Talleres que están en el repositorio principal. El error que me sale es el siguiente:

/bin/sh: 1: gcc: not found
Makefile: 111: recipe for target "obj/0_hello_world/main.o" failed
make: *** [obj/0_hello_world/main.o] Error 127

Que podrá ser? Gracias

**Comment by caespinoza5** [comment]
¿Intentaste correr `make clean` y luego `make` nuevamente?

**Comment by vchadwick** [comment]
Hola si! Pero nuevamente el mismo error

**Comment by caespinoza5** [comment]
¿El problema lo estás teniendo al correr `make`? Intenta corriendo el siguiente comando: `sudo apt install gcc` y luego prueba denuevo.

**Comment by vchadwick** [comment]
Ahora funciona perfectamente! Había reinstalado unas cosas del Pc y se debería haber borrado! 
Muchas gracias
