### ISSUE TITLE
Double free or corruption (fastop)

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2133-PUC/2020-1#113]
Hola me aparece ese error cuando intento liberar la memoria de mi Nodo, que lo tengo definido como:

```C
Nodo* nodo = malloc(sizeof(Nodo));
 for(int i = 0; i <= 1; i ++){
      (nodo -> valor)[i] = valor[i];
    }
  nodo -> sgte = NULL;
```

Lo libero en el siguiente código:

```C
Nodo* primero = cola -> primero;
 free(primero);
```

Si me pueden ayudar a encontrar el error o me recomiendan un programa para encontrarlo, lo agradecería mucho, porque me va quedando eliminar los leaks y valgrind explota con este error.
Saludos.

PD: No he usado free antes de esa linea.

**Comment by yerkko** [comment]
No veo el problema en las líneas que comentas (por favor revisa el formato, tuve que arreglarlo porque costaba mucho leer), intenta revisar bien el trace que te da valgrind y en qué línea se produce el error
