### ISSUE TITLE
Informe T0: Cantidad de puertas

### ISSUE THREAD

**Issue by mihenriquez** [IIC2133-PUC/2020-1#114]
Hola! Cuando se pide calcular la complejidad en función de la cantidad de puertas, esa variable (p por ejemplo) será la cantidad de puertas en todo el barco o a la cantidad de puertas en un terminal? O queda a nuestro criterio definirlo como un promedio o algo por el estilo?

Gracias!

**Comment by caespinoza5** [comment]
Te recomiendo calcular con p siendo la cantidad de puertas de un terminal. Si necesitas la cantidad de puertas de todos los N terminales, siempre puedes acotar tu complejidad con p = max(p1, p2, ..., pN), de tal manera que todas tus puertas estarían acotadas por N * p.
