### ISSUE TITLE
valgrind

### ISSUE THREAD

**Issue by JoseAvanzada2019** [IIC2133-PUC/2020-1#116]
hola, mi tarea se cae en los tests grandes, pero desafortunadamente no tengo valgrind.
 Algún ayudante podría correr mi tarea en valgrind.

**Comment by JohnTrombon** [comment]
Te dejaré un issue en tu repo con un output, espero te ayude! Para las siguientes entregas es necesario que tengas por lo menos una maquina virtual exclusivamente para correr los ejecutables con valgrind.

**Comment by JoseAvanzada2019** [comment]
gracias

**Comment by alexaptib** [comment]
@JoseAvanzada2019  podrias pofavor hacer lo mismo con el mio? he estado intentando toda la tarde instalar la maquina virtual para poder hacer valgrind y no puedo :( de ante mano muchisimas gracias!!
