### ISSUE TITLE
Tarea 1: Compresión

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2020-1#118]
Hola!
Tengo dos dudas del enunciado de la Tarea 1.
1) El enunciado dice en la 4ta página que 

> Se espera que **al iniciar tu programa construyas el árbol a partir de la imagen**, y que luego lo utilices mediante consultas para llevar a cabo los distintos pasos del algoritmo.

Por lo que entendí, construir el árbol y aplicar el filtro son lo mismo, es decir, no puedo construir el árbol sin un alfa. Lo que dice el enunciado entonces significa que en caso de usar modo **filtro**, simplemente construyo el árbol, lo transformo a imagen y retorno el output; y en caso de usar modo **compresión**, calculo el alfa (de aquí deriva mi segunda pregunta), construyo el árbol, lo transformo a imagen y retorno el output, correcto?

2) Es claro que hay una relación entre _h_ y _alfa_, me pregunto si debemos ser capaces de encontrar esa relación _matemática_, o debemos aplicar todo el filtro con _alfa = 128/2_, observar el _h_... etc, aplicando _k_ veces el filtro hasta llegar a un _h < input_?

Muchas gracias! Saludos.

**Comment by yerkko** [comment]
Mañana te contestamos la (1), que es relativamente más larga.

Con respecto a la (2), existe una relación, pero no es directa como alpha = k * h, si no que nace de la estructura y debes encontrarlo, como dice el enunciado, usando binary search

**Comment by jeschuwirth** [comment]
Hola @fabarros,

Creo que tus dos preguntas se pueden responder con la siguiente aclaración:

Al ejecutar el código en modo filtro no hay problema con que construyas el árbol, lo transformes a imagen y luego retornes el output.

Al usar el modo compresión, recomiendo fuertemente partir creando el árbol con alpha = 1, esto te dará un árbol muy complejo con muchos nodos hoja que probablemente no cumpla la condición de hojas máximas, luego sobre **ese mismo** árbol puede aplicar alpha = 2 y ver si cumples la condición de hojas máximas y así ir aumentando alpha hasta cumplir la condición.

Si no quedo clara la explicación o quedaron dudas sigue comentando en la issue :)

Éxito!

**Comment by vichoeq** [comment]
@fabarros @jeschuwirth  Hola, una pequeña corrección: 

> recomiendo fuertemente partir creando el árbol con alpha = 1

Juan quiso decir alpha = 0, es decir sin aplicar filtro; alpha = 1 ya causará la fusión de los nodos con gamma entre 0 y 1.

**Comment by vichoeq** [comment]
Luego puedes ir aumentando el alpha de 1 en 1 y ver en que momento se cumple la condición.

Ten en consideración si que va a ser más rapido hacer busqueda binaria para encontrar el menor alpha que cumple la condición.

**Comment by fabarros** [comment]
Perfecto! Entonces efectivamento tengo que aplicar el filtro una cierta cantidad de veces en el modo compresión. Gracias!

**Comment by VicenteMerino** [comment]
> Hola @fabarros,
> 
> Creo que tus dos preguntas se pueden responder con la siguiente aclaración:
> 
> Al ejecutar el código en modo filtro no hay problema con que construyas el árbol, lo transformes a imagen y luego retornes el output.
> 
> Al usar el modo compresión, recomiendo fuertemente partir creando el árbol con ~alpha = 1~ alpha = 0, esto te dará un árbol muy complejo con muchos nodos hoja que probablemente no cumpla la condición de hojas máximas, luego sobre **ese mismo** árbol puede aplicar ~alpha = 2~ alpha = 1 y ver si cumples la condición de hojas máximas y así ir aumentando alpha hasta cumplir la condición.
> 
> Si no quedo clara la explicación o quedaron dudas sigue comentando en la issue :)
> 
> Éxito!
> 
> EDIT: Ver siguiente comentario

@jeschuwirth @vichoeq  No me queda claro entonces donde se está aplicando la búsqueda binaria, ya que el alpha se va simplemente aumentando. Yo la verdad estaba pensando armar un arbol con los posibles valores de alpha y así ir viendo si se cumple la condición o no, pero de esta forma que tu mencionas me suena un poco más facil de implememntar (aunque quizás aumente un poco la complejidad en tiempo). Mi pregunta: ¿es válido entonces ir aumentando alpha de 1 en 1 hasta encontrar el mínimo? Que mi problema es que ahí no se estaŕia aplicando la búsqueda binaria.

**Comment by vichoeq** [comment]
@VicenteMerino 

Lo importante de la tarea es que resuelvas el problema que se pide, las estrategias recomendadas en el enunciado son más eficientes, pero pueden no ser necesarias. Considerando eso, es perfectamente válido ir aumentando el alpha de uno en uno. Juan lo recomendó precisamente porque es más simple de implementar. Además, ir aumentando de uno en uno te permite aplicar el filtro sobre el árbol anterior, lo cual simplifica aún más la implementación. 

La búsqueda binaria es una estrategia más eficiente, pero en este caso hacer búsqueda lineal con un n de 128 no hace mucha diferencia ya que el tiempo que toma revisar con cuantas hojas queda el árbol es poco. Lo correcto habría sido pedirles que buscaran números reales de hasta 6 decimales en vez de enteros pero se nos pasó eso en el diseño de la tarea, así que bien por ustedes :+1:
