### ISSUE TITLE
Tarea 1: missing #include <png.h>

### ISSUE THREAD

**Issue by figarcia3** [IIC2133-PUC/2020-1#119]
Hola, al correr el primer make me indica que no encuentra el archivo o directorio del include <png.h>, como soluciono este problema?

**Comment by figarcia3** [comment]
sudo apt-get install libpng-dev

Ese comando me soluciono el problema!

**Comment by yerkko** [comment]
Gracias por postear la solución, ojalá esta información le sirva al resto de los estudiantes :)

**Comment by chocopiano** [comment]
No entendí que debo hacer para poder probarlo? Al hacer make me aparece el mismo error, pero cuando corro esa línea de comando como solución me dice apt-get not found

**Comment by chocopiano** [comment]
La pifie... ahora si me funciono con brew install libpng

**Comment by yerkko** [comment]
En linux depende de la distro, para ubuntu es apt-get, 
Para mac mac supongo que es brew 🤔

**Comment by alexaptib** [comment]
No pude arreglar esto con los comentarios anteriores. (tengo mac)

Al hacer sudo brew install libpng-dev -->Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

al hacer brew install libpng-dev --> Error: No formulae found in taps.

estoy haciendo algo mal?
