### ISSUE TITLE
Hangouts con ayudante

### ISSUE THREAD

**Issue by aacamhi** [IIC2133-PUC/2020-1#12]
Hola! Me gustaría hacer un hangouts con algún ayudante para resolver dudas, en especial porque no pude ir al último taller de c

**Comment by arbiocanpion** [comment]
Hola!
Me puedes enviar un mail a lbaguilera@uc.cl y coordinamos

**Comment by ljrodriguez1** [comment]
Hola queria saber si en esta reunion solo se pueden hacer preguntas sobre el setup de la tarea o tambien sobre la tarea misma, como que estructura utilizar y como diseñarla. ya que me siento algo perdido en esto.

Saludos

**Comment by arbiocanpion** [comment]
Hola @ljrodriguez1  
Cualquier duda respecto de la tarea hazla por las issues, si es algo muy específico o complicado se hara una sesión de hangouts.
