### ISSUE TITLE
Tarea 1: Dirección Filtro

### ISSUE THREAD

**Issue by atroncoso2** [IIC2133-PUC/2020-1#120]
Hola, tengo una duda de enunciado en la sección de filtro. 
Dice que para cada cuadrante que tenga como desviación estandar menor a alpha, hay que pintar todos esos pixeles del color promedio (de todos los pixeles en el cuadrado). 

Según entiendo, puede ocurrir que la desviación estándar de un cuadrado sea menor a alpha, y al mismo tiempo que un cuadrante de ese cuadrado (un subcuadrado) tenga desviación estándar superior a alpha. En estos casos, ¿cuál es la prioridad? ¿Se pinta igual cuadrado grande a pesar de que un subcuadrado tenga desviación estándar mayor que alpha? ¿O sólo se puede pintar un cuadarado grande si todos los subcuadrados tienen desviación estándar mayor que alpha?

**Comment by vichoeq** [comment]
Hola.

> Puede ocurrir que la desviación estándar de un cuadrado sea menor a alpha, y al mismo tiempo que un cuadrante de ese cuadrado (un subcuadrado) tenga desviación estándar superior a alpha.

Sí, es posible esto. Por ejemplo los cuadrantes de 1x1 tienen un solo elemento, por lo que la desviación estandar es 0. 

> ¿Se pinta igual cuadrado grande a pesar de que un subcuadrado tenga desviación estándar mayor que alpha?

Si. El proceso de filtro se hace desde la raíz hasta las hojas: apenas encuentras un cuadrante que cumple la condicion lo dejas como hoja, sin importar las desviaciones estandar de sus hijos. Eso permite a un cuadrante "redondear" los colores de los hijos en un solo color, aunque ellos por si solos no califiquen.

> ¿O sólo se puede pintar un cuadarado grande si todos los subcuadrados tienen desviación estándar mayor que alpha?

No. Todos los cuadrados de 1x1 tienen desviación estandar 0, por lo que de ser así no se podría pintar niun cuadrado.

Espero que esto responda tu pregunta. 
Saludos!

**Comment by atroncoso2** [comment]
Se entiende perfecto. 
Gracias!

**Comment by miguelramirezv** [comment]
Hola! Los cuadrantes 1x1 te refieres a los pixeles o no?

**Comment by miguelramirezv** [comment]
Hola! Otra pregunta, todas las imágenes son cuadradas? Para poder dividirlas siempre en 4 hasta que se dividen en cuadrados de 1x1?

**Comment by caespinoza5** [comment]
@miguelramirezv Sí; dale una revisada a la sección de input del enunciado.
