### ISSUE TITLE
Similitud

### ISSUE THREAD

**Issue by dacampos1** [IIC2133-PUC/2020-1#121]
Hola, tengo dudas respecto a lo que sale en el enunciado sobre la media y varianza incremental. No entiendo como podría ser implementado ya que al filtrar se recorre desde la raíz hacia las hojas. Por ejemplo si calculara la media de cada uno de los 4 cuadrados morados podría utilizarla para calcular la media del cuadrado rosado 2 sin tener que recorrer todos los datos, pero como se debe recorrer desde la raíz primero calcularía el del cuadrado rosado 2 y no podría usar lo de la media incremental.
![Captura de Pantalla 2020-04-25 a la(s) 13 40 44](https://user-images.githubusercontent.com/42916420/80286601-5db04300-86fa-11ea-9427-1b063e00e58d.png)

**Comment by jeschuwirth** [comment]
Hola @dacampos1,

Lo que dices es cierto, en caso de partir de la raíz no podrías usar la media incremental. 

Lo que se recomienda para esta tarea es armar primero el árbol, mientras se arma puedes ir calculando la varianza y media de cada nodo de manera incremental. 

Luego de tener el árbol puede resolver la consulta de manera muy eficiente :)

Éxito!

**Comment by miguelramirezv** [comment]
Hola! O sea, habría que partir haciendo el árbol de las hojas hacía la raíz? 

Las hojas iniciales siempre parten siendo los pixeles? Y después cuando se filtra van cambiando estas hojas?

**Comment by vichoeq** [comment]
Hola, mi recomendacion es que:

1. Construyas el árbol, calculando la desviación estandar para cada nodo. Esto se hace desde las hojas hasta la raiz, ya sea top down (recursivamente) o bottom up (iterativamente). En el enunciado se menciona que inicialmente cada hoja del árbol corresponde a un pixel de la imagen.
2. Apliques recursivamente el el filtro, desde la raiz hasta las hojas, pintando en la imagen los cuadrados que decretes que son hoja.

Espero que esto responda tu pregunta

Saludos!
