### ISSUE TITLE
Tarea 1: Acceder a L, a y b.

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2020-1#122]
Hola!
En mi código estoy haciendo algo así ```img -> pixels[i][j] -> L``` para acceder al valor de ```L```, pero VSCode me dice que tengo un error y el compilador también. Particularmente el compilador me dice ```error: invalid type argument of ‘->’ (have ‘Color {aka struct color_lab}’)```.
Cuando cambio esa línea por ```img -> pixels[i][j].L``` el error se quita y me deja compilar pero arroja ```core dump invalid read of size 8``` (lo revisé con valgrind). 
Cómo debería entonces ingresar a la variable L?
Gracias! Saludos.

**Comment by VicenteMerino** [comment]
Tengo la misma duda

**Comment by yerkko** [comment]
Hola, esta es una duda que se está repitiendo mucho.
La diferencia en la sintaxis depende si accedes a un puntero de una variable o a una variable.
Fue resuelta acá
#4 
Y también está en el taller de C

**Comment by fabarros** [comment]
Hola @yerkko, gracias por tu respuesta.
Pero entonces, por qué me arroja Core Dump cuando lo cambio por ```img -> pixels[i][j].L```?

**Comment by VicenteMerino** [comment]
A mi me tiró bien los print al menos, tal vez puedan ser tus for porque te estas saliendo de los indices?

**Comment by yerkko** [comment]
Lo más probable es que tu error viene por otra parte del código.

**Comment by fabarros** [comment]
Ya lo solucioné, claramente era un error en los límites del for, Gracias :)
