### ISSUE TITLE
Tarea 1: Método Incremental

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2020-1#123]
Hola!
En la ayudantía 2 nos dijeron que se recomienda usar Métodos Incrementales para calcular promedio y desviación estándar, pero que no es obligación. Mi duda es, el riesgo de no usar métodos incrementales recae en un mayor tiempo de ejecución o en que se me puede generar un overflow de mis variables? Podría generarse un overflow en las imágenes más grandes si calculo la desviación estándar a la mala?
Gracias! Saludos.

**Comment by yerkko** [comment]
La única diferencia que genera es tiempo de ejecución, pero tampoco es mucha
