### ISSUE TITLE
Largo y ancho imágenes

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#124]
Hola, podemos asumir que las imágenes tendrán una largo/ancho múltiplo de 2? Podemos asumir también que serán potencia de 4 (o en su defecto, de 2)?

**Comment by caespinoza5** [comment]
¡Hola!

Sí. En la sección de Input de enunciado aparece eso, para que le des una segunda vuelta.

¡Saludos!
