### ISSUE TITLE
Duda acceso por índice

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#125]
Hola. hay alguna forma de en C de hacer lo siguiente:

Si tengo un arreglo a ={0,1,2,3,4,5,6,7}
Y hago a[:3] me entregue {0,1,2,3}

Se que siempre esta la forma de redifinir una nueva estructura usando un for, pero mi idea es poder hacerlo en O(1) usando acceso por indices.

**Comment by yerkko** [comment]
De poder, se puede... Quizás una struct Slice o usando un #define o función que devuelva eso. Quizás haciendo aritmética de punteros...

Sin embargo, intentaría reconsiderar lo que quieres implementar y ver si de verdad es necesario 🤔

**Comment by yerkko** [comment]
Si te interesa, más por curiosidad por el lenguaje C y sus librerías que por otra cosa, puedes usar `memcpy`, pero te recomiendo **no** hacerlo y reconsiderar tu algoritmo

**Comment by vichoeq** [comment]
C no tiene implementa slices como parte del lenguaje, pero como dijo Yerko puedes obtener una referencia a este sub-arreglo en O(1) usando aritmetica de punteros, aunque no lo recomiendo: probablemente se vuelva imposible de debugear.

Ten en consideración que al ser una referencia se modificaría el original si modificas el slice. Si quieres un arreglo independiente es imposible hacerlo en O(1) (memcpy es increiblemente rápido pero sí depende del tamaño del arreglo a copiar)

¿Por qué necesitas un slice? ¿Cuál es el problema con guardar un par de índices para delimitar el sub-arreglo?

**Comment by VicenteMerino** [comment]
Si, al final me di cuenta que era una pésima idea. Básicamente lo que quería hacer era que cada hijo almacenara cada submatriz, pero me di cuenta que es mejor lo que dice @vichoeq delimitando con índices y de ser necesario operar la submatriz solo utilizo la imagen ya preprocesada y los índices que me interesan.

**Comment by vichoeq** [comment]
Genial. Recuerda que la función pintar imagen recibe como parámetro la esquina superior izquierda (row, col) y el largo del lado del cuadrado (size).

Recomiendo guardar de ese mismo modo los indices de las submatrices para que sea llegar y pintar :+1:
