### ISSUE TITLE
[Tarea 1] Estructura image

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#126]
Hola! Me surgió unas dudas sobre la estructura imagen. 

Primero no entiendo muy bien que pasa en lab_2_rgb ni que es un uint8_t.

Después, entiendo que la función img_png_read_from_file me entrega un objeto Image*, pero lo que no entiendo, es que en su atributo Color** pixels no sé como accedo a cada uno de los pixeles. Leí en unas issues que era simplemente como pixels[i][j], pero no entiendo muy bien porque sería así. No lo entiendo porque si es un **, significa que es un puntero de un puntero o no? O tal vez me estoy enredando un poco con C.

Muchas gracias de antemano!! 😄😄

**Comment by vichoeq** [comment]
Hola, lo que importa que entiendas es `imagelib.h`, que son las estructuras y funciones a su disposición. En `imagelib.c` encontrarán detalles de implementacion y funciones internas que no necesitan usar o entender.

El atributo `Color** pixels` es una matriz de colores (un arreglo de arreglos), por lo que para acceder a un color debes hacer `pixels[fila][columna]`
