### ISSUE TITLE
Cantidad de nodos en cada nivel

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#127]
Hola, dado que las imágenes son cuadradas siempre y el largo y ancho son multiplos de 2, es correcto asumir que la cantidad de nodos en cada nivel será 4^k, con k la altura de la raiz al nivel (con la raiz de altura 0).

**Comment by vichoeq** [comment]
Hola, el largo y el ancho son **potencias** de 2, por lo que sí, es correcto asumir eso.
