### ISSUE TITLE
[Tarea 1] Comprobar Correctitud Subalgoritmos

### ISSUE THREAD

**Issue by cjones27** [IIC2133-PUC/2020-1#128]
Hola!

Quisiera saber como puedo corroborrar la correctitud de mis outputs (más allá de hacer inspección visual), es decir, de las imagenes finales filtradas o comprimidas. Hay algún comando que pueda correr (como el diff de la tarea pasada) con el cual pueda comprobar esto?

Gracias y que tengan buena semana!

**Comment by vichoeq** [comment]
Hola, puedes en tu mismo código leer la imagen de output y comprararla con tu resultado pixel por pixel.

**Comment by cjones27** [comment]
Genial, buena idea, gracias. Cuando subirán los outputs de ejemplo aprox?

**Comment by tpcantergiani** [comment]
Hola!
Puedo comprobar la correctitud con `diff -b out.png <resultado_correcto>`?

**Comment by caespinoza5** [comment]
¡Hola!

@cjones27 Los outputs de ejemplo están ya en Siding. Revisa los anuncios; ahí encontrarás más info.
@tpcantergiani ¡Si! por ejemplo:
`./quadtree imgs/256/emblem.png out.png filter 5.2`
Y luego
`diff -b out.png filtered/256/emblem_alpha=5.2.png`
debiese darte 0 diferencias, lo que indica que el output es correcto.

**Comment by vichoeq** [comment]
Cabe si mencionar que `diff` compara los bytes del binario de la imagen. En este caso debieran darte iguales porque fueron generados usando la misma librería que les entregamos :+1:

**Comment by vichoeq** [comment]
Ojo que `diff` solo indicará si ambas imagenes son distintas, pero no donde. Al comparar pixel a pixel dentro de tu código puedes generar una imagen que te indique exactamente en que lugares tu output es distinto del esperado, lo que te puede ayudar a debugear.

**Comment by mora4** [comment]
Aca estan los comandos que use para revisar filter y compress en las fotos de 2048:
(Para compressed le cambie los nombres a las fotos porque los "(" ")" me daban un error).

-- Filter 2048 -- 
./quadtree imgs/2048/bricks.png out.png filter 5.6
diff -b out.png filtered/2048/bricks_alpha=5.6.png

./quadtree imgs/2048/checkers.png out.png filter 12
diff -b out.png filtered/2048/checkers_alpha=12.png

./quadtree imgs/2048/lava.png out.png filter 5.2
diff -b out.png filtered/2048/lava_alpha=5.2.png

./quadtree imgs/2048/noise.png out.png filter 36
diff -b out.png filtered/2048/noise_alpha=36.png

./quadtree imgs/2048/wood.png out.png filter 4.4
diff -b out.png filtered/2048/wood_alpha=4.4.png

-- Compress 2048 -- 
./quadtree imgs/2048/bricks.png out.png compress 250000
diff -b out.png compressed/2048/bricks_h=250000_alpha=6.png

./quadtree imgs/2048/checkers.png out.png compress 900000 
diff -b out.png compressed/2048/checkers_h=900000_alpha=42.png

./quadtree imgs/2048/lava.png out.png compress 260000
diff -b out.png compressed/2048/lava_h=260000_alpha=7.png

./quadtree imgs/2048/noise.png out.png compress 700000 
diff -b out.png compressed/2048/noise_h=700000_alpha=36.png

./quadtree imgs/2048/wood.png out.png compress 220000
diff -b out.png compressed/2048/wood_h=220000_alpha=4.png

Lo dejo aca por si a alguien le sirve!

**Comment by alexaptib** [comment]
@vichoeq tengo una duda de lo que me retorna hacer el diff -b.

hice un filtrado, y hice el diff con su respuesta (6.3) y con otra que no era su respuesta (4.8) 
y me da lo siguiente:

6.3 - >  No imprime nada por lo que asumo que esta bien.
4.8 -> Binary files out.png and Tests T1/filtered/1024/tulips_alpha=4.8.png differ

De esto asumo que esta bien mi algoritmo, pero al hacer la comparación pixel a pixel me da que la gran mayoría esta mal (visualmente no veo diferencia). Me quedo tranquilo con el resultado de diff -b y asumo que mi comparación esta mal?

**Comment by miguelramirezv** [comment]
Las imágenes de tamaño 2048 son con como los "tests largos" o no? O sea, si los comandos de @mora4 (gracias por los comandos @mora4 !! 🙌🙌🙌) nos corren en menos de 10 segundos, entonces estamos bien de tiempo o no?

Gracias!

**Comment by vichoeq** [comment]
Creele al diff. Recomiendo que generes una imagen diferencia para ver visualmente donde difieren ambas imagenes.

**Comment by vichoeq** [comment]
@miguelramirezv efectivamente, no habrá tests más grandes que eso.
