### ISSUE TITLE
Interpretación del h

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#129]
Hola, como se interpretaría el h según la tarea?

Por ejemplo si tengo tres niveles (raiz, primer nivel de hijos y segundo nivel de hijos), el h vendría siendo 2 o 3?

**Comment by vichoeq** [comment]
Hola, ¿qué quieres decir con intepretación?

De acuerdo a la definición de compresión usando Quadtree, `h` es la cantidad máxima de **hojas** que puede tener un árbol filtrado con un _alpha_ dado.

> Por ejemplo si tengo tres niveles (raiz, primer nivel de hijos y segundo nivel de hijos), el h vendría siendo 2 o 3?

`h` es un parámetro de la compresión, no una propiedad del árbol.
