### ISSUE TITLE
Duda output compressed

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#130]
Hola, en la carpeta de las imágenes compressed aparecen como nombreimagen_alpha=X, supongo que ese alpha en realidad debería ser un h que es el input de este modo de uso. De otra forma como podemos checkear la compresión?

**Comment by caespinoza5** [comment]
En la carpeta de las imágenes compressed aparecen como `nombreimagen_h=N(alpha=M).png` El N es el PARAM a utilizar en tal caso.
