### ISSUE TITLE
Tarea 1: Crear un color

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2020-1#131]
Hola!
Para crear un ```struct Color``` deberíamos usar  memoria del Stack? Es que no veo una función ```color_init``` en la librería, entonces está bien si uso esta sintaxis para crear un ```Color``` dentro de mi función
```
Color my_color = {10, 10, 10};
```
?
Gracias! Saludos.

**Comment by vichoeq** [comment]
Efectivamente. En el código base hay un ejemplo de la inicialización de un Color para que le eches una mirada.
