### ISSUE TITLE
Comando para testear

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#132]
Hola,

Como en la tarea pasada ¿hay algún comando para testear todos los tests? Además, me da un problema al testear con los archivos compressed, debido al símbolo (. Es decir no me deja hacer diff -b out.png compressed/256/emblem_h=15000(alpha=6).png pero si diff -b out.png 'compressed/256/emblem_h=15000(alpha=6).png'

Es válido esto?

**Comment by caespinoza5** [comment]
¡Hola!

Guiándote por el comando de la tarea 0, puedes modificarlo levemente para que puedas testear todos los tests con tan solo un comando. Te recomiendo que leas [este recurso](https://linux4one.com/bash-for-loop-with-examples/) para más información.

Con respecto al problema que estás teniendo con diff, es válido agregar las comillas, por lo que lo puedes utilizar nuevamente en esta tarea para checkear que la imagen generada por tu programa es la correcta.
