### ISSUE TITLE
[Tarea 1] Segmentation Fault 11 al inicio

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#134]
Hola! Estaba teniendo un problema con segmentation fault al inicio de todo mi programa y no lo puedo encontrar! Esto porque en el main tengo:

int main(int argc, char **argv)
{
  printf("algo!");
  /* Si los parámetros del programa son inválidos */
  if (!check_arguments(argc, argv))

Es decir, tengo el printf lo primero que debería pasar pero igual no se imprime y sale segmetantion fault 11 al tiro. Me sale así:

`Miguels-MacBook-Pro:T1-2020-1-miguelramirezv mikemike$ ./quadtree imgs/lena.png out.png filter 10
Segmentation fault: 11
`

Entonces no sé porque podría estar pasando ni sé donde más poner printfs para encontrar el error, como lo pongo lo más arriba y ni siquiera lo nota, además no he cambiado en nada en el main arriba de ese printf. Solo agregué el archivo #include "tree.h". Sería de mucha ayuda una idea de cómo encontrar el error.

Muchas gracias!!

**Comment by caespinoza5** [comment]
¡Hola!

Primero, intenta colocar un printf("algo\n") en vez de printf("algo"); a veces con un simple "\n" el programa empieza a imprimir.

Lo otro, ¿Puedes mostrar qué output te entrega si es que ejecutas tu programa con valgrind?

**Comment by miguelramirezv** [comment]
Era eso! Ahora le puse \n a las que me faltaban y me imprime todo, así sí puedo buscar el problema!!

Muchísimas gracias! 😄😄😄
