### ISSUE TITLE
Error ubuntu

### ISSUE THREAD

**Issue by fthurtado** [IIC2133-PUC/2020-1#135]
Hola! No he podido partir bien la tarea debido a un error que tengo al tratar de hacer make, y no encuentro la forma de solucionarlo.
Esto es lo que me aparece en el terminal.

compiled 'obj/imagelib/imagelib.o'
compiled 'obj/quadtree/main.o'
compiled 'obj/quadtree/funciones.o'
obj/quadtree/funciones.o: En la función `quadTree_init':
/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:8: definiciones múltiples de `quadTree_init'
obj/quadtree/main.o:/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:8: primero se definió aquí
obj/quadtree/funciones.o: En la función `quadTree_append':
/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:16: definiciones múltiples de `quadTree_append'
obj/quadtree/main.o:/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:16: primero se definió aquí
collect2: error: ld returned 1 exit status
Makefile:119: recipe for target 'quadtree' failed
make: *** [quadtree] Error 1

Y ya traté al hacer 'make clean' antes de probar.

**Comment by caespinoza5** [comment]
¿Te aseguraste de no estar importando archivos `.c` y solo archivos `.h`?

**Comment by fthurtado** [comment]
No sabía eso! Pero entonces no puedo tener un archivos con mis funciones (init, append, destroy) para el árbol, el cual lo importe desde main? 
Y en ese caso como lo tendría que hacer? Definiendo estas funciones en el main?

**Comment by caespinoza5** [comment]
¡Si puedes! Debes declarar las funciones en funciones.h, definirlas en funciones.c e importarlas en tu main. Te recomiendo que le des un vistazo a cómo están organizados los archivos en el Taller 0 de C disponible en el repositorio, y si sigues con duda lo comentas en esta issue.

**Comment by fthurtado** [comment]
Toda la razón! Me confundí nomas, gracias!!
