### ISSUE TITLE
Fecha I2

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#136]
Hola, que pasará con la fecha de la I2? Se mantendrá y abarcará menos materia o se va a correr?

**Comment by vichoeq** [comment]
Se mantiene la fecha. Entrará solo la materia que alcanzamos a terminar de ver, por lo que árboles rojo-negro quedarán fuera.

**Comment by Arcoirisky** [comment]
@VicenteMerino ¿podrias ser especifico sobre qué materia entra? Lo último que entraba en la i1 era Heaps y Heapsort y de ahí se empezó con ABB hasta Arboles 2-3 
¿Sería todo eso de arboles? ¿Desde ABB hasta 2-3?

**Comment by vichoeq** [comment]
@Arcoirisky Etiquetaste al Vicente equivocado. Para la I2 entrará

- ABB
- AVL
- 2-3

**Comment by Arcoirisky** [comment]
AKDNKSKDKS NO ME DI CUENTA QUE AMBOS ERAN VICENTE xD Gracias @vichoeq correcto amndms
