### ISSUE TITLE
Error al probar imágenes grandes

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#137]
Hola,

Intenté probar el algoritmo filter (para imágenes pequeñas funciona bien) con una de las imágenes más grandes (bricks.png) y el terminal me entregó un output "Killed", acto seguido se cayó el editor de texto y tuve que reabrirlo. ¿Tiene que ver con mi computador, o estoy haciendo algo mal relacionado a manejo de memoria?

Salu2

**Comment by yerkko** [comment]
Eso es probablemente que te quedaste sin ram :( intenta ver si estás usando más memoria de la necesaria

**Comment by miguelramirezv** [comment]
Hola! A mi me pasó lo mismo con las imágenes de 2048, pero las otras no me mostró leak ni errores de memorias. Se consideraría malo las de 2048 que salga un KILLED o no?
