### ISSUE TITLE
Complejidad construcción del árbol

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#139]
Hola, cuando se pide en el informe por la complejidad de la construcción del árbol, se refiere al árbol en que las hojas son los "pixeles" verdad? Pregunto, ya que en el algoritmo de filtración se deja como "hoja" aquel cuadrante en que gamma <= alpha, entonces no se si esto cambia mi "construccion del arbol", o el cambiar la hoja y este tipo de características las debo tomar en cuenta solo para el algoritmo de filtración/compresión.

**Comment by cacosandon** [comment]
Hola!

Debes hacer un análisis tanto para la construcción del árbol, como para luego los sub-algoritmos de filtración y compresión. Los sub-algoritmos son realizados a partir de un Quad-Tree ya construído. Avísame si te queda claro!
