### ISSUE TITLE
Duda main

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2133-PUC/2020-1#14]
Hola no entiendo por qué se usa & en este contexto 
![image](https://user-images.githubusercontent.com/39094323/77831049-7fbea180-710b-11ea-97b7-1d03fdd63ca4.png)
Saludos!

**Comment by arbiocanpion** [comment]
Hola! 
Lo que hace esa linea es recibir el archivo  y setear el valor que esta en la linea a la variables terminal, passenger_id  y priority. 
El & se usa por definicion de la funcion, ya que esta pide el puntero a la variable
Te dejo este link por si tienes mas dudas!
https://www.tutorialspoint.com/c_standard_library/c_function_fscanf.htm

**Comment by miguelramirezv** [comment]
Hola! Yo también tenía dudas con la lectura del archivo y con &. Por ejemplo, esta línea que parte la base del proyecto que nos entregaron;:

// Leemos la cantidad de terminales
  int terminal_count;
  fscanf(file, "%i", &terminal_count);

¿Cómo sabe el programa que se está leyendo la primera fila? ¿Por que asume que lo primero que se lee es la primera?

Si es así, ne surge la duda después porque el programa sigue como:

for (int term = 0; term < terminal_count; term++)
  {
    int gate_count;
    fscanf(file, "%i", &gate_count);
    // TODO: Inicializar terminal
    printf("terminal #%i: %i puertas\n", term, gate_count);
  }

Aquí, ¿como sabe el programa que linea le toca ir revisando? Porque se va usando en cada loop el mismo comando "fscanf(file, "%i", &gate_count);", que no sé bien como sabe qué linea del archivo tiene que leer.

Muchas gracias!!

**Comment by arbiocanpion** [comment]
Hola @miguelramirezv 
Respecto a tu primera pregunta, el programa solo sabe que esta leyendo la primera linea del .txt, esto debido a que la función fscanf lee por default desde la primera linea del archivo cuando se le inicializa.
Respecto a tu segunda pregunta, fscanf lee según las variables que tu le indiques que habran, por ejemplo si tienes el siguiente .txt

d 
e
f
g 
h 
i

y el siguiente código 
```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

bool string_equals(char* string1, char* string2)
{
  return !strcmp(string1, string2);
}
void leer(char* filename)
{
  // Abrimos el archivo
  FILE* file = fopen(filename, "r");

  char command[32];
  char command2[32];

  while(true)
  {
    fscanf(file, "%s %s", command,command2);
    printf("%s %s \n", command,command2);
    if (!strcmp(command, "h"))
    {
      break;
    }
  }

  fclose(file);
}

int main(int argc, char *argv[])
{

  leer(argv[1]);

  return 0;
}
```

Este te printeara 

d e
f g
h i

Pero en cambio si cambias 

```c
    fscanf(file, "%s %s", command,command2);
    printf("%s %s \n", command,command2);
```

por 
```c
    fscanf(file, "%s", command);
    printf("%s \n", command);
```

El código ahora te printeara 
d
e
f
g
h
i

Esto debido a que para fscanf cada str del archivo que lee termina cuando hay un espacio, entonces una vez que acaban las variables que tu se le piden leer, fscanf queda en stand by en el primer string despues del último string que leyo. Así que cuando se le vuelve a llamar prosigue desde el punto indicado anteriormente. 

Como complemento a tu duda respecto a como sabe que linea esta leyendo, realmente fscanf no sabe eso para el txt son solo strings, espacios y saltos de linea, pero para fscanf un salto de linea o un espacio normal son lo mismo, ya que solo le importa cuando acaba un string y comienza el siguiente en el txt, de hecho si cambias en el .txt a 
d e f g h i 
en vez de lo que indique al comienzo, el ouput sera el mismo a como es con el .txt que indique inicialmente.
Tambien como detalle fscanf leera las variables segun el formato que tu le indiques, es decir si pones %i en vez de %s, el programa guardara una información que no tiene nada que ver respecto a lo que hay en el txt.

Cualquier duda comentas por aca.
