### ISSUE TITLE
Problemas con repositorio T1

### ISSUE THREAD

**Issue by dlcartagena** [IIC2133-PUC/2020-1#140]
Hola, estoy tratando de acceder a mi repositorio para la tarea 1, sin embargo me apareció que la invitación había vencido, y no tengo acceso.

Saludos!

**Comment by caespinoza5** [comment]
¡Hola! Se te acaba de reenviar una invitación. Favor este tipo de problemas enviarlos por correo (como aparece en el anuncio de la Tarea 1).

¡Saludos!

**Comment by dlcartagena** [comment]
Eso fue rápido jajaja 

Muchas gracias!
