### ISSUE TITLE
Cálculo desviación estandar

### ISSUE THREAD

**Issue by yerkko** [IIC2133-PUC/2020-1#141]
Dada la confusión que hemos notado en los canales de comunicación, consideramos preciso clarificar la fórmula de la desviación estandar usada en la tarea.
Es necesario que calculen la desviación estandar **por canal** y se dirá que la desviación estandar final será el promedio entre los tres canales. 
No confundir esto con considerar que la desviación estandar de un nodo será el promedio de las desviaciones de sus hijos. Esto **no** es así y tendrán errores dado que el operador varianza **no** es lineal. (Para ver cómo pueden agregar un factor de arreglo a este cálculo, revisar la referencia del cálculo incremental, aunque reiteramos, **no** es necesario) 

![image](https://user-images.githubusercontent.com/48332955/80610004-ce12d900-8a06-11ea-897e-2b4ff8555797.png)

EDIT: @camaruri había comentado que la fórmula tenía un error, este ha sido solucionado. Gracias por notarlo :)

**Comment by camaruri** [comment]
Hola en el link que mandaron de métodos incrementales, la varianza queda dado por la siguiente formula. Que no es la misma que sale en esta issue.
<img width="539" alt="Captura de Pantalla 2020-04-29 a la(s) 10 22 57" src="https://user-images.githubusercontent.com/53882047/80607361-673ff080-8a03-11ea-931c-4b3d21f9e6a2.png">

**Comment by yerkko** [comment]
Tienes toda la razón, me faltó añadir el cuadrado al segundo término, ahora lo agrego

**Comment by faamigo** [comment]
no entendí muy bien, entonces si hago los cálculos de forma incremental no tengo que usar un factor de corrección o si?

**Comment by vichoeq** [comment]
@faamigo a que te refieres con un "factor de corrección" ?

**Comment by faamigo** [comment]
Perdón, me equivoqué, me refiero al factor de arreglo que mencionan más arriba

**Comment by vichoeq** [comment]
El "factor de arreglo" es básicamente el termino que falta si es que tratas de calcular la desviación estandar de un nodo a partir de las desviaciones estandar de sus hijos. 

Si calculas la desviacion estandar directamente para cada nodo o de manera incremental no hace falta ese factor.

**Comment by faamigo** [comment]
ok, gracias!
