### ISSUE TITLE
Cálculo complejidad algoritmo img_square_paint

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#143]
Hola, como estoy usando este algoritmo que viene en el código base, debería analizar la complejidad de este, si es que añade un grado de complejidad al algoritmo total?

**Comment by vichoeq** [comment]
La complejidad de esa funcion es el tamaño del cuadrado a pintar, pero puedes dejarla fuera del análisis si quieres.

**Comment by VicenteMerino** [comment]
Hola Vicente, a qué te refieres con tamaño? Que viendolo, recorre una vez el largo y una vez el ancho, por lo que sería O(largo+ancho) y no O(largo*ancho), así que en verdad mi pregunta es si apuntas el "tamaño" a las dimensiones o el área del cuadrado en tu repuesta.

**Comment by cacosandon** [comment]
Hola @VicenteMerino!

La función `memcpy` usada copa una fila, por lo que sí estás tomando la complejidad como el tamaño del cuadrado o área.
