### ISSUE TITLE
Tiempo de algoritmo

### ISSUE THREAD

**Issue by fthurtado** [IIC2133-PUC/2020-1#144]
Hola! Tengo una pregunta, yo cuando corro mi código sin valgrind este demora 1 segundo, pero al hacerlo con valgrind demora mucho más (el que probé 40 segundos).

Al momento de evaluar, el tiempo lo toman corriendo con valgrind o sin este? Y esto pasa debido a valgrind o es por la eficiencia de mi código?

**Comment by caespinoza5** [comment]
¡Hola!

Favor revisa [esta issue](https://github.com/IIC2133-PUC/2020-1/issues/62); muchas de las cosas explicadas aquí aplican para todas las tareas.

¡Saludos!
