### ISSUE TITLE
Errores de memoria

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#145]
Hola,

Hay algo que no me queda claro. ¿Los errores de memoria que NO sean memory leaks, qué significan exactamente y cómo se pueden identificar? En la tarea 0 no tuve ningún memory leak, pero si tuve errores de memoria y quisiera evitar eso para esta tarea (si, ya revisé de nuevo lo del taller de C sobre memoria, pero aún no me queda claro)

Saludos y gracias de antemano

**Comment by caespinoza5** [comment]
A grandes rasgos, leaks son cuando pediste más memoria al sistema operativo (mediante malloc, por ejemplo) y luego no la devolviste (ergo, te faltó hacer frees en tu código). Por ejemplo, teniendo el siguiente código:
```c
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char **argv)
{
  int a = malloc(sizeof(int));
}
```
Te aparecerá que tienes leaks con valgrind ("definitely lost: 4 bytes in 1 blocks"), ya que nunca hiciste free del espacio que solicitaste al heap de memoria. Por otro lado, errores de memoria son accesos o escrituras inválidas que haces en el heap de memoria. Por ejemplo, en el siguiente código:
```c
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char **argv)
{
  int *a = malloc(sizeof(int));
  a[1] = 1;
  free(a);
}
```
Te aparecerá que tienes 1 error en 1 contexto con valgrind, ya que intentaste escribir en un espacio que no habías solicitado (a[1]). Por lo tanto, para asegurarte que no tengas leaks, al ejecutar tu programa con valgrind debe aparecer `All heap blocks were freed -- no leaks are possible`. Por otro lado, para asegurarte que no tenga errores, al ejecutar tu programa con valgrind debe aparecer `ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)`. 

En los comentarios del taller 0 de C, en el ejercicio 6, aparece más en detalle esto.

**Comment by vichoeq** [comment]
Hola, 

Los leaks son memoria que queda marcada como utilizada para el sistema operativo. La unica consecuencia que tiene es que luego de que tu programa termina esa memoria no se puede usar, lo que a la larga hace que el computador se vuelva lento. 

Los errores de memoria son el uso inválido de variables o el uso de variables inválidas. Su consecuencia es que el output de tu programa se vuelve impredecible y en ocasiones aleatorio. Es la principal causa de bugs en programas escritos en C o C++. Existen 3 principales errores de memoria:

* Uso de el valor de una variable que no ha sido inicializada

```c
int a;
int b = 2 * a; // El valor de b será básicamente aleatorio
```

* Lectura de una dirección de memoria a partir de una no relacionada
* Escritura de una dirección de memoria a partir de una no relacionada

```c
int* A = malloc(10*sizeof(int)); // Digamos que este malloc entrega la dirección de memoria #20
int* B = malloc(10*sizeof(int)); // Digamos que este malloc, coincidentalmente, entrega la dirección de memoria #60, es decir 10 * 4 (usualmente el sizeof(int)) posiciones mas adelante.

// Notese que la dirección de memoria A[10] es la misma que B[0]. Pero acceder a ella desde A es inválido, porque probablemente no es lo que pretendas hacer.

// Esto es una lectura inválida a partir de A
printf("%i\n", A[10]);

// Esto es una escritura inválida a partir de A
A[10] = 156;

// Y es esta la que mayor problemas te puede producir, ya que estás modificando los valores de otras variables de tu programa.

// A[10] no es una dirección de memoria inválida de por sí, pero acceder a ella desde A sí lo es

```

Nótese que estos 3 errores de memoria serán identificados por valgrind **si la memoria está en el heap** (es decir, es producto de un malloc). Si la memoria es del stack valgrind no identificará estos errores.

Espero que esto ayude a resolver tu duda.

Saludos!
