### ISSUE TITLE
Complejidad en términos de alpha y h

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#146]
Hola, no entiendo bien como debo dejar la complejidad en término de alpha y h, ya que no encuentro que mi algoritmo tenga una forma T(n,alpha) o T(n,h), puesto que en la filtración y la compresión yo no estoy iterando sobre estos parámetros y la complejidad de estos argumentos es indirecta, y no se cuanto voy a estar avanzando en cada iteración o recursion en la búsqueda del h o del alfa, o en que momento lo encontraré, ya que depende más que nada (sobre todo para el filter) de la composición de colores que tenga la imagen. Lo que si puedo saber es ver el peor o mejor caso dependiendo del input, por ejemplo para un alfa muy chico, podría significar que deba recorrer todos los nodos, y para un alfa muy grande, podría significar que solo recorra la raiz. Es válido hacer un análisis como el descrito?

**Comment by vichoeq** [comment]
Es perfectamente válido si según tu análisis llegas a que la complejidad no depende ni de alpha ni de h. Mientras lo justifiques todo bien :+1:

**Comment by tpcantergiani** [comment]
Las complejidades las debemos dejar en relación al numero de nodos del árbol o el ancho de la imagen?

**Comment by vichoeq** [comment]
Ambos son válidos ya que el numero de nodos depende de las dimensiones de la imagen.
