### ISSUE TITLE
binary search

### ISSUE THREAD

**Issue by dacampos1** [IIC2133-PUC/2020-1#148]
Hola!, tengo dudas respecto a como aplicar el binary search al problema ya que en este caso como se busca minimizar el alpha y el h, no hay una condición de parada para el binary search. Entiendo que se debe usar para buscar el alpha pero como podría ser eficiente si cada vez debo realizar la filtración para saber el número de hojas

**Comment by jnhasard** [comment]
La gracia de hacer binary search en este problema es que siempre harás 7 intentos de filtro (log base 2 de 128) en vez de entre 0 y 128 intentos. Como nunca se va a tener exactamente h hojas hay que ir guardando el mayor alpha que siga cumpliendo la condición de las hojas.
