### ISSUE TITLE
Perdida de Color

### ISSUE THREAD

**Issue by brayanmoreno** [IIC2133-PUC/2020-1#149]
Revisando que me código funcionara bien, me di cuenta que cuando utilizaba alpha = 0, la imagen que obtenía de output era distinta que la original (lo cual seria un error dado que se debería obtener la misma imagen). Tras mucho revisar, me di cuenta que el problema no era de mi código, si no de las funciones que se nos dieron para leer y escribir una imagen (**img_png_write_to_file** y **img_png_read_from_file**). El error es que cuando se escribe la imagen procesada "se pierde un poco de color", por lo cual estas al compararlas dan distinto.
Para mostrarlo, comente el procesamiento en mi código y solo deje un ciclo que lee y escribe la misma imagen para ver el resultado:
![Captura de pantalla de 2020-04-29 22-01-52](https://user-images.githubusercontent.com/37162737/80664574-1eb91f00-8a65-11ea-820a-8a6d72d04f41.png)
El resultado de la imagen lena.png fue:
![out](https://user-images.githubusercontent.com/37162737/80664758-971fe000-8a65-11ea-91ad-13024d792e01.png)
Si la comparan con la original se nota la diferencia. No se si esto afecta en algo, ya que los test me dan bien pero supongo que es porque se crearon con las mismas funciones.

**Comment by vichoeq** [comment]
A decir verdad ese código que convierte de RGB a Lab y viceversa no es el mejor, pero nos dimos cuenta de eso una vez que ya se habia publicado la tarea. Pero como los test se hicieron usando ese mismo código, no debería haber problemas.

Saludos!

**Comment by brayanmoreno** [comment]
Ok, muchas gracias.
