### ISSUE TITLE
Correr ejemplos clases 

### ISSUE THREAD

**Issue by kelseyfranken** [IIC2133-PUC/2020-1#15]
Hola, cuando trato de correr el codigo de hello world de las clases, usando el makefile para compilar me dice "Permiso denegado" Como puedo arreglar esto?
![Captura de pantalla de 2020-03-28 15-47-06](https://user-images.githubusercontent.com/42187498/77831114-e217a200-710b-11ea-8548-32eba1424431.png)

**Comment by arbiocanpion** [comment]
Hola!
Sucede que no debes de ejecutar el main.c, lo que debes hacer es primero ejecutar gcc -o nombre_del_output nombre_del_input.c en la carpeta, y despues ejecutar ./nombre_del_output

**Comment by prochotito-rises** [comment]
Hola! Lo que ejecutas no es el código .c sino el archivo que crea el compilador, el que debiese encontrarse en tu carpeta Ejemplos, con el mismo nombre del código, pero sin la extensión .c. En el caso que muestras sería helloworld y lo ejecutas escribiendo ./helloworld en la carpeta Ejemplos.
