### ISSUE TITLE
[Materia] Complejidad y tipo Sucesor(A) [ABB]

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#150]
Hola!
Estaba estudiando la clase de ABB y quedé con varias dudas sobre el sucesor y antecesor de un árbol (pensemos solo en sucesor que sería lo mismo pero al revés para el antecesor) 

Primero que nada ¿como se podría ver el orden para la función que se presenta en las diapositivas Sucesor(A) o en su defecto Min(A)?
La internet habla de algo llamado In-Orden, Post-Orden y Pre-Orden pero al parecer no tienen nada que ver con el orden de un árbol (o quizás si y yo no estoy entendiéndolo como debería) 

Lo que sí descubrí es que nosotros en el PowerPoint usamos la versión in-Orden. Esta dice que el sucesor será el nodo más a la izquierda de los subarboles del hijo derecho de mi nodo actual. Aka, el mínimo de mi hijo derecho. 

¿Como sería en la definición en casos Pre-Orden y Post-Orden? ¿Que significan estas cosas? ¿Que son estas cosas? Y ¿cómo me afectan en la complejidad de mi búsqueda de un sucesor?

**Comment by Arcoirisky** [comment]
Ya logré descubrir qué son y cómo funcionan. 
![F8482F94-C62C-4B22-949D-A3360FC4D6BA](https://user-images.githubusercontent.com/26121402/80780318-98700c00-8b3c-11ea-81a3-728caccbb89a.jpeg)

Son formas de recorrer un árbol y dependiendo de lo que necesitas usas uno u otro. Por eso usamos in-orden para el sucesor o para calcular el mínimo. Una vez entienden como se usan, entiendes el porqué.

Y sobre el cómo afecta, puede separarse en el mejor y peor caso como siempre pero el sepáralo por método de recorrido es, por decir algo suave, innecesario. 

Ahora, solo me quedaría la siguiente duda ¿cual sería la complejidad promedio de este método? Mi interior me dice que no puede ser logN porque es una búsqueda casi lineal hacia abajo a partir de un nodo... así que debería ser N con N la profundidad de la rama.

**Comment by Arcoirisky** [comment]
Olvídenlo, ese N no es el N que conocemos y amamos. Es profundidad y la profundidad en el verdadero N me da que la complejidad es Log(N) 
TODO ES LOG(N)

**Comment by yadran** [comment]
Sólo con respecto a los tipos de recorrido:

Inorden y los otros son formas (algoritmos) de recorrer un árbol (en este
caso, binario).
En principio, no tienen nada que ver con el tipo de árbol (p.ej., puede ser
ternario), ni su
contenido (p.ej., la info almacenada puede estar ordenada o no), ni nada.
Cuál usar
depende de qué quieres conseguir finalmente.

Sólo son algoritmos (que se pueden escribir fácilmente de manera recursiva)
para
visitar "sin repetir ni equivocarse" cada nodo del árbol.
La diferencia entre ellos es en qué momento visitas la raíz: en inorden es
"al medio", es decir,
después de visitar (recursivamente) el subárbol izquierdo y antes de
visitar el subárbol derecho;
en preorden es al principio, antes de visitar (recursivamente) el subárbol
izquierdo y el subárbol
derecho; y en postorden es al final.  Como lo puedes ver en tus propios
ejemplos.

En cuanto a complejidad, los tres algoritmos --que recorren exhaustivamente
del árbol-- son
teta(número de nodos del árbol); es decir, son O y Omega(número de nodos
del árbol).
Son Omega porque tú quieres recorrer el árbol completo, y por lo tanto
necesitas visitar cada
nodo al menos una vez; son O porque están implementados astutamente.

--Yadran

**Comment by Arcoirisky** [comment]
@yadran entiendo, eso es porque son algoritmos de recorrido. 
Entonces no deberían de influir significativamente en mi búsqueda de un mínimo o un máximo. En eso influye la profundidad de mi árbol.

Gracias!!
