### ISSUE TITLE
Notas informe T0

### ISSUE THREAD

**Issue by jcechavarri** [IIC2133-PUC/2020-1#151]
Hola!

Las notas del informe de la T0 las van a tener antes del 10/05? Como para saber si voy a poder corregir errores de formato que podría haber cometido en el informe de la T1 también?

Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Sí, las notas de los informes estarán antes del 10/05.

**Comment by VicenteMerino** [comment]
Al final que pasará con esto? En lo personal quiero entregar en el plazo original, y ver si debo corregir algún error.

**Comment by caespinoza5** [comment]
¡Las notas estarán hoy!
