### ISSUE TITLE
Evaluación Tiempo T1

### ISSUE THREAD

**Issue by NicolasCastillo24** [IIC2133-PUC/2020-1#152]
Hola! 
Quería saber si corregirán el tiempo con el que retorna la consola al correr **time** ./quadtree... como en la T0 o el que se imprime con el código base, que no cuenta el tiempo de lectura y escritura de imagen? Que para el caso mas grande de compress existe una diferencia de 4 segundos aprox. entre ambos resultados de tiempo.

Graciass

**Comment by Arcoirisky** [comment]
El enunciado decía q sería medido el tiempo de procesar la imagen, el tiempo que te imprime en la pantalla la base que nos dieron de la tarea

**Comment by trinigomez** [comment]
Hola! Una duda con respecto a esto tambien. Será medido el tiempo de correr con o sin valgrind? porque varía mucho.

**Comment by arbiocanpion** [comment]
@trinigomez sin Valgrind

**Comment by trinigomez** [comment]
gracias!
