### ISSUE TITLE
diff filter

### ISSUE THREAD

**Issue by dacampos1** [IIC2133-PUC/2020-1#153]
Hola!, he tenido problemas con el filtro varios tests no tienen diferencias pero en algunos tengo diferencias en los decimales de los colores, no sé si a alguien más le pasa. Usé la formula de sigma para cada canal que sale en el enunciado y después calcule el promedio, todo usando floats

**Comment by vichoeq** [comment]
Si tu problema son los decimales, prueba usando doubles en vez de floats, asi tienes mas precision en los calculos.

La pauta usa doubles, por si acaso.

**Comment by dacampos1** [comment]
siii eso era, gracias!
