### ISSUE TITLE
Complejidad eliminar 2-3 Tree

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#154]
Hola!

¿Cómo sería la complejidad para eliminar un nodo en un 2-3 tree? 
Hay varios casos posibles que pueden suceder pero no logro ver cómo poder obtener una complejidad promedio de esto...

**Comment by vichoeq** [comment]
Más que complejidad promedio, lo que tienes que hacer es ver la complejidad de cada caso: la complejidad del algoritmo va a ser la del peor de los casos.

**Comment by Arcoirisky** [comment]
Hmmmm... sería como inserción entonces?

**Comment by vichoeq** [comment]
Sip, O(altura del árbol)
