### ISSUE TITLE
Conmutatividad arbol binario

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#155]
¿Es la operación "eliminar" conmutativa? En el sentido de que eliminar "x" y luego eliminar "y" en un árbol binario deja el mismo árbol que eliminar "y" y luego eliminar "x".  Gracias!

**Comment by vichoeq** [comment]
Hola, no es conmutativa. Toma por ejemplo este árbol. Usaremos el sucesor como reemplazo del nodo si no es una hoja. Si usamos el antecesor puedes dar vuelta el árbol:

![15884480759841590450018](https://user-images.githubusercontent.com/5317897/80882105-a0d65d00-8c8a-11ea-957b-85053aabf196.jpg)

Saludos!

**Comment by chocopiano** [comment]
Tienes razón, me estaba confundiendo en algo super simple! Muchas gracias!
