### ISSUE TITLE
Error en sumatoria std

### ISSUE THREAD

**Issue by silvamatias** [IIC2133-PUC/2020-1#157]
Hola,

Estoy teniendo un problema en el filtro que no logro solucionar ni entender. Al probar con las imágenes de 256 me pasa que con "emblem" mi filtro difiere en lo siguiente (cuadrado rojo):

![diff](https://user-images.githubusercontent.com/13739643/80923161-d09b6880-8d4f-11ea-98ce-4682025314dc.png)

Cuando pruebo con la imagen "fossil" todo bien y cuando pruebo con "tiles" difiere en:

![diff2](https://user-images.githubusercontent.com/13739643/80923211-3daefe00-8d50-11ea-9c0c-1b68fa6f5dcd.png)

Luego de hacer harto debug me doy cuenta que el problema viene por la desviación estándar, en concreto cuando hago la sumatoria. Estoy sumando a un atributo de forma acumulable antes de hacer la división (1/n) y de sacar la raíz:

node->std_a += (x.a - x.promedio)^2  (esto es un ejemplo simplificado)

Pero cuando imprimo el resultado de node->std_a post la suma me doy cuenta de un problema:

<img width="465" alt="Screen Shot 2020-05-03 at 15 23 01" src="https://user-images.githubusercontent.com/13739643/80923549-81a30280-8d52-11ea-882a-a8b28917d76e.png">

Lo curioso (y lo que no logro entender) es que si yo imprimo lo que voy a sumar, esto siempre es un número y positivo (como debiera ser):

<img width="297" alt="Screen Shot 2020-05-03 at 15 34 45" src="https://user-images.githubusercontent.com/13739643/80923781-a9df3100-8d53-11ea-856f-ee6d83b845ec.png">

Por algún motivo al sumar la suma acumulada se transforma en ese numero negativo y gigante que luego al aplicarle raíz como es un numero negativo me entrega un "nan"

Alguien que le haya pasado o entienda por donde puede venir el problema?

**Comment by vichoeq** [comment]
Estas usando floats o doubles? Recuerda que los floats tienen 32 bits mientras que los double 64.

**Comment by silvamatias** [comment]
doubles!

**Comment by vichoeq** [comment]
Hola, probé tu código y efectivamente es raro que al sumar numeros positivos obtienes un numero negativo... a menos de que el número al que lo estés sumando haya sido negativo desde un principio. 😲 

![image](https://user-images.githubusercontent.com/5317897/80926106-01d16400-8d63-11ea-8aed-695bd968d87e.png)

Probé poner una linea para separar las distintas sumatorias, y podemos ver que ese `6.117612` es el primer numero en ser sumado, y aun asi el resultado da negativo! Eso significa que `std_a` ya era negativo de antes... al inicializarlo en 0 obtuve esto...

![image](https://user-images.githubusercontent.com/5317897/80926134-3e04c480-8d63-11ea-869b-02a2504c46bd.png)

Al probar el programa con **valgrind** lo primero que dice es que estás trabajando con valores no inicializados. Los numeros a sumar son los mismos, con la diferencia que el contenedor ahora sí parte desde 0.

Saludos!

**Comment by silvamatias** [comment]
gracias!!!
