### ISSUE TITLE
Error, respuestas practicamente iguales

### ISSUE THREAD

**Issue by trinigomez** [IIC2133-PUC/2020-1#158]
Hola! Al revisar muy detalladamente las fotos resultando de hacer filter veo que hay diferencias muy pequeñas entre mi respuesta y la subida

![comparacion respuestas](https://user-images.githubusercontent.com/37165720/81010909-065e5100-8e25-11ea-9156-444379139f2d.JPG)

El de la izquierda es mi output y el de la derecha es la respuesta, se nota por ejemplo en la esquina izquierda arriba que están distintos. Corrí un código para ver las diferencias entre los gamma de mi output y la respuesta ,y por ejemplo, de 600 gammas analizados variaba en 20 (hice un excel). 

Asumo que se pinta mal en los casos borde (un poco sobre y un poco bajo de alpha), porque a veces pasa que en mi codigo se pintó un cuadrado más grande que en la foto, y en otro casos al reves, por lo tanto, no es un error sistemático. ¿Puede ser que al calcular los gamma de manera distinta que la pauta queden levemente distintos? ¿Si el output no está 100% igual está mala la tarea?

¿Hay alguna manera de ver si efectivamente los gammas varían en decimales o algo asi causando estas diferencias? (estoy usando doubles)

Gracias!

**Comment by vichoeq** [comment]
Si estás usando doubles el problema no debería ser la precisión. La unica explicación que tengo es que estés calculando mal los valores.

En particular, si tomas el gamma como la raiz del promedio en lugar del promedio de las raices te dará numeros muy parecidos pero distintos.  ¿Segura que no estás haciendo algo por el estilo?

Me imagino que valgrind dice que está todo bien, ¿no?

**Comment by trinigomez** [comment]
Si, valgrind me sale cero errores. 

Estoy tomando gamma como el promedio de las tres desviaciones estandar:

(sd_L + sd_a + sd_b)/3

**Comment by cchauriye** [comment]
Hola! Pudiste solucionarlo? estoy en las mismas...

**Comment by trinigomez** [comment]
No, aún no lo he podido arreglar :(

**Comment by cchauriye** [comment]
Lo logré! Yo estaba mal porque había entendido mal el enunciado. Para la desviación de un nodo, usaba el resultado de la desviación de los nodos inferiores, pero en verdad me di cuenta que hay que almacenar la desviación para a,b y L para cada nodo (yo solo estaba guardando el promedio desagregado).

**Comment by trinigomez** [comment]
Yo igual, tenia un error en un indice

**Comment by vichoeq** [comment]
No quería preguntar "están seguros de que están calculando bien la desviación estandar?" ... que bueno que lo hayan logrado solucionar :)
