### ISSUE TITLE
Dudas punteros o atributos nodos ABB Balanceados

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#159]
Hola! Tenía una duda sobre los atributos de los nodos ABB Balanceado específicamente, aunque tal vez aplica para todos los ABB. Como se da mucho como en el rebalanceo en los splits, que se va del nodo hijo al nodo padre, ¿se puede asumir que cada nodo tiene un atributo que es un puntero a su nodo padre? Aprovechando, siempre he asumido que cada nodo tiene punteros a sus hijos, ¿esto está bien?

Muchas gracias!

**Comment by vichoeq** [comment]
¿Hola, estás hablando de los árboles 2-3? 

Por que los ABB no hacen splits como describes...

No es necesario tener una referencia al nodo padre para hacer un split, pero no cambia la logica de la estructura si la agregas.

Si es necesario que los nodos tengan punteros a los hijos, ya que los árboles se recorren de arriba hacia abajo.

**Comment by Arcoirisky** [comment]
Igual ojo que los 2-3 no son binarios de ningún tipo por lo que no son ABB ni AVL ni similares :s 

Es un balanceado no binario 

Si te complica ver cómo funciona el split te siguieron buscar código hecho de árboles 2-3 y ahí analizarlos paso por paso. Eso me sirvió a mi para entenderlos
