### ISSUE TITLE
Duda Tarea 0

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#16]
![Screen Shot 2020-03-28 at 7 02 31 PM](https://user-images.githubusercontent.com/42516267/77834936-5e6bae80-7127-11ea-881c-710151c0d3f6.png)

Hola, tengo dudas con respecto a esta parte del código que nos entregaron para la tarea.

En las partes que dicen "inicializar estructura principal" e "inicializar terminal", ¿Tenemos que inicializar alguna matriz o algo similar que definamos como struct?

En general tengo la duda de cómo empezar bien la modelación de la tarea.

Saludos y gracias de antemano

**Comment by jeschuwirth** [comment]
Hola @matumartinez,

La tarea se puede hacer de muchas formas distintas, pero recomendamos fuertemente el uso de structs propias para modelar el problema.

Como te diste cuenta por los comentarios y los print, efectivamente la tarea está pensada para que en esas líneas hagas los \_\_init\_\_ de tus estructuras.

Si tu duda era otra o no quedo clara la explicación sigue comentando en la issue :)

Éxito!

**Comment by JoacoCoyu** [comment]
Hola!

Quería aprovechar de colgarme de esta issue y preguntar a modo clarificativo:

De lo archivos que nos pasan, al final solo tenemos que editar el main.c, no es necesario crear archivos extras?

Osea, entiendo que se pueden hacer archivos extra como para que la tarea esté más ordenada, pero tenía esta misma duda como partir modelando.

Gracias!

**Comment by jeschuwirth** [comment]
Recomiendo crear archivos extra, especialmente si se quieres utilizar una estructura propia.
