### ISSUE TITLE
Cálculo de NI 

### ISSUE THREAD

**Issue by fediaz3** [IIC2133-PUC/2020-1#160]
Hola

Tengo una duda sobre el calculo de las notas de las interrogaciones

Tengo entendido que se calcula como el promedio de las 7 mejores preguntas de la interrogaciones,
pero ahora se subieron puntajes por pregunta. ¿Cómo es la conversión a nota para calcular NI?

**Comment by caespinoza5** [comment]
¡Hola!
Toda la razón. Acabo de actualizar la planilla para que refleje la nota de cada una de las preguntas, que se traduce en `1` + (`puntaje_parte_a` + `puntaje_parte_b`)*`3` en este caso, donde el máximo de `puntaje_parte_a` es 1 y el `máximo de puntaje_parte_b` es 1.
Por el momento, se mantendrá la nota referencial de la I1 al final de la planilla, pero puedes encontrar la nota de cada pregunta ahora.
Enviaremos un anuncio más tarde aclarando este tema.

¡Muchas gracias por el aporte!
