### ISSUE TITLE
Duda Ejercicio AVL rama más corta

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#161]
Hola! Me encontré con esta pregunta revisando ejercicios pero no puedo encontrar una forma de llegar a la solución.

¿De qué tamaño es la rama más corta que puede tener un árbol AVL de altura h? Justifique. 
Solución: ⌊h/2⌋

Alguien sabe por qué es esa la respuesta? Cómo se llega a eso?
Gracias!!

**Comment by cacosandon** [comment]
Hola!

Te recomiendo ponerte en el peor caso: cuando el árbol está lo más desbalanceado posible pero cumpliendo con la regla de un árbol AVL.  Teniendo esto, podrás ver lo que mencionas **en el peor caso**, lo que se cumple obviamente para todos los demás, dado que la rama más corta tendrá altura <= ⌊h/2⌋
