### ISSUE TITLE
Preguntas Frecuentes I2

### ISSUE THREAD

**Issue by vichoeq** [IIC2133-PUC/2020-1#163]
La prueba esta pensada para hacerla en aproximadamente 2 horas.

Con respecto a los cálculos de complejidad, mientras más formal mejor. 

# 1

## a

* Puedes asumir que los numeros son distintos
* No puedes asumir **nada más** sobre L. 
* Se pide la complejidad en notación **Omega**. Eso indica un caso particular del algoritmo (tu deberías saber cuál es). 
* Qué características tiene L en **este caso** particular que define el Omega. (Antes de ser ordenada)
* El ejemplo tiene que mostrar las caracteristicas de L que acabas de describir.
* Para el ejemplo hay que mostrar como queda el árbol luego de cada inserción.
* No hace diferencia si L es una lista o una array.
* Puedes utilizar todas las funciones de ABB vistas en clases.
* Lo que se pide **no es un algoritmo**, sino el como utilizar el ABB para ordenar L.
* Tu procedimiento debe devolver una lista ordenada.

## b

* Ax, Bx y Cx son conjuntos. Ax (union) Bx (union) Cx = todos los nodos del árbol. 
Ax (inter) Bx = Vacío, Ax (inter) Cx = Vacio. 
* T es un ABB, aunque las propiedades de balance no afectan para esta pregunta.
* Ax contiene los (hijos izquierdos y sus descendientes) de los nodos en Bx.
* Cx contiene los (hijos derechos y sus descendientes) de los nodos en Bx.
* Bx = {b | b está en la ruta de busqueda hacia x}
* Ax = {a | a no está en Bx & (a es hijo izquierdo de un nodo en Bx o es descendiente de otro elemento en Ax)}
* Cx = {c | c no está en Bx & (c es hijo derecho de un nodo en Bx o es descendiente de otro elemento en Cx)}

# 2

## a

* Puedes asumir que los numeros son distintos
* No puedes asumir **nada más** sobre L. 
* Se pide la complejidad en notación **Omega**. Eso indica un caso particular del algoritmo (tu deberías saber cuál es). 
* Qué características tiene L en **este caso** particular que define el Omega. (Antes de ser ordenada)
* Para el ejemplo hay que mostrar como queda el árbol luego de cada inserción.
* No hace diferencia si L es una lista o una array.
* Puedes utilizar todas las funciones de AVL vistas en clases.
* Lo que se pide **no es un algoritmo**, sino el como utilizar el AVL para ordenar L.
* Tu procedimiento debe devolver una lista ordenada.
* Los elementos de L deben ser procesados en orden en el que vienen. 

## b

* Demuestra que en los casos que es necesaria una rotación simple, basta con una simple
* Y los casos que requieren de una rotación doble, basta una rotación doble.
* Si vas a hacer ejemplos, asegurate de que aplique para AVL en general, no un caso particular
* (Hint: Usa triangulos para representar los subarboles)

# 3

* n elementos = n claves
* Altura del árbol = número de niveles. (un árbol con un solo nodo tendría altura 1)

## a

* Se pide la altura exacta en función de n. No en notación O.
* Esta funcion debe estar justificada mediante una deducción.

## b

* Cuando se dice "que valores de n" hacen que el árbol crezca o no, hay que expresarlos en función de h.
* Estos valores pueden ser o uno solo o ser un rango de valores. Tu debes identificar eso.
* Debes justificar de donde vienen estos valores.

**Comment by VicenteMerino** [comment]
En la 3, cuando me hablan de "elementos" se refiere a los nodos. Que en la 3.b hablan de clave, entonces podría considerar una distinción ahí entre el significado de cada una.

**Comment by bvallejo1** [comment]
En la 1.a hay que ir sacando los elementos de L en el orden que están? o podemos manipular L como queramos? Hablo del momento de armar el árbol T

**Comment by camaruri** [comment]
Podemos usar conceptos vistos y demostrados en ayudantias?

**Comment by tpcantergiani** [comment]
La demostración de la complejidad en la 1.a debe ser matemática o con palabras basta?

**Comment by rodobkn** [comment]
se puede citar cosas? onda escribirlas con nuestras propias palabras, y luego decir de donde sacamos esa idea?

**Comment by VicenteMerino** [comment]
En la 2, lo que se pide ordenar debe quedar como un arreglo, o con tal que esté ordenado está bien? Que no se si el resultado de la ordenación debe estar en forma arreglo o árbol, no se si se entiende.

**Comment by cchauriye** [comment]
Podemos hacer referencia al desarrollo de una pregunta en otra pregunta?

**Comment by VicenteMerino** [comment]
x está en Bx verdad?

**Comment by trinigomez** [comment]
Podemos asumir las cosas vistas en clases como correctas o hay que demostrarlas igual?

**Comment by arbiocanpion** [comment]
@VicenteMerino  al referirse a elementos la pregunta se refiere al numero de elementos del arbol (los numeros), no los nodos del arbol 2-3, respecto a tu segunda pregunta, x no esta en Bx

@bvallejo1   puedes sacar los elementos en el orden que quieras

@camaruri  si son cosas de las ayudantías, cita que ayudantía (con link).

@tpcantergiani  puede ser matemática o en palabras, pero debe tener fundamentos.

@rodobkn  si, incluye los links o referencias correspondientes.

@cchauriye si, pero mejor referencia explicitamente hago referencia a lo x de la pregunta y. Eso si, si tienes una conclusión equivocada en la pregunta que citas, tu respuesta en la pregunta que estas citando estara equivocada.

@trinigomez  si puedes asumirlas como correctas, pero de igual manera indica que esa es tu fuente (incluyendo el link a la clase).

**Comment by miguelramirezv** [comment]
En la 3.a) A qué se refiere con la estructura del árbol? características? si es así, cuántas hay que dar aproximadamente?

**Comment by arbiocanpion** [comment]
@miguelramirezv al referirise a estructura del arbol, es describir el arbol de tal manera, que en caso de no tener una imagen, sea posible visualizarlo.

**Comment by VicenteMerino** [comment]
@arbiocanpion Estás seguro con lo de elementos? Siempre que buscamos la altura lo hacemos en función de la cantidad de nodos, no de claves y es así también como vimos el O() de la altura en clases.

**Comment by vichoeq** [comment]
Corrección a algunas respuestas de @arbiocanpion :

@VicenteMerino Cuando hablamos de elementos nos referimos a las claves. n es el numero de claves en el árbol (y ese es el n que usamos al hablar de O() en los 2-3) 

X **sí** está en Bx. Pero no debería cambiar tu respuesta.

@bvallejo1 Ojo que si manipulas los elementos tendrías que considerar ese paso en la complejidad. Lo mejor es formular tu algoritmo de manera que procese los elementos en el orden en el que vienen en L, asi no te cuesta complejidad extra.

**Comment by vichoeq** [comment]
@bvallejo1 cuidado además de no ordenar los datos de L usando algo que no sea ABB. La pregunta es de como usar ABBs para ordenar los datos, si los ordenas de otra manera va a estar mala.

@VicenteMerino sí, puedes asumir que no hay elementos repetidos en la 1b.

**Comment by isavega** [comment]
[1a]. Que el árbol sea sin autobalance se refiere a que no se pueden hacer rotaciones? o que no intenta mantener su altura al minimo?

**Comment by vichoeq** [comment]
@isavega que es un ABB a secas, por lo que no tiene mecanismos de balanceo. Y, por si acaso, tampoco puedes meterle mecanismos de balanceo: la idea es utilizar la estructura, no modificar su logica.

**Comment by BenjaPrograma** [comment]
A que se refieren con "Lo que se pide no es un algoritmo, sino el como utilizar el XXX para ordenar L.",
en el fondo si me preguntan el como utilizar la estructura para ordenar L, lo primero que se me viene a la mente, es como hacer un algoritmo que usando la estructura me devuelva L ordenada. ¿En que me estoy confundiendo?

**Comment by vichoeq** [comment]
@BenjaPrograma si tu respuesta es un algoritmo, y queda claro como usar el ABB para ordenar, entonces todo bien. Pero tambien puedes responder sin dar un algoritmo concreto, simplemente explicando como usar el ABB para ordenar. El "lo que se pide no es un algoritmo" es para que tengan presente que no es la unica forma de responder la pregunta. Ahi cada uno ve como le acomoda :)

**Comment by silvamatias** [comment]
> Altura del árbol = número de niveles. (un árbol con un solo nodo tendría altura 1)
Esto se refiere a un árbol con raíz + una hoja o uno que tiene solo raíz?

**Comment by vichoeq** [comment]
@silvamatias un arbol (2-3) que solo tiene nodo raiz (y por lo tanto la raiz es hoja), ya sea de 1 o 2 claves.

**Comment by raespinoza4** [comment]
Cuando piden las características de L estas tienen que ser generales o pueden ser específicas ? Por ejemplo decir que algunos L[i] tienen cierta relación con otros L[j]  es una característica válida o ya sería un supuesto de L ?

**Comment by yadran** [comment]
Rodrigo: Pueden ser específicas, como en tu ejemplo.  --Yadran

**Comment by camaruri** [comment]
para la 1-a debemos mostrar cada paso de como va quedando el arbol para n = 11.
O podemos mostrar el arbol como queda alfinal. 
Lo pregunto porque para la 2.a lo hize pero era n = 7 y igual tiene sentido por el desarrollo del AVL, pero quizas en ABB podriamos dejar el arbol como queda una vez armado?

**Comment by yadran** [comment]
Me gustaría la corroboración de Vicente E., pero yo creo que sería
suficiente
si, además del árbol final, muestras los 5 primeros pasos, y queda claro
que sabes
lo que estás haciendo.
--Yadran

**Comment by sameneses** [comment]
¿Es un problema si el documento es muy largo?
Ninguna de mis respuestas es tan larga, pero una la respondí con dibujos y esos ocupan mucho espacio

**Comment by yerkko** [comment]
@sameneses mientras se pueda subir a siding y no sea innecesariamente larga, no hay problema

**Comment by ljrodriguez1** [comment]
Se puede responder la 2a agarrandose de la 1a para no escribir todo de nuevo, ya que muchas cosas son parecidas

**Comment by yadran** [comment]
Como tú dices, son parecidas.  Así que … sí, pero hay que tener cuidado.
Además, sirve sólo si la 1a está correcta.  --Yadran

**Comment by ljrodriguez1** [comment]
Y cuando se nos dice que ejecutemos el algoritmo en 1 y 2 es para mostrar como se va armando el árbol, o también debemos mostrar la parte que ordena, ya que no se me ocurre bien como mostrarla.

**Comment by ljrodriguez1** [comment]
Por último al ir ejecutando el algoritmo en avl debo mostrar cuando agregó un nodo como queda no balanceado y luego balancear o solo mostrar el resultado balanceado?

**Comment by yadran** [comment]
En 1a, si la respuesta estuviera correcta, sería suficiente con mostrar los
primeros pasos
y el resultado final; lo importante es que quede claro que entienden lo que
están haciendo.
En 2a, hay que mostrar cómo queda inmediatamente después de la inserción
inicial, y, si
quedó desbalanceado, cómo queda una vez rebalanceado; de nuevo, nos tiene
que quedar
claro que entienden lo que están haciendo.  --Yadran

**Comment by javiinostroza** [comment]
En la 3b, cuando preguntan para qué valores de n está garantizado que si aumenta la altura, es en base a un árbol 2-3 cualquiera o al árbol que cumple las características de la pregunta anterior (¿Qué debe cumplirse para que esta inserción aumente la altura de T?)?

**Comment by yadran** [comment]
Javiera:  ¿Qué crees tú?  --Yadran

**Comment by vichoeq** [comment]
@camaruri Si, en la 1a tiene sentido mostrar los primeros pasos como dice Yadran tal que nos quede claro que saben lo que están haciendo. (Y el árbol final, claro)

**Comment by ljrodriguez1** [comment]
Para la 3b podemos asumir algo del árbol (yo dije que era 2-3) sobre cómo está armado (cuantos nodos dobles y triples tiene) o debe ser para cualquier forma de armar un árbol 2-3 con n llaves.

**Comment by yadran** [comment]
Sólo sabemos que tiene n llaves.
Ahora, tú puedes trabajar haciendo ciertos supuestos inicialmente,
e irlos relajando a medida que vas dándote cuenta de lo que está
pasando.
Finalmente, si tu respuesta es válida sólo bajo ciertos supuestos,
entonces déjalos explícitos y a la hora de corregir veremos qué tan
restrictivos son.
--Yadran

**Comment by ljrodriguez1** [comment]
Creo que ahora entendí, la pregunta es para que n dado ese h? Aseguró que si insertó un nodo crece la altura, es decir la pregunta hace alusion al árbol de n nodos de altura h?

**Comment by yadran** [comment]
Efectivamente, para cuál n dada la altura h.
Cuidado: n es el número de claves, no de nodos.
--Yadran
