### ISSUE TITLE
Entrega T1 en plazo original

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#164]
Hola! Cómo puedo optar por entregar la T1 en el plazo original? Subiendo el informe en el cuestionario actual y teniendo el último commit antes del lunes, es suficiente para esto? O hay que responder un cuestionario aparte también?

Muchas gracias!!

**Comment by vichoeq** [comment]
Ojo, el plazo original es codigo el sabado 9 e informe el domingo 10. 

Mientras tengas tu commit arriba para el sabado 9 a las 23:59 y el informe en el cuestionario del siding, todo bien.
