### ISSUE TITLE
métodos incrementales para armar árbol

### ISSUE THREAD

**Issue by tsgonzalez** [IIC2133-PUC/2020-1#166]
Hola! 

En el informe de la T1, basta con mencionar que utilizamos métodos incrementales para calcular promedios y desviaciones estándar, o debemos explicar en detalle como se calculan estos valores a partir de los promedios y desviaciones de los nodos hijos??

**Comment by yerkko** [comment]
No es necesario que desarrolles toda la fórmula, pero sí una breve descripción de cómo lo hiciste
