### ISSUE TITLE
[Tarea 1] Qué subimos a git?

### ISSUE THREAD

**Issue by cjones27** [IIC2133-PUC/2020-1#167]
Hola! 

Que archivos subimos a git y cuales ignoramos?

Gracias!

**Comment by yerkko** [comment]
No es necesario que suban las imagenes :)

**Comment by cjones27** [comment]
##Para chequear entonces:

Subimos:
obj, src, makefile y readme

No subimos:
imgs, compressed, filtered

**Comment by caespinoza5** [comment]
obj lo genera make, por lo que no es necesario que lo subas tampoco. Antes de subir, te recomiendo que hagas `make clean`, y luego añadas los archivos que quedan ahí.

**Comment by yerkko** [comment]
Como dice Cristóbal, los compilados .o no son necesarios tampoco

**Comment by cjones27** [comment]
Genial, gracias!
