### ISSUE TITLE
Enunciado Tarea 2

### ISSUE THREAD

**Issue by jnhasard** [IIC2133-PUC/2020-1#168]
Hola! 

Quería saber si es posible que independiente de que se haya atrasado la entrega de la tarea 1, si podían subir el enunciado de la tarea 2 (en caso de que esta este lista) para poder organizarnos mejor.  Graciass

**Comment by vichoeq** [comment]
Hola, el enunciado de la T2 se publicará la otra semana. No entiendo tu preocupación, ¿Organizarte en qué sentido?
