### ISSUE TITLE
Archivos entrega final

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#17]
Hola!
¿debemos subir al repositorio el archivo compilado de nuestra simulación o no debemos subir más que los archivos en src para que ustedes lo compilen por si mismos?

**Comment by jeschuwirth** [comment]
Hola @Arcoirisky,

Solo es necesario que suban los archivos en src y nosotros lo compilamos, sin embargo no hay problema con subir también los binarios.

Éxito!

**Comment by Arcoirisky** [comment]
Los binarios son las cosas que nos entregaron? Solo modifique src y usé git add src para no subir nada extra 
Con eso estaría bien entonces? O:

**Comment by jeschuwirth** [comment]
Los binarios son los archivo que se crean al hacer `make`.

Mientras tu programa compile con `make` y corra con la línea de comando especificada en el enunciado estas bien :)
