### ISSUE TITLE
[Tarea 1] Tiempos de ejecución

### ISSUE THREAD

**Issue by SaritaGP** [IIC2133-PUC/2020-1#172]
Hola! Quería saber si es posible que den las especificaciones del computador(es) o máquinas donde se ejecutarán las tareas. En particular para esta tarea al realizar la compresión si:
- La ejecuto en un notebook con I5, Windows: Se demoran 11 segundos algunas de las imágenes de 2048px, todas las otras se demoran menos de 8 segundos.
- La ejecuto en un computador de escritorio I7, Windows (gamer): Se demoran todas las imágenes menos de 4 segundos.
- La ejecuto en un notebook I7, Ubuntu: Se demoran todas las imágenes menos de 7 segundos.

La diferencia es grande :c ¿debería optimizarlo para que corra en menos tiempo en un computador como el primero?

**Comment by caespinoza5** [comment]
Las tareas se ejecutan en un computador con las siguientes características:
Procesador Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81GHz
RAM 12GB

**Comment by SaritaGP** [comment]
@caespinoza5 Genial! gracias

**Comment by tfflores** [comment]
> Las tareas se ejecutan en un computador con las siguientes características:
> Procesador Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81GHz
> RAM 12GB

Igual tengo dudas con respecto a esto, porque por ejemplo mi notebook tiene CPU I7-9750H, y para mi tarea se demoraba aprox 6.8 segundos (en modo rendimiento) en procesar el test más demandante, que era el compress de uno de los de 2500x2500. En modo full ahorro de batería, se demoraba 18.2 segundos en procesar la imagen, y por ejemplo en ese caso no tendría puntaje en teoría.

**Comment by caespinoza5** [comment]
Al corregir, el computador estará conectado y no estará en modo de ahorro de batería. Recordar que, de acuerdo a enunciado, su programa debe tomar 10 segundos **sin considerar el tiempo de lectura y escritura de imagen**. Por ejemplo, si leer y escribir la imagen "noise.png" toma X segundos en el computador donde se corregirá, su programa debe correr en menos de 10 + X segundos.
