### ISSUE TITLE
[Ayudantía 3]

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#173]
Hola! Pueden subir la ayudantía 3? Gracias!

**Comment by chocopiano** [comment]
Porfa

**Comment by caespinoza5** [comment]
¡Hola!
Acabamos de subir el video; está disponible en la carpeta Ayudantías. Rogamos paciencia con la subida de archivos.

¡Saludos!

**Comment by chocopiano** [comment]
Y es posible subir la solución con las preguntas como en las otras ayudantías jajajaja! gracias

**Comment by BlancaMunizaga** [comment]
van a subir el jupyter que se muestra en la ayudantía???

**Comment by kelseyfranken** [comment]
Es posible que suban el jupyter? 😺

**Comment by vichoeq** [comment]
Hola, ya esta subido. Disculpen la demora. Ojalá les sirva

Saludos!
