### ISSUE TITLE
Repositorio T2

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#174]
Hola! No puedo acceder al repo de la tarea. Agradecería que me lo habilitaran porfa, gracias!

**Comment by caespinoza5** [comment]
¡Hola!

El anuncio de ayer tenía un error; durante el día (de hoy, 21 de mayo) se estarán enviando las invitaciones a los repositorios. Mil disculpas. De aquí a las 22.00hrs-23.00hrs deberías tener acceso al repositorio.

¡Saludos!

**Comment by chocopiano** [comment]
Perfect! muchas gracias!
