### ISSUE TITLE
Commits en la documentación de análisis T02

### ISSUE THREAD

**Issue by Oisangui** [IIC2133-PUC/2020-1#175]
En el enunciado dice que "cada experimento deberá estar como un commit independiente". A qué se refiere esto? Significa que debo hacer un único commit por experimento? O separar en branches?

**Comment by vichoeq** [comment]
Hola, si revisas tu repositorio podrás ver que ya hay creados unos commits que deberás rellenar. En particular, tenemos un commit para cada categoría: la idea es que dentro de ese commit comentes con todos los resultados que obtengas de distintos experimentos dentro de esa categoría. 

Si sabes usar branches, lo recomiendo, pero no es necesario: puedes volver al commit anterior haciendo checkout y luego crear un nuevo commit sobre ese :)

**Comment by VicenteMerino** [comment]
@vichoeq Tengo la misma duda, no me queda claro lo de los commits, ya que en el repo me aparece solo uno con nombre "Agregado archivos bases", lo que si me aparece son 9 issues ¿supongo que a esto te refieres? Aun así sigo medio colgado con lo de los commits? Debo hacer un commit por experimento y si quiero cambiar de experimento debo revertir el commit?

**Comment by vichoeq** [comment]
@VicenteMerino Cuando subes codigo a git, estás creando un nuevo commit. Los commits tienen asociados un hash que actúa como su nombre.

Los issues que les pusimos son para que rellenen con sus experimentos, no estan asociados a ningun commit porque no tienen ninguno de sus experimentos.

Cuando hagas un experimento, vas a modificar tu código y lo vas a subir a git. El commit que se cree es el que está asociado con tu experimento, y es ese commit el que deberás referenciar en el análisis de tu experimento.

Cuando quieras probar otra cosa, puedes hacer `checkout` del codigo base, o revertir el commit. Desde el código base puedes crear un nuevo commit con un nuevo experimento, y analizarlo en la issue correspondiente. Lo importante es que cada experimento tenga un único commit asociado.

Recomiendo en todo caso usar una rama para cada categoría ya que combinar experimentos es llegar y hacer merge de las ramas.

## Qué pasa con tu git si haces revert para cada experimento

![commit revert](https://user-images.githubusercontent.com/5317897/82741048-5f325280-9d1c-11ea-9bb0-c1afebef1542.png)

## Qué pasa con tu git si haces checkout del código base para cada experimento

![commit checkout](https://user-images.githubusercontent.com/5317897/82741049-635e7000-9d1c-11ea-93d2-bf7e7d4466ef.png)

**Comment by fthurtado** [comment]
Hola, acabo de darme cuenta de esta issue, y yo realicé el proyecto sin fijarme en los commits que realicé. De hecho, puede que haya hecho commit de dos funciones implementadas al mismo tiempo (sin antes subir ninguna por si sola). Pero de igual forma tengo las referencias respectivas a cada issue.
Es un problema? Tengo que tener un commit por cada implementación que haga?
