### ISSUE TITLE
Error al compilar GTK en MacOS

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#176]
hola! Al instalar lo del título me aparece "Error: invalid option: --without-x11". Sin embargo si solo corro brew install gtk+3 gtk+ y despues  brew install libjpeg me aparece "fatal error: 'cairo.h' file not found". Alguna ayuda porfa!

**Comment by Kitaps** [comment]
Hola, eso es en un Mac?

**Comment by chocopiano** [comment]
Sí!

**Comment by vichoeq** [comment]
Espera, entonces el error es al instalar libgtk o libjpeg? Podrias copiar el comando que pusiste junto con todo el output? (Si no es muy grande claro)

**Comment by chocopiano** [comment]
brew install gtk+3 gtk+ --without-x --without-x11
output:  
<img width="1254" alt="Captura de Pantalla 2020-05-23 a la(s) 12 35 38" src="https://user-images.githubusercontent.com/37153534/82735768-241b2980-9cf2-11ea-92f6-4c839e95c897.png">

**Comment by chocopiano** [comment]
brew install libjpeg-----> ese sí me funciona

Ahora si corro solo brew install gtk+3 gtk+ me funciona pero al hacer make me aparece lo siguiente:
<img width="528" alt="Captura de Pantalla 2020-05-23 a la(s) 12 40 21" src="https://user-images.githubusercontent.com/37153534/82735829-9e4bae00-9cf2-11ea-85a9-8476675aee75.png">

**Comment by chocopiano** [comment]
Listo lo resolví!....use el siguiente comando "brew install pkg-config"

**Comment by miguelramirezv** [comment]
Hola! A mi también me funcionó ese comando, pero el comando:

brew install gtk+3 gtk+ --without-x --without-x11

Ese aún no me está funcionando. No sé si es necesario todavía eso sí. Me sale el mismo output que subieron

**Comment by chocopiano** [comment]
brew install gtk+3 gtk+
brew install libjpeg
brew install pkg-config

Eso hice yo y me funciono perfect!

**Comment by vichoeq** [comment]
Excelente, pkg-config viene por default en linux y no tenemos ayudantes con
Mac. Sorry

**Comment by inzuniga** [comment]
Hola, tuve un problema al instalar la librería en mac. Ejecuté los comandos que aparecían más arriba y al final de la descarga me apareció el siguiente error.
![Captura de pantalla 2020-06-08 a la(s) 21 27 31](https://user-images.githubusercontent.com/48324412/84098199-99664a00-a9d4-11ea-88a1-e45fb81cea42.png)

Creo que tiene que ver con la versión del mac y no me deja instalarlo. Gracias de antemano
