### ISSUE TITLE
Fecha I3 y Examen

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#177]
Hola quería confirmar que la I3 y el Examen se corren una semana según lo que estaban planificados?

**Comment by vichoeq** [comment]
Sip

**Comment by jotanavarrete** [comment]
Hola! ¿podrían confirmar la fecha del examen si es posible? En todos mis otros cursos la fecha del examen se corrió 6 días y no una semana exacta y, en cualquiera de los dos casos, al parecer tendría tope con examen de otro curso. Por ello me gustaría saber el día y hora del examen definitivo para comunicarlo a los profesores respectivos.

**Comment by JoseAvanzada2019** [comment]
Cuándo sería finalmente??

**Comment by VicenteMerino** [comment]
Próximo miércoles según tengo entendido

**Comment by vichoeq** [comment]
Si, miercoles 8. Eso se avisó en un correo hace algunas semanas, no ha cambiado nada.
