### ISSUE TITLE
Duda Xming Windows

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#179]
Hola, estaaba instalando todo lo que necesitaba para correr la tarea y funciona bien. Pero cuando pruebo el comando del readme para ver la animacion de como se resuelve el puzzle la ventana de xming apararece en naranjo como si se hubiera actualizado pero no se abre y si lo abro a mano no aparece nada. Que puede ser? 

PD: si corro los archivos python todo funciona bien.

Gracias!

**Comment by vichoeq** [comment]
Que curioso. Hiciste el `export DISPLAY=:0`?

**Comment by danustilovsky** [comment]
Hola, si lo hice. Se tiene que correr en bash antes de correr la tarea verdad?

**Comment by vichoeq** [comment]
Si, tienes que correrlo con Xming abierto y en la misma terminal en la que vas a correr tu tarea.

**Comment by ljrodriguez1** [comment]
Cuando corro el archivo la animación se hace muy rápido por lo que no alcanzo a verla, es eso normal?

**Comment by vichoeq** [comment]
@ljrodriguez1 No, el programa utiliza sleeps para regular la duracion de la animacion. Quizás esta fallando eso?

**Comment by ljrodriguez1** [comment]
si los sleep no estan funcionando, pero no se como arreglarlo y google no me ayuda

**Comment by danustilovsky** [comment]
@ljrodriguez1 Hola, Pudiste arreglarlo?

**Comment by ljrodriguez1** [comment]
Si, es un problema con ubuntu20, creo que se puede solucionar con ese sistema operativo pero no me funciono, me salio mas facil instalar ubuntu18

**Comment by danustilovsky** [comment]
Hola, por si alguien en windows no le funciona, este comando lo arreglo para mi.
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
