### ISSUE TITLE
Error make en ubuntu

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2133-PUC/2020-1#18]
Hola, acabo de instalar ubuntu con una maquina virtual, pero al hacer make en la carpeta de la tarea o en la carpeta del taller, me sale este error:

/bin/sh: 1: gcc: not found
Makefile:110: recipe for target 'obj/simulate/main.o' failed
make: *** [obj/simulate/main.o] Error 127

**Comment by JohnTrombon** [comment]
Hola. Lo más probable es que directamente no venga gcc (compilador de C ) instalado por defecto en la máquina virtual.
Intenta corriendo 
`sudo apt install gcc` en el terminal e intentándolo de nuevo.

**Comment by nrrosenberg** [comment]
Buena gracias! ahi funcionó
