### ISSUE TITLE
[Tiempo de ejecución en experimentos]

### ISSUE THREAD

**Issue by fediaz3** [IIC2133-PUC/2020-1#180]
Hola!
Tengo una duda de enunciado
Cuando nos dicen que: si el algoritmo demora más de 10 segundos en un test, será cortado y tendré 0 puntos en ese test.
¿se refiere solamente al último algoritmo que contiene mis 3 mejoras a la tabla de hash?

Por ejemplo, si hago un experimento que realiza una mejora en la tabla de hash en la categoría D y logro mejorar la eficiencia de 30 hasta el test 70, pero aún me falta completar los tests hasta el 127  ¿esto no contaría como 0 puntos? ¿sería solo un experimento para llegar al último algoritmo?

Pregunta bonus: ¿ Es normal que se demoren mucho los gráficos generados en python, cuando tengo mas tests resueltos?  

Gracias

**Comment by vichoeq** [comment]
> ¿se refiere solamente al último algoritmo que contiene mis 3 mejoras a la tabla de hash?

Lo que subas a tu repo puede contener todas las mejoras que quieras, no está limitado a 3.

Lo que está limitado a 3 mejoras es el análisis, para hacerlo más manejable (sino son muchas combinaciones)

> Por ejemplo, si hago un experimento que realiza una mejora en la tabla de hash en la categoría D y logro mejorar la eficiencia de 30 hasta el test 70, pero aún me falta completar los tests hasta el 127 ¿esto no contaría como 0 puntos?

No, solo los tests que no lograste completar tienen 0 puntos. En este caso tendrías el puntaje completo por los 70 que lograste completar, y 0 puntos en los que no.

La corrección se hará con 12 tests de las mismas características que los que subimos. Sólo considera que ninguno de esos 12 tests podrá ser resuelto a tiempo por el código base, es decir necesitas como mínimo una mejora para poder resolver los tests de corrección.

> ¿sería solo un experimento para llegar al último algoritmo?

Hay categorías que tienen más efecto sobre el rendimiento de la tabla, así que si es posible que tu ultimo algoritmo consista de una sola mejora :) 

> Pregunta bonus: ¿ Es normal que se demoren mucho los gráficos generados en python, cuando tengo mas tests resueltos?

Si, porque son más datos para la regresión y los demás graficos.

**Comment by mimunoz11** [comment]
Hola! Al menos a mi me sigue quedando la duda de si ¿el análisis de los experimentos va separado a la evaluación del código? Por ejemplo, ¿el código final en la master debiera tener los 12/12 test buenos mientras que los experimentos podrían tener mejoras respecto al código base pero sin necesariamente tener los 12/12 test correctos?
gracias.

**Comment by yerkko** [comment]
> Hola! Al menos a mi me sigue quedando la duda de si ¿el análisis de los experimentos va separado a la evaluación del código? Por ejemplo, ¿el código final en la master debiera tener los 12/12 test buenos mientras que los experimentos podrían tener mejoras respecto al código base pero sin necesariamente tener los 12/12 test correctos?
> gracias.

El código que se somete a la evaluación del tiempo es lo último que tengas en la rama master a la fecha de entrega. Los experimentos son para mostrar cómo llegaste a tal implementación. No es necesario que cumplan todos los tests.

**Comment by fediaz3** [comment]
Perdón, solo para ver si entendí:

1.  Tenemos que hacer varios experimentos por categoría ( no hay limite) y encontrar una combinación de experimentos que me resuelvan los 127 de 127 test de prueba para estar seguro que va resultar con los 12 de 12. Esta mejor combinación debe quedar en la rama master.

2.  Para el análisis tengo que elegir: 3 experimentos individuales (de los tantos que pude haber hecho) y a partir de esos tres, generar 2 experimentos 'dobles' y 1 experimento 'triple'. En estos, no es necesario que tenga bueno los 127 de 127 test ( o 12 de 12 cuando lo prueben ustedes), solo sirve para el informe.

**Comment by vichoeq** [comment]
@fediaz3 efectivamente :+1:

**Comment by miguelramirezv** [comment]
Hola! Tengo una duda aún sobre esto. Cuando el programa dice que no logró resolver un test y por ejemplo que fue "derrotado" por el test 82, significa una de las siguientes opciones:
1) No logró llegar a la respuesta
2) Que demoró más de 10 segundos en resolver el test entonces se corta

¿Estoy en lo correcto? Porque o si no debiera tomar el tiempo que demoran los últimos test si es que se resuelven

**Comment by vichoeq** [comment]
@miguelramirezv es solo que se demoró mas de 10 segundos. `run_homework.py` no considera la correctitud de tu algoritmo, aunque si se cae te lo va a informar.
