### ISSUE TITLE
Duda zobrist

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#181]
Hola, una pregunta,

si quiero hacer un hash mediante zobrist, la matriz de numero aleatorios debe permanecer constante para todos los posibles estado o se va generando nuevamente para cada estado?

**Comment by vichoeq** [comment]
Debe ser constante para todos los estados, recuerda que para dos estados iguales debes poder obtener exactamente el mismo hash.

**Comment by fabarros** [comment]
Hola! 
Respecto a esa pregunta, dado que no tenemos exactamente un tablero con piezas, en el enunciado se sugiere implementar un método incremental para calcular el hash de un estado usando el hash del estado anterior y la operación que produjo el nuevo estado. Sin embargo en los contenidos del curso no vimos algo así como un hash incremental, entonces mi duda es 
1) podemos implementarlo como se nos dé la gana y según nuestra creatividad lo permita?
2) cómo me aseguro que siga distribuyendo uniforme?
Es que no veo la forma de implementar ZobristHashing en el problema.
Gracias! Saludos.

**Comment by vichoeq** [comment]
Hola @fabarros,
 
> Respecto a esa pregunta, dado que no tenemos exactamente un tablero con piezas

¿Qué son las piezas en un tablero más que números dentro de los posibles valores que puede tomar una celda? Recuerda que en la clase hicimos la conversión de piezas a números, del 0 al 3 (+ las celdas vacías, que no incluiamos en el hash)

En este caso ya tienes los números, por lo que es llegar y aplicar zobrist: las celdas pueden tener números del 0 al total de celdas -1.

>  en el enunciado se sugiere implementar un método incremental para calcular el hash de un estado usando el hash del estado anterior y la operación que produjo el nuevo estado.

Zobrist tiene la popularidad que tiene ya que te permite calcularlo de manera incremental en O(cantidad de celdas que fueron modificadas). Recuerda que el operador XOR es su propio inverso, por lo que puedes "sacar" del hash del estado anterior los valores de la fila/columna que modificaste y agregar los valores del nuevo estado: ya que las demás filas/columnas no cambian el aporte que hacen al XOR de esos los números tampoco cambia.

> podemos implementarlo como se nos dé la gana y según nuestra creatividad lo permita?

Si, absolutamente. Go wild, experimenta, de eso se trata la tarea. Para la parte de análisis lo que importa es que el análisis esté bien hecho, ya sea el por qué esperarías que algo sea bueno, como si lo fue realmente y por qué.

> cómo me aseguro que siga distribuyendo uniforme?

Si estamos hablando de zobrist, al hacerlo de manera incremental el valor de hash debería ser exactamente el mismo que si lo calculas completo, solo que lo haces más rápido ya que partes de otro valor como referencia. Asique mientras mantengas eso, (y asumiendo que tu zobrist normal estaba bien hecho por lo que distribuía uniforme), entonces tu zobrist incremental va a distribuir uniforme.

Cualquier duda me dices.
Saludos!

**Comment by vichoeq** [comment]
Como bonus a como funciona un hash incremental, imaginate que un hash fuera la suma de los números de una matriz. Si yo te digo que la celda X, Y y Z cambiaron de valor, tu puedes calcular el nuevo hash en 2*3 = 6 pasos: restas los 3 valores que habia inicialmente en esas celdas, y sumas los nuevos 3 valores. La diferencia con zobrist es que la suma no distribuye uniforme, mientras que el XOR si. La resta es la inversa de la suma, y el XOR es el inverso del XOR. 

¿Se entiende?

**Comment by fabarros** [comment]
Simplemente maravilloso, gracias, te pasaste.

**Comment by vchadwick** [comment]
Hola! El valor de hash que obtuve al aplicar Zobrist es un número de 64 bit, ahora bien cuando quiero ajustar ese valor al tamaño de la tabla, estoy realizando la siguiente operación: hash%table_size (venia por defecto), en donde table_size es un INT. 
El problema está que no me entrega un número entre [0,table_size - 1] como debería ser. No entiendo como funciona la división entre un número de 64 bit y un INT.

**Comment by VicenteMerino** [comment]
@vchadwick en mi opinión probablemente tengas algo mal implementado, quizás en como estás obteniendo el valor del hash, ya que hash%table_size si o si debería entregarte un valor entre 0 y table_size - 1, independiente del tipo de dato. Al final la division entre 64 bit y 4 bit (int), debería arrojarte el mayor: 64 bit (igual depende como guardes la variable resultante de dicha operacion, ojo con eso).

**Comment by vchadwick** [comment]
@VicenteMerino tienes toda la razón! Tenia un error de implementación.
Muchas gracias

**Comment by ljrodriguez1** [comment]
Hola Para lograr implementar este metodo incremental siento que debo pasarle el Nodo que contiene la operacion para llegar a ese estado y operacion padre al state_hash() para asi poder acceder a ellos y calcular el valor de forma incremental.

**Comment by VicenteMerino** [comment]
a mi me pasa algo parecido que a @ljrodriguez1 , pero no se puede editar los otros códigos por lo que no se podría cambiar como se llama la función :(

**Comment by ljrodriguez1** [comment]
Leyendo el código un poco mas si existe un lugar donde tengo al padre y calculo el hash, te diria donde pero quizas lo consideran copia :(.

**Comment by tpcantergiani** [comment]
Hola!
Para aplicar Zobrist, no entiendo como se acotan las celdas:
Los valores de las celdas van entre 0 y 255 (ya que es un byte)? 
O se acota por otro valor, como se comenta mas arriba:

> En este caso ya tienes los números, por lo que es llegar y aplicar zobrist: las celdas pueden tener números del 0 al total de celdas -1.

**Comment by vichoeq** [comment]
La funcion de insertar en la tabla recibe el padre y la operacion precisamente para que puedan calcular el hash de manera incremental.

Recuerda que como el padre es un nodo, tiene guardado su hash :+1: 

En state.h estan las funciones "is row" y "get index" que te indican la fila / columna sobre la que opera una operacion para poder hacer el hash incremental.

**Comment by tpcantergiani** [comment]
Hola,
Ayer aplique zobrist incremental y me funcionaba muy bien, realizando casi todos los tests.
Lo corrí, pero no tenia memoria, por lo que no se me guardaron los grafos (y borre la carpeta).
Hoy lo corrí de nuevo, y aumento el tiempo en que corre cada test, y cada vez que lo corro, aumenta mas el tiempo. 
Al terminar el programa libero toda la memoria, por lo que no se por que pasara.

**Comment by tpcantergiani** [comment]
Si creo dos experimentos, uno con zobrist no incremental y otro zobrist incremental, debería contar el segundo como un experimento mixto como uno de complejidad del Hash?

**Comment by niguzman** [comment]
> La funcion de insertar en la tabla recibe el padre y la operacion precisamente para que puedan calcular el hash de manera incremental.

@vichoeq cuál es esa función de insertar en la tabla?
