### ISSUE TITLE
Complejidad función de Hash

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#182]
Hola no entiendo como se puede realizar un experimento sobre la complejidad de la función de Hash del código base, siendo que esta ya toma tiempo O(1) en calcularse, por lo cual no se que tan factible sea hacer este experimento por si solo. Tal vez se podría experimentar con la comlejidad, una vez que se cambia la función de hash (experimentar con la distribución)

**Comment by yerkko** [comment]
Recuerda que debes usar métricas como colisiones y tiempo. Lo importante es optimizar estos valores, no necesariamente el criterio del experimentos

**Comment by vichoeq** [comment]
Lo importante de tus experimentos es que evalues como varía el desempeño de tu programa al variar una variable. En este caso, ¿el programa se demora más al usar un hash de mayor complejidad? ¿Se demora menos? ¿Es lo que uno esperaría? ¿Por qué?
