### ISSUE TITLE
Cantidad de experimentos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#183]
Hola, algo que no me queda muy claro es la cantidad de experimentos que debo realizar. Por ejemplo para las categorías individuales, debo realizar 3 experimentos distintos para cada una o 3 en total? Que mi duda surge, ya que en la issue de ejemplo aparece dos veces comentado como si se hicieran dos experimentos para esa categoría, por lo que yo hice lo mismo: para una misma categoría hice 3 experimentos (pensando siempre en la categoría individual, en mi caso 3 experimentos para la complejidad del hash).

**Comment by vichoeq** [comment]
Debes hacer al menos un experimento para cada categoría distinta. El ejemplo que hicimos eran 2 experimentos de una misma categoria, por eso iban comentados en un mismo issue.

Sorry por la confusión que esto haya podido causar.

**Comment by chocopiano** [comment]
Hola! pero el enunciado da a entender que no necesariamente es un experimento por categoría. De hecho para los 3 individuales hay que escoger 3 categorías, para los dos dobles hay que escoger 2 combinaciones de los primeros 3 experimentos. Y para el triple, los 3 experimentos juntos.
