### ISSUE TITLE
Categorías constante / variable

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#184]
Hola, el enunciado dice: 

> Es importante recalcar que en cada experimento puedes modificar la categorı́a a estudiar, pero el resto deben quedar constantes.

Pero me queda la duda con lo siguiente: Por ejemplo si quiero implementar una función de hash que distribuya uniforme, por ejemplo: zobrist, según lo vimos en clase, esto además de cambiar la distribución de la función de hash, aumenta la complejidad (ya que segun la implementación de clases, debe revisar todo el tablero y la del caso base es O(1)), por lo que no se si sea correcto implementar esta función de hash en la categoría individual: Distribución de la función, o más bien este experimento debería ir a parar a la combinación A+B.

**Comment by VicenteMerino** [comment]
Mismo caso por ejemplo para el método de ajuste, lo cambié y me sigue dando los mismos resultados, debido a que la función de hash me retorna siempre 0 (y por lo tanto el método de ajuste, tanto original como cambiado van a parar al 0), por lo que no entiendo como puede el efecto singular del método de ajuste por si solo afectar a ĺa tabla de hash ¿o es precisamente este efecto nulo lo que debería incluir en el análisis?

**Comment by vichoeq** [comment]
En el primer caso que describes puedes implementar zobrist y en (A) estudiar como distribuye y en (B) estudiar como afecta su complejidad.

**Comment by yerkko** [comment]
Hello, con respecto a 

> ¿o es precisamente este efecto nulo lo que debería incluir en el análisis?

El decir "no se aprecia un efecto dada las condiciones iniciales" es una conclusión válida. Sin embargo, con el fin de que tu análisis sea más útil, como recomendación intenta hacer aquellos experimentos que te brinden un mayor insight del problema.

**Comment by VicenteMerino** [comment]
@vichoeq Entonces, puedo obviar un poco eso de que "las otras categorías deben permanecer constantes", va más dirigido a la mirada del análisis lo de dejar las categorías constantes, verdad?

Y si hiciera lo que tu me dices entonces daría lo mismo que use el mismo commit? Ya que sería la misma implementación de zobrist para analizar el experimento en A y en B y no tendría sentido separarlo en commits distintos.

**Comment by vichoeq** [comment]
Exacto. Es mas que nada para ayudarlos a enfocar su análisis ya que sino son demasiadas variables y estudiar como interactúan entre ellas es mucho más trabajo del que nos interesa que hagan :smile:

**Comment by niguzman** [comment]
> En el primer caso que describes puedes implementar zobrist y en (A) estudiar como distribuye y en (B) estudiar como afecta su complejidad.

@vichoeq Me queda una duda sobre esto, como en el correo que mandaron recomendaban mejorar la función de hash y dejar eso constante. Si hago zobrist para el experimento A, zobrist incremental para el experimento B y luego quiero hacer otro experimento, puedo dejar zobrist incremental al momento de experimentar con Ajuste, Probing o Rehasging?

**Comment by yerkko** [comment]
Puedes dejar Zobrist 1.0 como constante para el resto de los experimentos, incremental implica complejidad por lo que tendrás que incluirlo como variable en un experimento de 2 categorías

**Comment by jmsilvas** [comment]
Hola! Tengo una duda relacionada a esto, si el experimento A es zobrist y el B zobrist incremental, el experimento A+B sería el mismo que el B de manera individual (ambos sería un zobrist incremental). Es posible hacer esta combinación siendo que se tendría un experimento menos?
