### ISSUE TITLE
KS Test hash

### ISSUE THREAD

**Issue by mora4** [IIC2133-PUC/2020-1#185]
Hola, 

Estoy tratando de usar el metodo test_hash de la clase HashTester para ver si mi funcion de hash distribuye parecido a una uniforme, pero no entiendo muy bien como interpretar los resultados ni que parametro usar como max_range. 
¿Para max_range estoy usando la diferencia entre el hash mas grande y el mas chico, esta bien? 
¿Si la hipotesis nula es rechazada significa que mis hash sí distribuyen similar a una uniforme?

Gracias!

**Comment by yerkko** [comment]
Max range indica cuál es el máximo valor que puede obtener tu función de hash. En este sentido, se utiliza para normalizar el recorrido al intervalo [0,1]. El código base hace el supuesto que el recorrido parte en 0 y se extiende por R+. Si tu función no parte en 0, tienes que usar una normalización como min-max para obtener el resultado correcto.

Con respecto al test KS: Como se explica en el enunciado, el uso de las funciones estadísticas es optativo y son sólo para aquellos que dominen los conocimientos en el área y quieran elevar su análisis. De todas formas, te recomiendo leer esta [página](https://www.itl.nist.gov/div898/handbook/eda/section3/eda35g.htm
)
```
H0: | The data follow a specified distribution
-- | --
Ha: | The data do not follow the specified distribution
```
