### ISSUE TITLE
Falla "killed" en algunos tests

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#186]
Hola!

Hice una mejora relacionada al "probing" (no puedo dar más detalles o estaría soplando) y en algunos de los tests el terminal me entrega un output "killed". Es extraño porque me pasó por ejemplo en el 061.txt, pero para el 065.txt me entregó el output correcto y muy rápido. ¿Estoy haciendo algo mal o es un problema del computador?

Saludos

Update: revisé con valgrind algún test que no diera "killed" y no me entrega errores de memoria, por lo que no sé a qué se debe el "killed", no he podido probar los tests grandes de la tarea.

**Comment by vichoeq** [comment]
Pero y qué dice valgrind de los tests que sí dan killed?

**Comment by matumartinez** [comment]
"killed", no me entrega ninguna información

**Comment by vichoeq** [comment]
Ok, por lo que estoy leyendo, el sistema operativo va a matar a tu programa si este empieza a usar DEMASIADA memoria.

Que dice valgrind sobre la memoria solicitada de tu programa?

**Comment by matumartinez** [comment]
Para la mejora que hice no usé ningún struct nuevo o puntero (o cualquier cosa que requiera usar un malloc()), valgrind no me arroja ningún error con respecto al uso de memoria.

**Comment by vichoeq** [comment]
Cuanta memoria estás solicitando?

**Comment by matumartinez** [comment]
Ni idea que tanta memoria solicitaba el código base, pero probé usar otro computador (donde podía asignar más de los solo 2GB de RAM que tenía en la máquina virtual con mi computador) y dejé de tener estos problemas.
