### ISSUE TITLE
Histogramas de colisiones

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#187]
Hola, me gustaría entender que quiere decir los histogramas de colisiones: creo entender que aquellos que dicen no probing, son los histogramas resultantes de no haber sondeo, y los que dicen probing los histogramas producto del sondeo. Pero lo que no entiendo es qué quiere decir el numero del histograma?

**Comment by vichoeq** [comment]
Los histogramas de colisiones indican, para cada celda de la tabla de hash, cuantos elementos intentaron insertarse en esa celda y no pudieron porque ya habia algo.

El histograma sin probing toma en consideracion solo el primer intento de un elemento, mientras que el con probing toma en cuenta todos las demas celdas en las que se intenta insertar hasta que lo logra.

El script genera un histograma por cada tamaño de tu tabla, por si hay problemas que sean evidentes en un tamaño y no otro.

Cualquier duda me preguntas!
