### ISSUE TITLE
LaTeX en Github

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#188]
Hola, hay alguna forma de poner fórmulas matemáticas en Github? He buscado bastante al respecto y al parecer Github no soporta las fórmulas matemáticas (pese a que soporta Markdown y ahí si se puede escribir). En fin, si alguien sabe de alguna forma, agradecería que me lo dijera.

**Comment by cacosandon** [comment]
Hola!

Yo al menos no conozco ninguna! Pero si [https://www.codecogs.com/latex/eqneditor.php](está esta página) que puedes escribir ecuaciones en LaTeX y exportarlas como foto.
