### ISSUE TITLE
Metodo de la multiplicacion

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#189]
Hola, en el metodo de la multiplicacion visto en clases:

![image](https://user-images.githubusercontent.com/47841749/83157972-33bfb700-a0d2-11ea-8def-453008cfb585.png)

Me queda la duda a que es lo que se le hace módulo? Al h(X) o al A*h(X), me queda esta duda, ya que A*h(X), por definición es un número decimal y el operador módulo tengo entendido que no está definido para estos números.

**Comment by cacosandon** [comment]
Hola!

Tengo entendido que no necesariamente 

![image](https://user-images.githubusercontent.com/30879716/83162461-cadb3d80-a0d7-11ea-90a3-1d56700bc68b.png) 

es un número decimal, por lo que al hacer `mod 1` estas obteniendo la parte decimal. También lo puedes ver así

![image](https://user-images.githubusercontent.com/30879716/83162644-fe1dcc80-a0d7-11ea-9988-0ab51bf4839f.png)

**Comment by vichoeq** [comment]
Exacto. La definición de módulo es "el resto de la división". Para cualquier numero, el mod 1 va a ser la parte decimal del número.

**Comment by VicenteMerino** [comment]
@cacosandon @vichoeq dado que los números que trabajamos son muy grandes (64 bits) es válido usar los últimos dos dígitos del valor que me entregue la función de hash para calcular la parte decimal. La verdad por inspección creo que si se puede, pero no se si hay una regla general, p.ej decimal_part(123456)=decimal_part(56)=0.28

**Comment by vichoeq** [comment]
Puedes usar "long double" para guardar el resultado de la multiplicación de A * h(x). Sino, debería servir elegir un A entre 0 y 1, como 1/phi.

C se pone raro con estas operaciones asique avisame si tienes cualquier problema.

**Comment by vichoeq** [comment]
De hecho, el long double debería ser la unica forma de resolverlo ya que los double funcionan de manera de que mientras más grande es la parte entera, menos información se puede guardar de la parte decimal. Si intentas guardar el resultado de la multiplicación en un double, te va a quedar una parte decimal = 0

**Comment by VicenteMerino** [comment]
Si, un poco por eso era mi duda, que no sabía si al hacer la multiplicación se iba a poder guardar todo el dato, al final hice lo de tomar las cifras "significativas" de mi h y eso multiplicarlo, y al parecer es equivalente a tomar todo el dato y por lo visto me resultó.

**Comment by vichoeq** [comment]
Osea, va a funcionar, pero estás perdiendo un poco de información. Si haces eso vas a tener que explicar bajo que reglas escoges estas "cifras significativas" y pq puedes descartar las demás.

**Comment by vchadwick** [comment]
Hola @vichoeq en cuanto a tu respuesta anterior ¿como podríamos obtener Ah mod 1 sin perder información? Tengo almacenado Ah como long double, ahora bien, cuando intento obtener su parte decimal estaba probando con múltiples funciones (dentro de ellas modfl). Pero no he obtenido resultados convincentes (me quedan los resultados redondeados) ¿Qué recomendarías tú en este caso?
Saludos
