### ISSUE TITLE
Inconsistencias entre ejecución con python y ejecución con C

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#190]
Hola!

Probé una mejora al código, ejecuté el run_homework.py y el test 067.txt me derrotó la ejecución. Sin embargo, probando individualmente puedo ejecutar en menos de 10 segundos hasta el test 080.txt aproximadamente. ¿Cómo se van a probar nuestras tareas, con la ejecución de corrido o test a test?

Saludos

**Comment by vichoeq** [comment]
El tiempo que se imprime en consola es el tiempo que se demora el solver, sin incluir la creacion ni destruccion de la tabla. El tiempo al ejecutarlo de corrido es el tiempo total del programa.

La tarea se evaluará con la ejecución de corrido, la cual no deberia diferir de la ejecucion test a test por mas de 1 segundo (siendo generoso)

**Comment by vichoeq** [comment]
Osea, se evaluara test a test, pero utilizando el mismo sistema de ejecucion que utiliza el script de python.

**Comment by chocopiano** [comment]
Me pasa lo mismo. Se me derrota en el test 122 pero individualmente ningun test se me demora más de 5s. Debo corregirlo igual para que python no me lo derrote o estoy bien? Gracias!

**Comment by matumartinez** [comment]
chocopiano apaga tu máquina virtual (o computador), vuelve a encenderla y prueba el run_homework.py antes de hacer cualquier otra cosa, ahí en una de esas te pasa los 127 tests.

**Comment by chocopiano** [comment]
ahí me funciono! gracias por el consejo!
