### ISSUE TITLE
Modificación de parámetros

### ISSUE THREAD

**Issue by jaromero6** [IIC2133-PUC/2020-1#194]
Hola
Tenía una duda respecto a si solo podemos modificar para la tarea la versión final los aspectos que se dan en el enunciado (función hash, método de ajuste, funcion de probing, etc) o podemos modificar otros parámetros o funciones del programa?

En otras palabras, hacer cada experimento modificando solo el atributo que se corresponde con el experimento. Luego la versión final del código se implementan las modificaciones que ya fueron validadas previamente y se añaden otras adicionales que no estaban involucradas en los experimentos. De ser posible hacer estas modificaciones adicionales, deben estar necesariamente involucradas con la tabla hash, o bien puede ser una modificación de otro aspecto nada que ver con la tabla hash? Obiviamente al hacerlo, estaría asumiendo que si rompo la funcionalidad del código tendría la penalización correspondiente

**Comment by vichoeq** [comment]
Para los experimentos, lo ideal es mantener aisladas las variables asi puedes hacer mejor el analisis.

Para la versión final (el código que se va a corregir), metele todo lo que quieras para que sea lo más eficiente posible.

**Comment by vichoeq** [comment]
Como dice en el enunciado, solo tienes permiso para modificar los archivos dentro de la carpeta `src/graph` (donde esta la tabla de hash).

Asique si modificas otra cosa no se va a ver porque para lo demás usaremos el codigo original.

En el enunciado dice que si tu programa no da exactamente la misma solución que el código base, entonces se considerará como que rompiste la funcionalidad y se te asignarán 0 puntos a ese test.

**Comment by jaromero6** [comment]
ok, muchas gracias
