### ISSUE TITLE
Problema al correr run_homework.py

### ISSUE THREAD

**Issue by niguzman** [IIC2133-PUC/2020-1#195]
Hola,
si corro "python run_homework.py" directo desde cmd me tira el sgte error
![image](https://user-images.githubusercontent.com/48304981/83478835-e2fae600-a464-11ea-835f-816409011274.png)

Estuve viendo y debe ser por ":" en la hora. Si cambio esto por ".", me deja de tirar ese error pero me tira el sgte:
![image](https://user-images.githubusercontent.com/48304981/83478880-fc9c2d80-a464-11ea-95d5-591cc0993bf4.png)

Por otro lado, si primero inicio bash y corro "python run_homework.py", me tira el sgte error:
![image](https://user-images.githubusercontent.com/48304981/83478947-28b7ae80-a465-11ea-824e-612688317431.png)
y eso que ya corrí "pip install progress"

así que no sé como solucionar esto :C

**Comment by caespinoza5** [comment]
¡Hola!

Intenta correr "pip3 install progress" en vez de "pip install progress" y ve si te funciona. "pip" en ciertos computadores instala para python (2) y no python3, por lo que con pip3 te debería funcionar.

**Comment by niguzman** [comment]
También me da error :C
![image](https://user-images.githubusercontent.com/48304981/83532001-ad351c00-a4bb-11ea-96e9-a77365df362e.png)

**Comment by caespinoza5** [comment]
¡Intenta instalarlo con el comando que te a parece ahí! `sudo apt install python3-pip` y luego intenta denuevo con pip3.

**Comment by niguzman** [comment]
Ahí si me sirvio!
Gracias!!
