### ISSUE TITLE
Como se evaluarán los commits?

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#196]
Bueno, tengo bastante desordenados los commits, hay muchos (e incluso algunas branchs) que son simplemente de prueba y están muy desordenadas, no se si deba reiniciar todo e ir de a poco haciendo los commits, esta vez bien, o basta que en realidad cumpla 1 commit 1 experimento, y no debería haber problema?

**Comment by vichoeq** [comment]
Lo que se va a evaluar son los issues, los commits son para respaldar que efectivamente hiciste lo que dices haber hecho.
