### ISSUE TITLE
Clase dijkstra

### ISSUE THREAD

**Issue by rodobkn** [IIC2133-PUC/2020-1#197]
Hola!

Quisiera saber cuando subirán el video de la clase de dijkstra? Fue la clase del miercoles 3 de Junio.

Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Ya está subida en el README; la puedes encontrar [aquí](https://youtu.be/N7eDsmZIJxI). Disculpa la demora; habíamos tenido un pequeño problema técnico.

¡Éxito con el estudio! 😃
