### ISSUE TITLE
invitacion repositorio tarea 2

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2133-PUC/2020-1#199]
Holaa! hoy quise aceptar la invitación para el repositorio de la tarea, pero me salia que ya no estaba disponible. Habra alguna posibilidad de que se pueda generar una nueva?

**Comment by caespinoza5** [comment]
¡Hola!

Acabo de reenviarte la invitación. Debieras tener acceso en https://github.com/IIC2133-PUC/T2-2020-1-nrrosenberg .

¡Saludos!
