### ISSUE TITLE
Duda código hellofile

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2133-PUC/2020-1#2]
Hola, tengo una duda con dos variables de este código 
![image](https://user-images.githubusercontent.com/39094323/76924247-856aea80-68b4-11ea-8c92-4016491e1bda.png)

No entiendo qué es argv, además de ser un array, y en qué momento se definen los valores de argc y argv.
Saludos!

**Comment by vichoeq** [comment]
Hola,

No tuvimos mucho tiempo para explicar eso en el taller de C, pero no es muy complicado.

El arreglo `argv` es un arreglo de strings que se inicializa al iniciar el programa. `argc` indica la cantidad de elementos que tiene. ¿Qué elementos tiene? Son los parametros del programa.

Si llamas tu programa diciendo 

```bash
./programa hola 1 mundo 2
```

entonces el contenido de `argv` es el siguiente:

```c
{
   "programa",
   "hola",
   "1",
   "mundo",
   "2"
}
```

y por lo tanto `argc` sería 5.

Para hacer el simil con python: `argv` es exactamente lo mismo que `sys.argv`, y `argc` sería `len(sys.argv)`

Espero que eso responda tu duda 👍
