### ISSUE TITLE
Tarea 0 Error con make (make: *** [simulate] Error 1)

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#20]
Hola! Cuando corro el comando make me aparece el siguiente error en la terminal:

...
duplicate symbol _titanic_clausura in:
    obj/simulate/main.o
    obj/simulate/fila.o
ld: 19 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [simulate] Error 1

Mi estructura se encuentra en fila.c y fila.h, entiendo que habla de duplicados pero no sé bien a qué se refiere, porque no tengo código duplicado. En algunas funciones definidas uso la misma variable, por ejemplo int i, pero solo una vez por función. Y las últimas dos filas no entiendo a qué se refiere, cuál puede ser el error?

Ademas sí tengo instalado gcc y make.

Gracias!

**Comment by arbiocanpion** [comment]
Hola @miguelramirezv 
¿Podrías mostrarme como estas exportando tus archivos en tu main?.

**Comment by miguelramirezv** [comment]
Hola sí:

#include "fila.c"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>


Y en el archivo fila.c tengo:

#include "fila.h"
#include <stdlib.h>
#include <stdio.h>


También probé con valgrind pero no me dice más información sobre los errores.

**Comment by arbiocanpion** [comment]
En el archivo main.c cambia 
``` c
#include "fila.c"
```

Por 
``` c
#include "fila.h"
```

**Comment by arbiocanpion** [comment]
¿Te estas preguntando por que pasa esto?
En la issue #4 @B-Dominguez  explico en profundidad la lógica y porque cuales son las principales diferencias entre los dos archivos y porque hay que importar el .h.

**Comment by miguelramirezv** [comment]
Eso era! Muchísimas gracias! Voy a revisar esa issue, te pasaste!!!!
