### ISSUE TITLE
Repositorio T2

### ISSUE THREAD

**Issue by fjcroquevielle** [IIC2133-PUC/2020-1#200]
Hola,
No he podido encontrar mi repositorio de la tarea 2. Lo he buscado con el formato que enviaron pero me lleva siempre a la misma pagina (donde indica que no se ha encontrado). Saben que puedo hacer?
Gracias

**Comment by caespinoza5** [comment]
¡Hola!

Acabo de reenviarte una invitación; las invitaciones duran 7 días desde que se crea el repositorio (que coincide cuando se sube el enunciado o un poco después), por lo que es importante que accedas a él tan pronto posible.

¡Saludos!
