### ISSUE TITLE
Variable con tamaño de state

### ISSUE THREAD

**Issue by atroncoso2** [IIC2133-PUC/2020-1#201]
Hola, 
Estoy intentando hacer una buena función de hash y me doy cuenta que para hacerlo necesito saber el tamaño del arreglo _state_. He buscado bastante en el código y no encuentro ninguna variable adonde podría estar almacenado. Pienso que saber esto es fundamental para crear una buena función de hash (incluir toda la información de state) y me tiento a modificar archivos afuera de _graph_, lo cuál según el enunciado no se puede. 
Hay algún lugar adonde estén guardados los valores de la altura y ancho de state que no haya visto? Y si no, podría modificar archivos afuera de _graph_ solamente para poder usar estos valores?

**Comment by VicenteMerino** [comment]
Si están en el código, creo que como variables globales, no se si te pueda decir ya que quizás es "copia" pero yo que tu busco más.

**Comment by atroncoso2** [comment]
Ya los ví @VicenteMerino muchas gracias! Me faltaba mirar con un poco más de detalle solamente.
