### ISSUE TITLE
Duda Tarea 2 "probing"

### ISSUE THREAD

**Issue by rodobkn** [IIC2133-PUC/2020-1#202]
El siguiente path:

results/timestamp/graphs/histograms/n/*.html

"Contiene gráficos para los histogramas de colisiones para cada tamaño de la tabla. Uno de los gráficos son las colisiones producidas al avanzar con la función de probing, y el otro las colisiones producidas al encontrarte que en la celda que te corresponde por función de hash ya hay algo guardado"

Eso sale en el readme del repositorio de la tarea 2. MI duda es, cual es la diferencia entre las colisiones producidas al avanzar con la funciòn de probing y el otro tipo de colisiòn mencionado.

EN clases al parecer solamente vimos el tipo de colisión cuando la función de hash arroja un índice donde algo ya estaba guardado, sin embargo eso del "probing" no tengo idea que es.

SI me lo pudieran explicar estarìa agradecido.

**Comment by VicenteMerino** [comment]
No se si te sirve, pero me habian contestado esto #187

**Comment by yerkko** [comment]
Uno contiene solo las colisiones de la función de hash, sin contar las colisiones extras generadas por la función de probing cuando avanzas a la celda contigua. El otro si las considera
