### ISSUE TITLE
Experimentos por categoría

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#203]
Hola! Tengo la siguiente duda: En el enunciado se da a entender que no necesariamente es un experimento por categoría. De hecho para los 3 individuales hay que escoger 3 categorías, para los dos dobles hay que escoger 2 combinaciones de los primeros 3 experimentos. Y para el triple, los 3 experimentos juntos. Sin embargo, en un comentario de una issue se menciona que como mínimo debe se run experimento por categoría. Gracias!

**Comment by vichoeq** [comment]
Hola, tal como dices no necesariamente hay que hacer un experimento por categoría.

Me puedes indicar el comentario en el que se da a entender que si para revisarlo?

**Comment by chocopiano** [comment]
Quizas entendí mal lo que salía [acá](https://github.com/IIC2133-PUC/2020-1/issues/183)   Muchas gracias

**Comment by vichoeq** [comment]
El contexto de esa pregunta era si se podía elegir una sola categoría y hacer todos los experimentos en esa categoría, por eso dije que debia hacer al menos un experimento en cada categoría, aunque me falto agregar, **en cada categoría que vayas a analizar**.

Sorry por la confusión.

**Comment by diegoaguayo** [comment]
Tengo una pregunta parecida. En en un anuncio por siding se dijo:
"se recomienda que primero experimenten con la función de hash y se autoriza que dejen esta mejora para el resto de sus experimentos."
Digamos, por ejemplo, que  elijo las categorías A (para experimentar con la función de Hash), B y C. Si sigo la recomendación los experimentos que podría hacer son A, AB, AC y finalmente ABC. Pero se pierden dos experimentos que serian B por sí solo y C por sí solo. Esta bien esto?

**Comment by vichoeq** [comment]
Si, está bien. Es una inevitable consecuencia de como planteamos los experimentos.

**Comment by miguelramirezv** [comment]
Otra pregunta! Está bien si en un experimento, por ejemplo A, me da peor rendimiento que el caso base? Esto dado que el caso base se realizó una función de hash bastante buena como Zobrist ya que si no, no iba a poder ser comparable

**Comment by vichoeq** [comment]
@miguelramirezv Sí, está perfecto. Los que evaluamos de los experimentos no es que tan buenos son los resultados obtenidos, sino que tan bueno es el análisis que hacen al respecto.

**Comment by trinigomez** [comment]
Hola, una pregunta similar respecto al anuncio en el siding. Dice que podemos mantener la función de hash para el resto de los experimentos, ¿eso incluye los individuales? Es decir, podemos hacer experimentos sobre B y C (por ejemplo) manteniendo la función de hash alterada?

**Comment by caespinoza5** [comment]
@trinigomez Sí, incluye los tests individuales. Si puedes hacer experimentos sobre B manteniendo la función de hash alterada.
