### ISSUE TITLE
Tiempo de ejecución en "Generando gráficos"

### ISSUE THREAD

**Issue by tfflores** [IIC2133-PUC/2020-1#205]
Hola, tengo una duda con respecto a la generación de gráficos de "run_homework.py".

Resulta que una vez ejecutados todos los tests, procede a generar gráficos, pero en el caso más reciente que probé (en el que corren todos los test en <10 seg), se demora una eternidad en generar los últimos gráficos (del 100 en adelante). ¿Esto es normal? Literalmente tardó más de 40 min o 2 URFS en generar los 127 gráficos.

PD: Y ocupa más de 15 GB la carpeta con los resultados 😮.

**Comment by vichoeq** [comment]
Si, es normal. Los tests mas grandes tienen del orden de millones de estados distintos.

> 2 URFS

jajajajaj buena medida de tiempo

**Comment by yerkko** [comment]
Si quieres hacer el proceso más expedito, puedes cambiar el gráfico por uno que hagas tú usando matplotlib por ej. 
De todas formas, altair tiene la opción de añadir jitter, lo que reduce enormemente la cantidad de puntos y el tiempo de ejecución (tendrías que investigar tú como implementarlo)
