### ISSUE TITLE
Resultados run_homehorwk.py

### ISSUE THREAD

**Issue by niguzman** [IIC2133-PUC/2020-1#206]
Hola,
No entiendo bien que son los X_0, X_1 y R^2 que salen al correr python3 run_homehorwk.py en las categorías de "Result test total_states vs unique_states", "Result test total_states vs collisions", "Result test total_states vs resizes" y "Result test total_states vs time"

**Comment by ljrodriguez1** [comment]
Yo entiendo que es una regresion donde x_0 es donde la recta corta con el eje y y x1 la pendiente. R^2 es algo asi como que tan bien ajusta la recta a los datos

**Comment by yerkko** [comment]
Son los pesos del polinomio de la regresión lineal en forma canónica (el primero es el peso del término de más grande orden) (al revés de como lo menciona @ljrodriguez1) . R^2 es el coeficiente de regresión de Pearson, mientras más cercano a 1, mejor la regresión. 
De todas formas, como se menciona el enunciado de la tarea y en varias issues, **no es necesario** que usen estos estadísticos si es que no manejan los conceptos.
