### ISSUE TITLE
Dudas imlementacion Doble hashing

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#208]
Hola, estuve investigando como se implementa doble hashing y encontre varias funciones que se ocupaban como segundo hash en caso de coliciones. El tema es que probando con varias de las que encontre, me paso que al realizar el modulo de los valores siempre me daba 0 y se ve sumamente poco probable que el modulo con numeros primos de 0. No agregue las formulas porque no se si se puede. Pero hay alguna razon porque el modulo siempre de 0?

Gracias

**Comment by cacosandon** [comment]
Puede ser por muchas cosas, puede haber un error en tu código. Puedes acercarte al discord para verlo!
