### ISSUE TITLE
Duda Materia I3: Orden Topológico

### ISSUE THREAD

**Issue by JoacoCoyu** [IIC2133-PUC/2020-1#209]
Hola!

Tengo una duda sobre orden topológico respecto al orden en que van quedando las actividades por realizar en la lista (vértices en la cola). Comprendo que al final el último vértice de la lista es aquel con el menor valor en time.end, y como en clases mencionamos, independiente de donde uno comience a realizar el orden, este último vértice no cambiaría.

Esta última propiedad sobre que el último vértice se mantendrá, independiente de por dónde comienza a ordenar, no entendí muy bien porque se cumple. Espero que haga sentido la pregunta.

Gracias!

**Comment by vichoeq** [comment]
Hola, en la ayudantía hablamos de eso. ¿Lo revisaste?

https://youtu.be/hPgkRtJdZkc?t=1154

Me avisas si te queda alguna duda!

**Comment by JoacoCoyu** [comment]
gracias!

**Comment by yadran** [comment]
Ese "último" vértice no tiene aristas de salida, ¿ok?

Por lo tanto, si partes de ahí, termina inmediatamente; luego, es el que
termina primero.

Si no partes de ahí, todos los otros vértices tienen aristas de salida, por
lo que en cualquiera
que estés siempre vas a poder avanzar a otro (y no terminas ninguno), hasta
que llegues a
ese último vértice --> y de nuevo, es el que termina primero.

--Yadran

**Comment by vichoeq** [comment]
@miguelramirezv Si, efectivamente.

**Comment by JoacoCoyu** [comment]
Gracias profesor me quedo mucho más claro

**Comment by yadran** [comment]
Como lo dijimos en clases, si hay más de un "útlimo" vértice, o más de un
"primer" vértice
(ambos casos son perfectamente posibles: mira simplemente la malla de
cursos de la carrera),
entonces vas a tener distintos órdenes topológicos, dependiendo de cómo
eliges los vértices
en algunos pasos del algoritmo.  Pero estas no son las únicas condiciones
que dan origen
a más de un orden topológico.  --Yadran
