### ISSUE TITLE
Hangouts con ayudante

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#21]
Hola! Me gustaría hacer un hangouts con algún ayudante para resolver dudas específicas de Ubuntu y uso de memoria.

Gracias!!

**Comment by vichoeq** [comment]
Hola, el hangouts es para ayudarte a configurar tu computador ya que depende de cada computador.

Si las preguntas que tienes le sirven a los demás, hazlas por acá.

Saludos!
