### ISSUE TITLE
Plazo T2 y demás tareas

### ISSUE THREAD

**Issue by vichoeq** [IIC2133-PUC/2020-1#210]
Hola a todos,

### Sobre la T2

Se me han acercado algunos pidiendo más plazo para la tarea.

Hemos decidido lo siguiente:
* La T2 se puede entregar hasta el miércoles 17 a las 23:59
* El pozo para el bonus de la T2 (Gotta go fast) considerará solo a los que hayan entregado en el plazo original (Domingo 14 a las 23:59)

Este plazo aplica para la entrega de código y de las issues: o entregan ambos en el plazo original, o entregan ambos en el plazo extendido.

Hemos abierto un cuestionario en **SIDING** para que indiquen si quieren que se les corrija la T2 en  el plazo extendido. Si no contestan se considerará que quieren corregir su tarea en el plazo original.

### Sobre la T3

La T3 será en **Python**. Se publicará el Jueves 18 de Junio a primera hora. La fecha de entrega será el 12 de Julio. El tema será **Backtracking**.

### Sobre la T4

La T4, que es opcional, será en **Python**. Se considerará como una nota adicional. Es decir:

```py
TO = T0 + T1 + T2 + T3 # Tareas obligatorias
P4 = TO / 4 # Promedio de las 4 tareas obligatorias
P5 = (TO + T4) / 5 # Promedio de tareas contando la tarea opcional T4

NT = max(P4, P5) # Nota de tareas. Hacer la T4 no puede perjudicar tu nota
```

Se publicará el 13 de Julio y su fecha de entrega será el 20 de Julio. **No tendrá informe**. Consistirá en 2 problemas cortos, uno de **Programación Dinámica** y otro de **Algoritmos Codiciosos.**

Saludos!
Vicho

**Comment by JoacoCoyu** [comment]
Gracias por la información!
Hasta cuando se puede contestar el cuestionario del siding? (cómo para ver en a que plazo acomoda más optar)

**Comment by isavega** [comment]
Muuuuchas gracias!! :tada: :tada:

**Comment by vichoeq** [comment]
@JoacoCoyu Hasta el miercoles 17 a las 23:59 😉

**Comment by VicenteMerino** [comment]
@vichoeq la fórmula no debería ser P5 = (4TO + T5)/5 ?

**Comment by JoacoCoyu** [comment]
gracias Vicho!

**Comment by niguzman** [comment]
Tengo una duda, 
en el correo que mandó rectoría sobre el cierre de semestre decía que las evaluaciones podían ser hasta el sábado 18 de julio 🤒
