### ISSUE TITLE
Preguntas frecuentes I3

### ISSUE THREAD

**Issue by vichoeq** [IIC2133-PUC/2020-1#214]
Todos los algoritmos vistos en clases y sus propiedades  se asumen como ley: pueden usarlos sin demostrar nada, a menos de que les pidamos explicitamente que demuestren alguna propiedad de X algoritmo visto en clases.

Cuando se pide que diseñes / escribas un algoritmo, lo importante es que se entiendan los pasos a seguir para resolver el problema. Puedes hacerlo como pseudocódigo o prosa, o una mezcla de ambos. Evita cosas especificas de lenguajes de programacion (como malloc, structs, clases y slices) ya que lo hace mas dificil de entender..

# 1

* Las nuevas aristas no tienen un costo asociado
* Puedes asumir que existe una ruta entre s y f
* no puedes asumir que el grafo es aciclico (o ciclico)
* puedes usar todas las propiedades de BFS, incluyendo que es correcto
* la profundidad es el largo de la ruta entre s y f
* **el for ignora las nuevas aristas**
* ruta mas corta = ruta más barata
* costos = pesos

## a

* trata de ser lo mas formal posible

## b
* si la complejidad depende en alguna forma de los pesos de las aristas, ve tu como lo incluyes en los cálculos
* la complejidad siempre se asume que es en el peor caso 
* agregar un nodo o una arista es O(1)
* el peso de la arista se accese en O(1)

## c

* se refiere a usar dijksta en vez de SPW

# 2

* puedes asumir que no hay inconsistencias ni contradicciones en la malla
* el formato en el que viene la malla debes definirlo tu. sabes que tienes una lista de cursos que patrick debe aprobar, y cada curso tiene prerequisitos.
* no existen los co-requisitos
* el output de tu algoritmo tiene que ser la lista de cursos por cada semestre. estructurala como quieras, mientras no haya ambigüedad.
* no hay convalidacion de ramos ni nada.
* no puedes asumir que no haya requisitos redundantes
* no hay limite de requisitos
* tu tienes un problema de la vida real y quieres resolverlo con un algoritmo. Por lo tanto, si vas a usar una estructura de datos como un grafo, debes definir como se construye. 
* la complejidad es en el peor caso

# 3

* E' no necesariamente es subconjunto de E
* no hay ninguna restriccion en como se relacionan E y E'
* **G y G' tienen exactamente el mismo grafo de componentes.**
* El input del algoritmo es solo G
* No es necesario generar G', basta con calcular Delta E
* para ser considerado eficiente, su complejidad tiene que ser logarítmica, lineal, o linearítmica
* un nodo que no es alcanzable por ningun otro es una CFC en si misma. revisar el algoritmo visto en clases
* tanto G como G' pueden ser disconexos. Lo importante es que sus grafos de componentes sean iguales

**Comment by BenjaPrograma** [comment]
En la pregunta 1b, eliminar una arista que complejidad tiene? Saludos

**Comment by fediaz3** [comment]
Hola! en la pregunta 2, ¿se pide retornar una lista que tenga los cursos y especifique  a que semestre pertenece o retornar por separado una lista por cada semestre?, o ¿se puede entregar como uno quiera?

Gracias

**Comment by tamaralues** [comment]
La estructura del input de la pregunta 2 la podemos definir como queramos?

**Comment by jeschuwirth** [comment]
@BenjaPrograma,
Eliminar una arista es O(1)

**Comment by jeschuwirth** [comment]
@fediaz3,
Como quieres, puedes estructurarla como te parezca más cómodo mientras no haya ambigüedad.

**Comment by jeschuwirth** [comment]
@tamaralues,
El formato en el que viene la malla debes definirlo tu. sabes que tienes una lista de cursos que Patrick debe aprobar, y cada curso tiene prerequisitos. 

Te recomiendo fuertemente explicar el formato que uses para que el ayudante te entienda

**Comment by miguelramirezv** [comment]
Hola! En la pregunta 1, el bfs es bfs++ visto en Dijkstra o es bfs simple visto en Grafos I?

**Comment by VicenteMerino** [comment]
@vichoeq entonces según los dibujos que hiciste, aunque un nodo (que no esté en otra CFC) no tenga Loop, igual consideramos ese nodo como tal como una CFC?

**Comment by jeschuwirth** [comment]
@VicenteMerino,
Eso es materia del curso

**Comment by vichoeq** [comment]
@VicenteMerino 
> Pregunta 3: G' es conocido?

No. Además, como podras ver por los ejemplos, G' no es único.

**Comment by vichoeq** [comment]
@miguelramirezv 

> En la pregunta 1, el bfs es bfs++ visto en Dijkstra o es bfs simple visto en Grafos I?

BFS es BFS y BFS++ es BFS++. Además, BFS++ no existe, fue un nombre temporal que le pusimos en la clase a un algoritmo que opera como BFS pero que además es capaz de manejar aristas con costos, el cual resultó ser Dijkstra.

**Comment by danustilovsky** [comment]
Hola, en la pregunta 3 es valido imprimir cada curso con su semestre correspondiente? o debe necesariamente "retornar" algo que permita obtener listas con los cursos para cada semestre?

**Comment by jeschuwirth** [comment]
@danustilovsky 
Es un problema real que debes encontrar como resolver, por lo tanto como lo implementas y resuelves queda a criterio tuyo

**Comment by michimalonko** [comment]
en la pregunta 1 pueden ser los pesos 0?, de ser asi, al ejecutar bfs al no importarle a este los pesos consideraría por ejemplo un camino de pesos 0 con una profundidad diferente a 0 que seria el real costo de ir hacia ese nodo por ese camino, lo cual no daría una respuesta correcta

**Comment by jcechavarri** [comment]
Para la pregunta 3, qué complejidad tiene obtener |E|?

**Comment by jeschuwirth** [comment]
@jcechavarri,
O(1)

**Comment by vichoeq** [comment]
@danustilovsky 

> Hola, en la pregunta 3 es valido imprimir cada curso con su semestre correspondiente? o debe necesariamente "retornar" algo que permita obtener listas con los cursos para cada semestre?

Me imagino que es la pregunta 2. Ambos son correctos.

**Comment by vichoeq** [comment]
@michimalonko 

> en la pregunta 1 pueden ser los pesos 0?, de ser asi, al ejecutar bfs al no importarle a este los pesos consideraría por ejemplo un camino de pesos 0 con una profundidad diferente a 0 que seria el real costo de ir hacia ese nodo por ese camino, lo cual no daría una respuesta correcta

0 no es un numero positivo.

**Comment by trinigomez** [comment]
En los algoritmos vistos en clases se usa un α[u] conocido para referirse al conjunto de nodos a los cual conecta el nodo u, esto lo podemos usar para nuestros algoritmos? Podemos asumir que se sabe ese α?

**Comment by JoseAvanzada2019** [comment]
A que se refiere con que la cantidad de aristas (E`)  es mínima?

**Comment by vichoeq** [comment]
@JoseAvanzada2019 

> A que se refiere con que la cantidad de aristas (E`) es mínima?

Que no existe un E'' que cumpla esas mismas propiedades y |E''| < |E'|

**Comment by vichoeq** [comment]
@trinigomez 
 
> En los algoritmos vistos en clases se usa un α[u] conocido para referirse al conjunto de nodos a los cual conecta el nodo u, esto lo podemos usar para nuestros algoritmos? Podemos asumir que se sabe ese α?

Si, α[u] es una lista de todas las aristas de la forma (u, x), asique puedes usarlo sin problemas.

> En la pregunta 2, hay que contar la complejidad de armar la estructura de la malla o podemos asumir que ya está dada al empezar nuestro algoritmo?

No puedes asumir que tu algoritmo recibe la estructura armada, por lo que tienes que incluir en el analisis el proceso de armarla.

**Comment by trinigomez** [comment]
> @trinigomez
> 
> > En los algoritmos vistos en clases se usa un α[u] conocido para referirse al conjunto de nodos a los cual conecta el nodo u, esto lo podemos usar para nuestros algoritmos? Podemos asumir que se sabe ese α?
> 
> Si, α[u] es una lista de todas las aristas de la forma (u, x), asique puedes usarlo sin problemas.
> 
> > En la pregunta 2, hay que contar la complejidad de armar la estructura de la malla o podemos asumir que ya está dada al empezar nuestro algoritmo?
> 
> No puedes asumir que tu algoritmo recibe la estructura armada, por lo que tienes que incluir en el analisis el proceso de armarla.

Gracias por la respuesta! perfect que haya que incluir el análisis de como se armará. Armar la estructura eso si tiene una complejidad asociada, esa complejidad se toma en cuenta para 𝑶(|cursos| + |requisitos|) ? ¿O  𝑶(|cursos| + |requisitos|) es solamente del algoritmo para asignar cursos a semestres? (asumiendo que ese algoritmo recibirá como input la estructura ya armada)

**Comment by pgarnham** [comment]
Para la pregunta 2 podemos asumir que la cantidad de semestres es lo suficientemente bajo como para que no aumente el orden de magnitud, si debo recorrer un grafo tantas veces como semestres tenga que hacer Patrick por ejemplo ?

**Comment by silvamatias** [comment]
Hola, cual es la complejidad de obtener la transpuesta de un grafo?

**Comment by vvcastro** [comment]
Hola! En la pregunta 2, cuando dicen:

> tu tienes un problema de la vida real y quieres resolverlo con un algoritmo. Por lo tanto, si vas a usar una estructura de datos como un grafo, debes definir cómo se construye.

se tiene que considerar la construcción de la estructura en el calculo de nuestra complejidad? Es decir, la construcción es parte de la complejidad requerida?

**Comment by vichoeq** [comment]
@trinigomez 

> Gracias por la respuesta! perfect que haya que incluir el análisis de como se armará. Armar la estructura eso si tiene una complejidad asociada, esa complejidad se toma en cuenta para 𝑶(|cursos| + |requisitos|) ? ¿O 𝑶(|cursos| + |requisitos|) es solamente del algoritmo para asignar cursos a semestres? (asumiendo que ese algoritmo recibirá como input la estructura ya armada)

Armar la estructura es parte de resolver el problema, por lo que su complejidad es parte de lo que se pide.

**Comment by vichoeq** [comment]
@pgarnham 

> Para la pregunta 2 podemos asumir que la cantidad de semestres es lo suficientemente bajo como para que no aumente el orden de magnitud, si debo recorrer un grafo tantas veces como semestres tenga que hacer Patrick por ejemplo ?

No.

**Comment by vichoeq** [comment]
@silvamatias 

> Hola, cual es la complejidad de obtener la transpuesta de un grafo?

O(E).

**Comment by vichoeq** [comment]
@vvcastro 

> Hola! En la pregunta 2, cuando dicen:
> 
> > tu tienes un problema de la vida real y quieres resolverlo con un algoritmo. Por lo tanto, si vas a usar una estructura de datos como un grafo, debes definir cómo se construye.
> 
> se tiene que considerar la construcción de la estructura en el calculo de nuestra complejidad? Es decir, la construcción es parte de la complejidad requerida?

Armar la estructura es parte de resolver el problema, por lo que su complejidad es parte de lo que se pide.

**Comment by tamaralues** [comment]
En la pregunta 2,  esa lista de curso también contienen los pre-requisitos y de ser así, eso también tendrían pre-requisitos? Qué en las preguntas frecuentes sale que todos tienen pre-requisitos, pero no sería entonces no tener un punto de partida?

**Comment by vichoeq** [comment]
@tamaralues 

> En la pregunta 2, esa lista de curso también contienen los pre-requisitos y de ser así, eso también tendrían pre-requisitos?

No entiendo tu pregunta. 

> Qué en las preguntas frecuentes sale que todos tienen pre-requisitos, pero no sería entonces no tener un punto de partida?

Con eso se refiere a que conoces los pre-requisitos para cada curso, pero esos pre-requisitos pueden ser "ninguno".

**Comment by tamaralues** [comment]
@vichoeq A yaya con lo segundo me queda clara mi pregunta! Muchas gracias!

**Comment by isavega** [comment]
> @JoseAvanzada2019
> 
> > A que se refiere con que la cantidad de aristas (E`) es mínima?
> 
> Que no existe un E'' que cumpla esas mismas propiedades y |E''| < |E'|

Siguiendo con esta issue, en las preguntas frecuentes se indica que "no hay ninguna restricción en como se relacionan E y E'". Si en teoría no restricción, como puedo afirmar que  |E'| < |E|?

**Comment by mistico0121** [comment]
Hola. Puedo usar la estructura "set" en la prueba?

**Comment by michimalonko** [comment]
En la P2 puedo definir como llegan los datos a mi gusto, podria esto ser un diccionario donde cada llave sea un curso y el valor de estas llaves sea un lista donde están los requisitos?
En la P3 como se vio el algoritmo de kosaraju en clases puedo utilizarlo para obtener las cfc?

**Comment by jeschuwirth** [comment]
@mistico0121 
si

**Comment by jeschuwirth** [comment]
@isavega,
Del enunciado de la prueba no puedes afirmar que |E'|<|E|. Si crees que esto es correcto lo puedes explicar en tu prueba.

**Comment by vichoeq** [comment]
@mistico0121 

> Hola. Puedo usar la estructura "set" en la prueba?

Los conjuntos no son una estructura, son un constructo matemático. Y si, puedes usarlos. No se si viste que el algoritmo en la 1 los usa.

**Comment by jeschuwirth** [comment]
@michimalonko,

P2) 
Es un problema real que debes encontrar como resolver, por lo tanto como implementas los inputs/outputs y como lo resuelves queda a criterio tuyo

P3)
 Todos los algoritmos vistos en clases y sus propiedades se asumen como ley: pueden usarlos sin demostrar nada, a menos de que les pidamos explicitamente que demuestren alguna propiedad de X algoritmo visto en clases.

**Comment by vichoeq** [comment]
@isavega 

> Siguiendo con esta issue, en las preguntas frecuentes se indica que "no hay ninguna restricción en como se relacionan E y E'". Si en teoría no restricción, como puedo afirmar que |E'| < |E|?

No puedes afirmar eso: si el grafo original es mínimo, entonces |E'| = |E|

**Comment by camaruri** [comment]
obtener el |V| de un grafo tambien es O(1), me refiero a obtener el numero de nodos que tiene un grafo.

**Comment by jeschuwirth** [comment]
@camaruri 
Si

**Comment by silvamatias** [comment]
Cual es la complejidad de crear vertices auxiliares en el problema 1?

**Comment by jeschuwirth** [comment]
@silvamatias,
O(1)

**Comment by fediaz3** [comment]
Hola!
En el ejemplo escrito en el cuaderno, al inicio de esta issue.
En estricto rigor, el nodo E, ¿ no debería tener un rulo (una arista que llegue a sí misma) para que sea considerado una CFC y luego parte del grafo de CFCS? Que por definición, tiene que ser mutuamente alcanzable, osea que de E se pueda ir y volver a E, no solo ir a E. En el ejemplo de clases, el nodo "solo" también aparece con un rulo.
Solo eso, para tener consistencia en el conteo de las aristas

Gracias

**Comment by jeschuwirth** [comment]
@fediaz3,
Misma respuesta que a VicenteMerino

> @vichoeq entonces según los dibujos que hiciste, aunque un nodo (que no esté en otra CFC) no tenga Loop, igual consideramos ese nodo como tal como una CFC?


Es materia del curso

**Comment by mfortiz** [comment]
Hola,
Quiero saber si entendí bien
1. La complejidad de crear (w-1) vértices es O(1)
2. La complejidad de agregar w aristas es O(1)

Gracias.

**Comment by fediaz3** [comment]
@jeschuwirth Ya le daré una vuelta. 
En todo caso, podemos asumir que la foto que subieron esta bien?

**Comment by vichoeq** [comment]
@mfortiz 
> Hola,
> Quiero saber si entendí bien
> 
>     1. La complejidad de crear (w-1) vértices es O(1)
> 
>     2. La complejidad de agregar w aristas es O(1)

No. 

Crear un vértice es O(1)

Agregar un vértice es O(1)

Agregar una arista es O(1)

:+1:

**Comment by naviera** [comment]
Se asume que la complejidad de Kosaraju se vio en clases o la tengo que demostrar?

**Comment by yerkko** [comment]
@naviera 
**Todos los algoritmos vistos en clases y sus propiedades se asumen como ley: pueden usarlos sin demostrar nada, a menos de que les pidamos explicitamente que demuestren alguna propiedad de X algoritmo visto en clases.**

**Comment by silvamatias** [comment]
en la pregunta 3

- se puede asumir que las distintas componentes están conectadas entre ellas?

- hay que demostrar la complejidad?
