### ISSUE TITLE
Tiempos run_homework vs .solver

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#217]
Hola, los 10 segundos que corre como maximo run_homework es el mismo que se imprime al correr ./solver? Porque si lo corro a mano deberia llegar mucho mas lejos y la diferencia me da de mas de 5 segundos. 

Vi que habia una issue mas o menos parecida pero intente de reiniciar mi computador y igual el test que derrota a mi algoritmo no cambio y estoy escribiendo los resultados entonces necesito los graficos ojala lo mas precisos posible.

Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Te recomiendo que veas esta issue: https://github.com/IIC2133-PUC/2020-1/issues/222

Respecto a los gráficos, en las issues no evaluaremos cuán lejos llegan, si no el análisis que hacen sobre los experimentos que realizan. Si con A llegabas a 30, con B a 40, y combinándolos llegas a 60 y muestras datos, gráficos que respalden por qué mejoró y una breve justificación, está bien.
