### ISSUE TITLE
[T2] Referencias del código

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#218]
Hola! Estoy tratando de referenciar el código como dice la página que nos pusieron en el enunciado:

https://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github

Pero en vez de ponerme las lineas de mi código en la issue, me aparece un link que me lleva al commit. ¿Cómo lo hago para que me muestre las lineas en la misma issue?

**Comment by vichoeq** [comment]
Asegurate de seleccionar varias lineas (salen marcadas en amarillo)

El URL debería terminar con #LX-LY, con X la linea inicial e Y la linea final de tu referencia.

**Comment by miguelramirezv** [comment]
Hola! Efectivamente eso esto haciendo, un link (cortándolo un poco) aparece así por ejemplo:

https://github.com/.../commit/25b1facf9831fe1d14b6ed9#diff-5eb162cf653847571c24c1bf8bc5b29aR33-R47

Como puedes ver, el # me aparece bastante antes, y la linea se marca con una R en vez de una L, probé cambiando R por L pero tampoco funcionó. ¿Qué me estará faltando hacer? Como dice la página, lo que copio es el url al seleccionar las lineas.

**Comment by vichoeq** [comment]
Hm, lo estoy probando. Apenas le hago click a una linea X me aparece LX en el URL arriba, y si hago shift-click más abajo a otra linea Y me aparece #LX-LY...

https://github.com/IIC2133-PUC/2020-1/blob/94f2f98a86ca33e7fef3b98157f06088f0247e32/Talleres/Taller%201%20-%20Backtracking/sudoku/sudoku_simple.py#L95-L114

Si aun asi no lo puedes hacer hablame por discord pa que lo veamos en tu PC.

**Comment by atroncoso2** [comment]
No sé si ya lo resolvieron, pero a mi me funciona copiando el link directamente en issue, es decir sin declarar que voy  insertar un url.
