### ISSUE TITLE
Duda Análisis

### ISSUE THREAD

**Issue by robertov1** [IIC2133-PUC/2020-1#219]
Hola! 

Para la parte de análisis a que se refieren con: "Se espera que por cada categorı́a pruebes distintas configuraciones"?

Hay que poner en el analisis esas diferentes configuraciones? O es que probemos distintas configuraciones y dejémos solo una para el análisis?

Gracias!

**Comment by vichoeq** [comment]
Se espera que realices más de un experimento para poder elegir la mejor opción, pero para el análisis se va a evaluar el que escojas para cada categoría. En tus palabras,

> que probemos distintas configuraciones y dejémos solo una para el análisis

El mínimo a probar sería 1 por categoría a analizar, y dejar esa para el análisis.

**Comment by vichoeq** [comment]
Pero muchas conclusiones no vas a poder sacar sobre "la mejor opcion" si solo pruebas una.

**Comment by robertov1** [comment]
Gracias!
