### ISSUE TITLE
Tarea 0: Problema con Ubuntu correr archivo compilado

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#22]
Hola! Estoy trabajando en la máquina virtual con el Ubuntu del tutorial de la Wiki y me funciona bien el make pero cuando hago trato de correr el archivo con "./simulate .." me sale un problema, que es raro porque en mi Mac sí puedo correrlo. El problema que me sale es este:

Bash: ./filename : Cannot execute binary file

Con filename = simulate. Qué es? Busqué y me salía que puede ser que el Ubuntu que instalé no lee esos archivos binarios, pero sería raro porque como dije instalé el que salía en la Wiki. O mi make estará compilando mal? 

Muchas gracias!

**Comment by yerkko** [comment]
Puedes correr código del taller o de los ejemplos?

Por otra parte, intenta ejecutando chmod +x, este comando le da permisos de ejecución al binario compilado.
Ej:
``` 
chmod +x simulate
 ./simulate
```
De no funcionarte esto, por favor manda el resultado de `gcc -v `en la terminal. Te debería salir algo como esto
![image](https://user-images.githubusercontent.com/48332955/78101387-c2a7a000-73bd-11ea-883a-08d8dc301fcf.png)

**Comment by miguelramirezv** [comment]
Hola! Sí me corre el código del taller en Ubuntu. Se hace el make y después sí puedo correr los archivos compilados

Con respecto a chmod +x, no pasó nada cuando lo corrí, tal vez no lo corrí muy bien porque no me quedó claro como hacerlo. En la siguiente foto se ve como lo intenté correr y no funcionó. También se ve lo que aparece al correr gcc -v

<img width="1313" alt="Screen Shot 2020-04-01 at 6 26 22 PM" src="https://user-images.githubusercontent.com/17711310/78188725-17dbc400-7447-11ea-9387-ac5e0e83341c.png">

Qué puede ser?

Muchas gracias!!

**Comment by yerkko** [comment]
En la carpeta donde se encuentra el binario ejecuta textualmente este comando:
`chmod +x simulate` 
(fíjate que **no es ./simulate argumentos**, si no que **sólo simulate**)
y luego intenta correr el binario con este, poniendo los argumentos:
`./simulate argumentos`
En tu caso sería 
`./simulate tests/unit/0_gate_enqueue.txt`
Te pedí el gcc -v para revisar si estabas compilando para linux x86_64. Podría haber pasado que estabas generando binarios para otro S.O.

Me dices si se soluciona

**Comment by miguelramirezv** [comment]
Lo acabo de hacer y me sigue saliendo el mismo problema. Es raro porque sí corre en mi mac pero no corre en la máquina virtual, y en la máquina virtual sí corren lo visto en clases pero no corre mi programa. Además, hasta ahora corre bien mi código los test y a veces sale un Segmentantion Fault 11, no sé si eso sirve de algo.

Te dejo un screenshot de lo que pasó cuando corrí los comandos que me dijiste:

<img width="994" alt="Screen Shot 2020-04-02 at 12 47 36 PM" src="https://user-images.githubusercontent.com/17711310/78269591-2d50fc80-74e0-11ea-903e-823f61555973.png">


No sé que puede ser! Pero mientras no me funcione no puedo usar valgrind que sé que es de gran ayuda. Qué otra causa puede tener esto?

Muchas gracias!!

**Comment by yerkko** [comment]
Si te sale Seg Fault 11 es que estás usando demasiada memoria. Prueba a revisar tus definiciones de array, mallocs, etc. Una posibilidad es que tu mac tenga más ram que la máquina virtual y por eso no funciona

**Comment by miguelramirezv** [comment]
Hola! Ya lo arreglé y no me sale Segmentation Fault 11, si no que me corre todo bien en mi mac! Al final de correrlo me sale en la terminal:

simulate(2267,0x7fff96f5d380) malloc: *** error for object 0x7fcd2c400360: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

Que no sé bien que es porque me corre todo el programa bien igual. 

Pero el problema es que al tratar de correr los mismos comandos Pero en Ubuntu, me sale siempre lo que puse arriba en las fotos: cannot execute binary file


Qué puede ser? porque no me corre mi programa en Ubuntu? Probando con todo lo que sale arriba de chmod +x tampoco funciona

**Comment by miguelramirezv** [comment]
Arreglé el problema de Seg Fault 11 pero me sigue apareciendo el problema en la maquina virtual, qué podría ser? 

Ahora en mi mac corre todo bien y solo me sale al final, cuando tira lo último el programa, que:

simulate(2288,0x7fff96f5d380) malloc: *** error for object 0x7fa7d8e00000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

Pero alcanza a tirar todo bien antes. No sé si será esto pero no me funciona todavía en Ubuntu que es raro porque si funciona en mi Mac. Ya no sé bien que hacer 😕😕

**Comment by miguelramirezv** [comment]
Ya arreglé ese problema también! Ahora lo único que me sale raro es que, cuando hago make, antes de los compiled.., me sale:

clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]

Pero es solo eso, que me sale en mi mac, en Ubuntu me sale al tiro done compiling (ojo que se salta el compiled 'obj/simulate/main.o' y el compiled 'simulate'

**Comment by miguelramirezv** [comment]
Perdón que escriba tan seguido es que al fin estoy haciendo progreso! Me di cuenta, dado que solo me decía done compiling, tal vez había que compilarlo todo en Ubuntu. Entonces eliminé el archivo compilado de simulate e hice make de nuevo. El make me tira un error que dice: 

obj/simulate/fila.o file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target 'simulate' failed
make: *** [simulate] Error 1

Eso sí, tengo un archivo main, que importa otro archivo fila.h. Estos, repito, funcionan bien en mi Mac todo, el problema es Ubuntu. Gracias!!

**Comment by caespinoza5** [comment]
Aseguraste de correr 'make clean' en ubuntu antes de correr 'make' denuevo?

**Comment by miguelramirezv** [comment]
No sabía eso de make clean!! Eso era! Ahora me esta corriendo! 😄😄😄😄😄😄 

Muchísimas gracias!!!!! 😃😃😃

**Comment by caespinoza5** [comment]
¡De nada! Suerte con la tarea 😃

**Comment by fthurtado** [comment]
> Aseguraste de correr 'make clean' en ubuntu antes de correr 'make' denuevo?

Hola! Tengo un error parecido, donde aunque haga make clean me lo sigue tirando!
compiled 'obj/imagelib/imagelib.o'
compiled 'obj/quadtree/main.o'
compiled 'obj/quadtree/funciones.o'
obj/quadtree/funciones.o: En la función `quadTree_init':
/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:8: definiciones múltiples de `quadTree_init'
obj/quadtree/main.o:/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:8: primero se definió aquí
obj/quadtree/funciones.o: En la función `quadTree_append':
/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:16: definiciones múltiples de `quadTree_append'
obj/quadtree/main.o:/home/fthurtado/T1-2020-1-fthurtado/src/quadtree/funciones.c:16: primero se definió aquí
collect2: error: ld returned 1 exit status
Makefile:119: recipe for target 'quadtree' failed
make: *** [quadtree] Error 1
Llevo harto tiempo pegado en esto, feliz de si sabes que pasa!
