### ISSUE TITLE
Tiempos de ejecución al evaluar T2

### ISSUE THREAD

**Issue by atroncoso2** [IIC2133-PUC/2020-1#222]
Hola, 
Estoy tratando de mejorar la eficiencia de mi código y me surgen múltiples dudas respecto de los tiempos de ejecución de este. 
Hasta el momento el test en el que mi programa es derrotado varía bastante dependiendo del estado de mi computador y me surge la duda de que al momento de evaluar mi código, tiempo de ejecución del programa también puede variar bastante. 
Estoy corriendo mi programa en **wsl**, hay alguna forma de simular los tiempos de ejecución que tendría el programa al momento de la evaluación? 
He utilizado _time_ para evaluar el tiempo de ejecución de mi código y resulta que aproximadamente un 25% del tiempo en la ejecución del programa es utilizado en _sys_. Hasta el momento, el peor tiempo de mi mejor versión demora menos de 13 segundos por lo que sin este 25%, mi programa podría ejecutar todos los tests en menos de 10 segundos. Es válido considerar esto o debería seguir intentando mejorar mi código?

**Comment by sameneses** [comment]
yo estaba a punto de hacer una issue por lo mismo
quería preguntar si podemos subir el programa al servidor y correrlo ahí
en mi caso, yo uso una maquina virtual y es más lenta que mi computador, y creo que eso puede estar afectando mis resultados

**Comment by caespinoza5** [comment]
¡Hola!

Respecto a la nota de evaluación de código, aseguren que sus programas corran antes de los 10 segundos por test al ser ejecutados manualmente, para tener el puntaje completo en ese test. (Los tests a utilizar no serán los mismos pero serán bastante similares). Si quieren estar tranquilos, intenten dejar un margen de error de al menos medio segundo para que su test corra siempre antes de  9.5 segundos al ejecutarlo manualmente, y que no dependa de la ejecución.

Por otro lado, si los tests continuamente corrían en menos de 10 segundos en su computador y al recibir la nota ven que falló en algún test de evaluación, siempre está la instancia de recorrección para que puedan comentar que en su computador los tests si corrieron en el tiempo apropiado, y de ser el caso se cambia la nota sin descuento.

**Comment by atroncoso2** [comment]
Ok, perfecto. 
Y solo para estar seguro, cuando dices manualmente, te refieres a ejecutar el test por su cuenta sin el archivo Python? Es decir corriendo ./solve testX.txt ??

**Comment by caespinoza5** [comment]
Sí 🙂

**Comment by sameneses** [comment]
el problema es que mi maquina virtual es lenta todo el tiempo, así que no tengo como saber si tengo que mejorar el programa aun más o si solo estoy fallando los test porque la maquina virtual me esta atrasando, por eso quería saber si podemos usar el servidor

**Comment by caespinoza5** [comment]
@sameneses No se utiliza un servidor disponible  en la web; se evalúa en un computador particular. ¿Qué sistema operativo tienes? Si tienes Windows 10, te recomiendo que utilices linux subsystem para que tu programa corra más rápido que en una máquina virtual.

**Comment by sameneses** [comment]
ok, tengo windows 10, así que probare eso
gracias

**Comment by NicolasCastillo24** [comment]
Para estar seguro entonces, tengo dos dudas. 
Yo tenia tests que manualmente corrían en menos de 10 segundos pero luego me derrotaban al correr run_homework y en mis resultados me centro en los resultados de run_homework nomas, no hay problema?. 
Y, si un código me corre los 127 tests con run_homework, puedo asumir entonces que esta "listo" y correrá todo test en menos de 10 segundos al probarlo manualmente?

**Comment by caespinoza5** [comment]
1) No hay problema en eso.
2) Sí; si corre bien con run_homework definitivamente correrá bien manualmente.

**Comment by caespinoza5** [comment]
@chapito96  ¿Ocupaste valgrind para ver dónde ocurría el error?

**Comment by chapito96** [comment]
estoy en eso!

**Comment by chapito96** [comment]
Era un error en los limites de un for que se me escapaba. Pero me llama la atención que pasaba los 127 tests
