### ISSUE TITLE
Error en Run_homework.py

### ISSUE THREAD

**Issue by srhernandez1** [IIC2133-PUC/2020-1#223]
Cuando trato de correr el archivo "run_homework.py" con el comando "python3 run_homework.py" desde el terminal tengo el siguiente error:
![Screenshot (8)](https://user-images.githubusercontent.com/42222696/84715383-47767480-af3e-11ea-9f58-cc41aa2b2937.png)

Y si lo trato de correr directo del editor de python obtengo este error:
![Screenshot (10)](https://user-images.githubusercontent.com/42222696/84715462-86a4c580-af3e-11ea-9b79-9e96227d2af5.png)

**Comment by caespinoza5** [comment]
¿Qué versión de python tienes? Intenta actualizarla a una más reciente (3.6>).

**Comment by srhernandez1** [comment]
Al ver la version desde el susbsistema de windows me dice que el 2.7. Como puedo actualizarlo?

**Comment by srhernandez1** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/42222696/84716824-37609400-af42-11ea-9286-45e2a08abdbf.png)

**Comment by caespinoza5** [comment]
¿Qué pasa si corres `python3` en vez de `python`? Te recomiendo que pruebes el siguiente comando también:

`sudo apt-get install python3.6`

Y luego intentes correr `python3.6 run_homework.py` o `python3 run_homework.py` y ve qué tal.

**Comment by srhernandez1** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/42222696/84804721-2f9c0080-afd1-11ea-8e0e-679696f819f6.png)
Al tratar de instalar python 3.6 me dice que no encuentra el paquete, y con python3 me dice version 3.5.2.
Al intentar hacer python3 run_homework.py me sigue dando el error de IncrementalBar.

**Comment by srhernandez1** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/42222696/84805645-966de980-afd2-11ea-944a-52a91eb54a53.png)
Y si pruebo con gitbash, me da el error del modulo progress, aunque ya sale como instalado con pip3 isntall progress.

**Comment by caespinoza5** [comment]
Intenta correr primero `sudo apt-get update` y luego `sudo apt-get install python3.6`.

Si sigues teniendo muchos problemas, simplemente cambia los f-strings de los archivos python, desde `f"este texto tiene dos variables: {var1} y {var2}"` a `"este texto tiene dos variables: {} y {}".format(var1, var2)`

**Comment by rafafdz** [comment]
> Cuando trato de correr el archivo "run_homework.py" con el comando "python3 run_homework.py" desde el terminal tengo el siguiente error:
> ![Screenshot (8)](https://user-images.githubusercontent.com/42222696/84715383-47767480-af3e-11ea-9f58-cc41aa2b2937.png)
> 
> Y si lo trato de correr directo del editor de python obtengo este error:
> ![Screenshot (10)](https://user-images.githubusercontent.com/42222696/84715462-86a4c580-af3e-11ea-9b79-9e96227d2af5.png)

Yo pude solucionar el error de abajo (OSError) en linux cambiando la siguiente parte de la línea **31** de ```run_homework.py``` :  ```datetime.now().isoformat("_","seconds")``` por ```datetime.now().isoformat("_","seconds").replace(":", "-"))```.  El problema es que el sistema operativo no permite crear carpetas que contengan ':' en el nombre

**Comment by srhernandez1** [comment]
Gracias! Ahora si me funciona
