### ISSUE TITLE
T2 commits

### ISSUE THREAD

**Issue by fthurtado** [IIC2133-PUC/2020-1#225]
Hola, yo subí la tarea el domingo, pero me ha quedado dando vueltas el tema de los commit. 
Realicé la tarea sin fijarme en esto. De hecho, puede que haya hecho commit de dos funciones implementadas al mismo tiempo (A+B por ejemplo, sin antes subir ninguna por si sola). Pero de igual forma tengo las referencias respectivas a cada issue.
Es un problema? Es obligación tener un commit por cada implementación que haga?

**Comment by vichoeq** [comment]
Puede ser un problema al evaluar tu informe, pero tu código se va a evaluar correctamente.
