### ISSUE TITLE
Diferencia de tiempos entre ./solve y run_homework.py.

### ISSUE THREAD

**Issue by Nico-gf** [IIC2133-PUC/2020-1#227]
Hola,
Al correr run_homework.py con ciertas configuraciones de mi codigo este me dice que falla en un test X (que va cambiando cada ver que lo ejecuto), pero si luego yo corro el codigo con ./solver tests/X.txt este lo resuelve en menos de un segundo.

Mi problema es que si bien no me afecta esto la nota del código ya que manualmente si resuelve los problemas, al momento de realizar experimentos no me da gráficos que necesito usar en el informe.
Gracias de antemano.

**Comment by kelseyfranken** [comment]
Tengo el mismo problema

**Comment by jnhasard** [comment]
Yo también :(

**Comment by yerkko** [comment]
Están llamando a python desde windows o desde WSL?

**Comment by jnhasard** [comment]
Yo tengo mac, lo ejecuto en la terminal con python3 run_homework.py
Se cae en el 118 y si lo corro con ./solver tests/118.txt se demora 7.5 segundos jajaja

**Comment by Nico-gf** [comment]
Lo estoy corriendo en WSL

**Comment by yerkko** [comment]
Se puede deber al overhead de llamar desde python y generar los archivos. Como dijo Cristóbal en otra issue 

"> ¡Hola!
> 
> Respecto a la nota de evaluación de código, aseguren que sus programas corran antes de los 10 segundos por test al ser ejecutados manualmente, para tener el puntaje completo en ese test. (Los tests a utilizar no serán los mismos pero serán bastante similares). Si quieren estar tranquilos, intenten dejar un margen de error de al menos medio segundo para que su test corra siempre antes de 9.5 segundos al ejecutarlo manualmente, y que no dependa de la ejecución.
> 
> Por otro lado, si los tests continuamente corrían en menos de 10 segundos en su computador y al recibir la nota ven que falló en algún test de evaluación, siempre está la instancia de recorrección para que puedan comentar que en su computador los tests si corrieron en el tiempo apropiado, y de ser el caso se cambia la nota sin descuento.
"
