### ISSUE TITLE
Armar Puzzle [Tarea 3]

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#229]
Hola! No estoy entendiendo como se arman ó definen los estanques en el puzzle con el input que nos dan ¿podrían darme un ejemplo de cómo están traduciendo el input para el tablero?  

Tampoco me calza el llenado de materia para cada estanque pero primero me interesa lo de “armar” los estanques

**Comment by vichoeq** [comment]
Hola,

En el archivo de input, las celdas de la matriz tienen un ID que indica el estanque al que pertenecen. Todas las celdas con el mismo ID de estanque forman parte del mismo estanque.

Quizás queda mas claro con un dibujito.

![image](https://user-images.githubusercontent.com/5317897/85028270-d9ea6400-b148-11ea-8167-bfe944c2754d.png)

¿Se nota ahi?

**Comment by Arcoirisky** [comment]
Mejor xD Entré en pánico, sorry
