### ISSUE TITLE
[Tarea 0] Dudas con make y con Segmentation fault: 11

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#23]
Hola! Tenía dos dudas:

1) La primera, es que cuando corro el comando make me sale siempre:

`clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]`

A veces más de una vez. No sé bien a lo que se refiere porque busqué y me salía que podían ser errores en el archivo make pero como dijeron en ayudantía que si nos salía que teníamos problema en el make lo más probable es que era algo nuestro, no sé bien qué puede ser.

2) La segunda, es que cuando corro "./simulate ..." funciona, pero se para en la mitad diciendo:

`Segmentation fault: 11`

Esto ocurre cuando llego a una función en el mail del estilo:

` print_gates(terminal_actual);`

donde tengo que, en el archivo archivo.h la función declarada y en el archivo archivo.c tengo algo del estilo:

void terminal_print_gates(Terminal* terminal){
  int g = terminal -> gates;
  printf("Este terminal tiene %i Puertas\n", g);
}

Y también definí en el archivo.h que terminal tiene int gates, que creo que esto funciona bien porque no se cae antes el programa cuando defino terminal, si no que se cae después. 

Esas son mis dos preguntas, todavía no lo puedo tirar con valgrind por un problema que puse en otra issue, entonces no puedo sacar más información.

Muchas gracias!!

**Comment by Kitaps** [comment]
Hola, en primer lugar, disculpa la demora en responder. 
En segundo lugar, como vas solucionando esos problemas?

**Comment by miguelramirezv** [comment]
Hola! Mal jajaja No he podido avanzar con esto aún!

**Comment by Kitaps** [comment]
La pregunta 2 me tiene más preocupado. 
Cuando debugueas con prints, hasta dónde te lleva?
(Antes de debuguear commitea y pushe por si acaso, no que rompas algo sin querer (me ha pasado)).

**Comment by vichoeq** [comment]
Hola, podrías haber mencionado que estás trabajando en Mac. El primer punto, 

> clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]

es porque en la Makefile se incluye la librería MATH (por eso la m de -lm).

El compilador de Mac está reclamando que se está incluyendo la librería pero no se está usando.

El segundo punto es un problema en tu código. Qué dice valgrind al respecto?

**Comment by Kitaps** [comment]
@vichoeq parece q aun no logra hacer funcionar valgrind.

**Comment by miguelramirezv** [comment]
Hola!! Sí como dijo @Kitaps  se trataba de un problema que se encontraba haciendo muuuuchos prints! Lo logré encontrar ahora. No sabía que que Segmentation fault: 11 es cuando hay un problema de memoria porque es primera vez que uso C. Pero ahora ya aprendí.

Y gracias @vichoeq , eso tampoco lo sabía! No importa que no lo use, verdad?

**Comment by Kitaps** [comment]
Se que le preguntaste a Vicho pero me tomaré la libertad de contestarte yo.
Por un lado valgrind ayuda un poco para debuguear.

Por otro lado, y más importante, sirve para ver si es que hay leaks de memoria. En otras palabras, que te falte hacer free de alguna memoria que hayas pedido (ej con malloc o calloc). En el curso esto se evalua, por lo que te recomiendo que si lo uses. La alternativa sería ser muy ordenado y confiar en tu orden y habilidad, pero eso yo por lo menos lo encuentro arriesgado.
