### ISSUE TITLE
[T3] Output y otros

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#231]
Hola! Tenía una duda de lo que se espera que se entregue de output. O sea entiendo el output final final que es el archivo con 0s y 1s, más bien mi pregunta es si también es necesario pintar los cuadrantes en la guía entregada? Porque pensando a la rápida, la gui permite leer correctamente el input y armar como el puzzle antes de resolverlo, pero luego para resolverlo no me queda muy claro como puede ser de utilidad. Es más, tal vez podría volver más lento al programa por lo que sería útil usar otra estructura para guardar los datos. ¿Estoy en lo correcto? ¿Recomiendan mejor ir usando la gui? Muchas gracias!!

**Comment by caespinoza5** [comment]
¡Hola!

Tal como dices, es recomendable usar tus propias estructuras y modelamiento para resolver el problema. La gui simplemente es una herramienta para que observen cómo su algoritmo va resolviendo el puzzle (en caso de que llamen a la gui dentro de la modelación); sin embargo, lo que se espera es que ustedes planteen su propia modelación eficiente del problema.

**Comment by vichoeq** [comment]
La idea de la GUI es ver en qué se está equivocando tu programa: si la ves constantemente reasignando la misma variable puedes darte cuenta enseguida que algo no anda bien.

Además, es tremendamente util para diseñar podas y heurísticas: puedes ver como tu algoritmo se da contra la pared una y otra vez luego de una primera asignación que tu, viendo el tablero completo, te puedes dar cuenta que estaba equivocada.
