### ISSUE TITLE
[T3] Tests

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#232]
Hola! Los tests que venía con el código que son 6x6, 10x10 y 15x15 son considerados dificultad Easy, Medium y Hard respectivamente?

Y otra duda que tenía es si habían subido las soluciones para cada uno de estos tests? Que en mi código venian sin solución y no pude encontrar soluciones ni en el repositorio ni en el siding. Y si aún no las han subido cuándo se van a subir y adónde?

Muchas gracias!!

**Comment by Arcoirisky** [comment]
Yo creo que resolví los 6x6 por si a alguien más le sirven:
test 6x6_0:
```
100001
111100
001100
000011
000001
011111
```

test 6x6_1:
```
100011
110001
110001
110111
111110
011111
```

Test 6x6_2:
```
000001
000110
111101
111100
000110
001100

```
Ojalá no estén malos xD los revisé y cumplen

**Comment by alexaptib** [comment]
Test 10x10_0:
```
1100111111
1000011111
0000011111
1100001111
0000000010
0000011111
0000000011
1110011111
0011110000
0000001111

```

Test 15x15_0:

```
111111110000111
011001110000011
011000000000001
000000000001001
000110000001001
111111111011001
001000010000000
000010000000000
000010100110101
000000000010101
000000000011111
010010000000010
110000000000110
110000000011111
111110000000000
```

**Comment by vichoeq** [comment]
Ojo que las soluciones a los tests no necesariamente son únicas. Al corregir vamos a verificar que la solución cumpla con las restricciones, no que sea exactamente X output.

**Comment by Arcoirisky** [comment]
Pero es bueno tener una idea para poder sacar el algoritmo @vichoeq

**Comment by miguelramirezv** [comment]
Yo saqué, creo que está correcto, el de 10x10_2:

0000011111
0000111100
1110100001
1000011101
0100011001
0111011111
0000010001
1100111111
0011011111
1110000000

**Comment by JoseAvanzada2019** [comment]
Hola, una pregunta, yo hice que en el output me aparezcan espacios entremedio. ¿Eso importa?

**Comment by caespinoza5** [comment]
Hola @JoseAvanzada2019 ,

No debería afectar el resultado. En cualquier caso, está la instancia de recorrección donde se puede revisar eso sin descuento alguno.

**Comment by JoseAvanzada2019** [comment]
gracias!
