### ISSUE TITLE
[T3] Tiempo de los tests

### ISSUE THREAD

**Issue by josefinabengoa** [IIC2133-PUC/2020-1#233]
Hola! 

En el enunciado sale que los tests se tienen que demorar menos de 10 segundos. ¿Este tiempo se cuenta desde el principio incluyendo el tiempo de abrir el archivo input y escribir el archivo output, ó es solo el tiempo de llamar al algoritmo, como en el código de sudoku del taller?

**Comment by caespinoza5** [comment]
¡Hola!

El tiempo se cuenta desde el principio, incluyendo lectura y escritura de input y output respectivamente. Es decir, tu programa entero debe correr bajo los 10 segundos por test.

**Comment by mimunoz11** [comment]
Hola, lo medirán con time? por ejemplo:

`time python src/solver.py tests/test15x15_2.txt out15x15_2.txt`

**Comment by niguzman** [comment]
> Hola, lo medirán con time? por ejemplo:
> 
> `time python src/solver.py tests/test15x15_2.txt out15x15_2.txt`

Tengo esta misma duda :C

**Comment by caespinoza5** [comment]
Sí se medirá con `time`.
