### ISSUE TITLE
[T3]OOP

### ISSUE THREAD

**Issue by michimalonko** [IIC2133-PUC/2020-1#234]
se puede usar OOP par modelar el problema? pregunto por que en el enunciado dice "y hagas uso de estructuras de datos del
lenguaje como Hash Sets, Diccionarios y Colas de Prioridad" y no se si debo restringirme a eso

**Comment by vichoeq** [comment]
Claro que si, usa el esquema que a tí te acomode, no hay reglas para esta tarea! ...aparte de lo que dice el enunciado 

La parte del enunciado que tu mencionas dice "se **espera** que hagas uso de...", pero no es ni obligación ni lo único que pueden usar.

**Comment by vichoeq** [comment]
Ok, si hay una regla: no pueden usar librerías externas además de las que se mencionan en el enunciado: `pqdict` y `PyQt5`

Si quieren usar otra librería externa, deben pedir permiso.

**Comment by matumartinez** [comment]
¿Se puede usar defaultdict de collections?

**Comment by vichoeq** [comment]
> ¿Se puede usar defaultdict de collections?


No es una librería externa (es parte de Python) por lo que sí se puede usar.

**Comment by naviera** [comment]
> La parte del enunciado que tu mencionas dice "se **espera** que hagas uso de...", pero no es ni obligación ni lo único que pueden usar.
Eso significa que podría hacerlo sin backtracking y tener todos los puntos?

**Comment by vichoeq** [comment]
Asumiendo que logras resolverlo en el tiempo estipulado, sí. Pero ahi tendrías que usar cosas que no hemos visto en el curso, y no vamos a solucionarte dudas sobre eso.
