### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#235]
Hola, cuando se me cae el Watcher y vuelvo a ejecutar me aparece lo siguiente:

[
![Captura de pantalla de 2020-06-24 15-58-05](https://user-images.githubusercontent.com/47841749/85621682-a8cfcf00-b633-11ea-931c-1c65198b8f57.png)
](url)

Después de un rato me vuelve a funcionar, pero no se si hay alguna forma de "matar" la conección inmediatamente

**Comment by vichoeq** [comment]
En linux, usa

```sh
sudo fuser -k 12345/tcp
```

para liberar el puerto.

**Comment by VicenteMerino** [comment]
Gracias!

**Comment by vichoeq** [comment]
Puedo preguntar por qué se cayo el watcher? Tienes algun mensaje de error?

**Comment by VicenteMerino** [comment]
Según yo en general cuando agrego algo y me sale error de sintaxis o algun otro error me sale ese error porque no se alcanza a cerrar el Watcher en la ejecución anterior, pero no estoy muy seguro la vdd.

**Comment by vichoeq** [comment]
Osea cuando se cae tu programa, no el watcher. Ok eso me tranquiliza.
