### ISSUE TITLE
Problemas en installación de qt

### ISSUE THREAD

**Issue by atroncoso2** [IIC2133-PUC/2020-1#237]
Hola, 
Estoy usando wsl y estoy teniendo problemas con qt al ejecutar solver.py. 
Me retorna el siguiente error: 

Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

He buscado y probado muchas soluciones diferentes en internet y ninguno me funciona. Quise preguntar por acá por si a alguno le pasó lo mismo y logró encontrar la solución.

**Comment by vichoeq** [comment]
No uses wsl. Ejecuta python desde windows.

**Comment by nacho-11** [comment]
Yo tengo el mismo problema, específicamente: 

```
$ python3 src/solver.py tests/test6x6_0.txt test.txt
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

Tengo Ubuntu 20.04 y Python3.8.

**Comment by vichoeq** [comment]
Probaste lo que dice? Reinstalando las librerías?

**Comment by nacho-11** [comment]
Si, también instale python3.6 y usando su respectivo pip instale pyqt5 nuevamente y sigo con el mismo error.

**Comment by nacho-11** [comment]
Finalmente lo arreglé, después de navegar por varios foros random encontré el paquete a instalar

`$ sudo apt install anki`

Saludos
