### ISSUE TITLE
Formato output

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#238]
Quería saber si se puede usar:

os
os.path

Para guardar el output.

Y aprovecho qué forma tiene el output? Es decir si me dan una dirección "/path/file.txt", debo guardarlo en "T3-VicenteMerino/path/file.txt"?

Y además puedo asumir que el output estará escrito de la forma "algo.txt", es decir un archivo .txt

**Comment by VicenteMerino** [comment]
Y aprovecho qué forma tiene el output? Es decir si me dan una dirección "/path/file.txt", debo guardarlo en "T3-VicenteMerino/path/file.txt"?

**Comment by vichoeq** [comment]
Esos módulos son parte de Python, así que los puedes usar.

Tanto el input y el output son un path: no los modifiques, sólo usalos.

**Comment by mimunoz11** [comment]
Hola,

Los "1" y "0" en el output deben ir como int o como str ? La verdad no se si hay mayor diferencia pero mejor preguntar

**Comment by VicenteMerino** [comment]
Hola, aprovecho de preguntar también si da lo mismo que al final de cada fila del output, haya un espacio extra?

**Comment by vichoeq** [comment]
@mimunoz11 

> Los "1" y "0" en el output deben ir como int o como str ? La verdad no se si hay mayor diferencia pero mejor preguntar

El output es un archivo de texto plano: no existen los tipos, todo es texto.

@VicenteMerino 

> Hola, aprovecho de preguntar también si da lo mismo que al final de cada fila del output, haya un espacio extra?

Si, da lo mismo, al leerlo le vamos a hacer strip.
