### ISSUE TITLE
Librería numpy

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#239]
Hola, se puede usar la librería numpy?

Y aprovecho de preguntar: cuales son las externas y las de python? Si se instala por pip en consola es externa?

**Comment by vichoeq** [comment]
Si, puedes usar numpy. Aunque ojo con la complejidad de las operaciones.

Si la especificación de un módulo está en https://docs.python.org, entonces es parte del lenguaje.

Si hay que instalarla con, por ejemplo, pip, entonces es externa.
