### ISSUE TITLE
Dudas Clase: El problema de ordenar

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#24]
Hola!
Estudiando me encontré con un par de dudas en esta clase, si alguien me puede responder 

1) ¿Como sabemos que existen ((n**2)-n)/2 pares en un arreglo de largo n?

2) ¿por qué dicen que en el problema de ordenar A de n elementos existen n! Permutaciones? Entiendo que sean n! Instancias pero porque una instancia es una permutación y el número va ligado. Pero ¿como llegan a que es n! ?

**Comment by Kitaps** [comment]
Hola, 

1. A primera vista me hace sentido que se base en esta regla matemática: 

Es como en proba, una combinatoria de nC2 (n sobre 2 (no se como hacer eso en Markdown :(   ))
La explicación es que tienes:
n números posibles
luego te quedan (n-1) números como posible pareja. 
No te importa el orden, solo las parejas, por lo que es una combinatoria, es decir tienes que quitarle los casos repetidos. 
n! / ((n - 2)! * 2!)
= n * (n - 1) * (n - 2)! / ((n - 2)! 2 * 1)
= n(n-1) / 2

Si quieres saber más al respecto: [link](http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/runsums/triNbProof.html).

2. Suponiendo a que te refieres a ordenar el array A de n elementos: 

Esto es algo de proba, digamos que n=3 y tenemos las posiciones a, b y c:
Entonces:
a puede ser cualquier de los 3 valores
b puede ser dos de los restantes                   es decir:   3 * 2 * 1 = 3!
c tiene que ser el que sobra

De la misma forma funciona con n: 
a puede ser cualquiera de los n valores
b puede ser cualquiera de los (n-1) valores
c puede ser cualquiera de los (n-2) valores
.
.                                                                                         
.
あ puede ser 2 de los valores restantes
い pues solo ser el valor que queda                 por lo tanto queda:   n * (n-1) * ... * 2 * 1 = n!

por si quieres leer más al respecto: [link](http://hyperphysics.phy-astr.gsu.edu/hbase/Math/permut.html#c2)

Espero que te haya quedado claro, cualquier duda me dices. Y si alguien encuentra errores o alguna informalidad me avisan porfa ;)

**Comment by vichoeq** [comment]
@Arcoirisky 

1. Una forma más simple de verlo es la siguiente:

Las parejas que contienen al elemento 1: n-1 (una por cada otro elemento)
+ las parejas que contienen al elemento 2: n-2 (restamos 1 porque ya contamos la pareja (1,2))
+ las parejas que contienen al elemento 3: n-3 (restamos 2 porque ya contamos (1,3) y (2,3))
...
+ las parejas que contienen al elemento n: 0 (ya las contamos todas)

eso es

![7c52c11ca6f815477113cf7ef2adc799](https://user-images.githubusercontent.com/5317897/77984196-42167000-72e7-11ea-9c38-367502a5006e.png)

Si no me crees la fórmula, es muy fácil demostrarla por inducción (al menos fue el ejemplo que usó mi profe en cálculo cuando nos enseñó inducción).
