### ISSUE TITLE
Con respecto al Examen

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#240]
Hola,

¿Qué entra para el examen? ¿Tendrá el mismo formato que las interrogaciones?

Saludos

**Comment by miguelramirezv** [comment]
Hola! Si es igual que antes, se podría subir más temprano? Para disminuir la probabilidad que tope con otro examen 😄

**Comment by vichoeq** [comment]
Hola, el examen tendrá el mismo formato que las interrogaciones, y lo subiremos y haremos sesión de consulta a las 9 AM.

Entra toda la materia del curso, pero en particular lo que no ha sido evaluado en ninguna prueba ni tarea.

Saludos!

**Comment by vichoeq** [comment]
(La T4 no cuenta ya que es opcional)

**Comment by vichoeq** [comment]
Hola, me apresure con la respuesta. Acabo de hablar con Yadran y su plan en realidad es que el examen dure solo 3 horas para que no se les traslape con otros examenes que tengan que dar, asique ten esto en cuenta. Ya vamos a avisar formalmente cual va a ser el formato.

Saludos!

**Comment by SaritaGP** [comment]
@vichoeq  ¿Finalmente, ya se sabe cuál será el formato del examen?

**Comment by vichoeq** [comment]
@SaritaGP siiiiii no he escrito el anuncio oficial porque estoy terminando un trabajo. Pero puedo decirlo por aca de manera informal:

El examen es de 9AM a 3PM (6 horas). Esto es para que no le estorbe con otros examenes que puedan tener. Va a estar diseñado para resolverlo en 2 hrs

Consiste de 4 preguntas, de las cuales solo tienen que responder 3.

* una pregunta de algoritmos codiciosos como prim y kruskal. Puede que esto incluya propiedades de los MST
* una pregunta de programación dinámica y los algoritmos de Bellman Ford y Floyd Warshall
* una pregunta de árboles rojo negro
* una pregunta de alguna otra materia del curso (sorpresa)

Saludos!
