### ISSUE TITLE
Complejidad funciones implementados en python

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#241]
Hola, hay alguna forma en general de saber la complejidad que tiene una función en python que viene implementado? Por ejemplo un sum sobre una lista hay dos formas de implementar esto: que cada vez que lo calcule "por detrás" haga un for sobre los elementos o en realidad se accede a un "atributo" que va calculando de forma incremental el valor (esto en verdad pensando en OOP, como yo crearía una lista, no se si es así en la práctica). En definitiva, existe alguna forma de saber la complejidad? Ya que en la documentación no aparece esto detallado, o puedo asumir que en general las operaciones son eficientes y no deberían causar mayor problema?

Gracias

**Comment by vichoeq** [comment]
En general la documentación de las librerías habla de la eficiencia, y cuando no, siempre hay alguien que ya lo preguntó en stackoverflow. Por ejemplo:

https://stackoverflow.com/questions/20135093/what-is-the-time-complexity-of-sum-in-python

Ojo que como dicen, puede depender de como están estructurados los datos, pero siempre vas a tener que al menos revisar todos los números así que no puede ser menor a n.

Cualquier librería que se respete tiene corre en tiempo theta de la cota inferior de lo que está haciendo, así que puedes usar tus habilidades de cálculo de complejidad para calcular la cota inferior de lo que están haciendo; probablemente la complejidad sea esa. Al menos las cosas de python están bien hechas, como puedes ver en esta lista:

https://wiki.python.org/moin/TimeComplexity

Para el código que tu implementes, debes ser capaz de calcular tú la complejidad en base a lo que haces tu y las librerías que ocupas.
