### ISSUE TITLE
Tiempo tests y Watcher

### ISSUE THREAD

**Issue by robertov1** [IIC2133-PUC/2020-1#242]
Hola!

Para los 10 segundos que pueden demorarse los tests es sin usar watcher? Es solo para debuggear?

Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Así es; el watcher es solo para debuggear. Los 10 segundos se consideran en el total de la ejecución de su programa por test, por lo que recomendamos no llamar al watcher en la entrega que suban a github.

**Comment by robertov1** [comment]
Buenísimo! Gracias!

Y los inputs que están en solver.py los tenemos que sacar también?

**Comment by caespinoza5** [comment]
Así es; tu programa debiera finalizar su ejecución sin solicitar ningún input durante ella (piensalo como las tareas pasadas).

**Comment by robertov1** [comment]
Gracias!

**Comment by vichoeq** [comment]
En todo caso si no eliminas las llamadas al watcher en tu solución, nosotros lo haremos :wink:
