### ISSUE TITLE
Duda sobre orden de la materia clara y oscura

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#243]
Lo que esta encerrado en negro es correcto o no? Gracias!

<img width="631" alt="Captura de Pantalla 2020-07-01 a la(s) 7 33 58 p  m" src="https://user-images.githubusercontent.com/37153534/86300770-f1f2c680-bbd1-11ea-8027-c200752275f4.png">

**Comment by arbiocanpion** [comment]
Hola @chocopiano !

Como tu bien indicas, no es correcto que suceda aquello en un acuario.

**Comment by chocopiano** [comment]
<img width="245" alt="Captura de Pantalla 2020-07-02 a la(s) 12 17 47 a  m" src="https://user-images.githubusercontent.com/37153534/86315975-9b00e780-bbf9-11ea-8775-90d30f9f2349.png">
 Ese caso tampoco sería correcto? Gracias!

**Comment by arbiocanpion** [comment]
@chocopiano  tampoco sería correcto.

**Comment by chocopiano** [comment]
aaa perfecto ahora entendí bien el enunciado! jajaja disculpa

**Comment by vichoeq** [comment]
Hola, el detalle que importa aquí es lo que en el enunciado aparece como "al llenarse un nivel de materia este debe llenarse **en todo su ancho**"

Basicamente si separas el acuario en filas, cada fila es o completamente materia oscura, o completamente materia clara.

Considerando eso, tu primer ejemplo tiene más errores:

![image](https://user-images.githubusercontent.com/5317897/86350871-5a24c500-bc31-11ea-8623-03dbe12122e0.png)

Saludos!
