### ISSUE TITLE
[Operation timed out] Interfaz gráfica no funciona

### ISSUE THREAD

**Issue by dasolari** [IIC2133-PUC/2020-1#244]
Hola! Estaba intentando probar la demo de la tarea, pero no me muestra la interfaz gráfica. Al parecer el programa se queda pegado al intentar ejecutar la función `Watcher.open()` en el archivo `solver.py`. No he hecho ningún cambio en el código, tengo PyQt5 instalado y clone el repositorio de nuevo, pero nada funciona.
El error que muestra es:
<img width="1027" alt="Screen Shot 2020-07-02 at 11 18 41" src="https://user-images.githubusercontent.com/42161460/86377021-cca79c00-bc55-11ea-8089-765eb0196843.png">

**Comment by vichoeq** [comment]
Cual es tu sistema operativo?

**Comment by dasolari** [comment]
macOS X

**Comment by vichoeq** [comment]
El problema es que no está logrando establecer la conexión entre tu programa y la ventana. Se me ocurren dos cosas:

* el puerto 12345 está en uso. No se si daría time out pero puedes probar cambiando el puerto por otro. Linea 22 de `src/watcher/updater.py` y linea 43 de `src/watcher/watcher.py`

Puedes revisar que puertos están en uso con https://support.apple.com/lt-lt/guide/mac-help/mchlp1710/mac

* la conexión está siendo bloqueada por tu firewall. Al menos windows tira una advertencia al intentar conectarlos por primera vez, no se como funciona mac al respecto.

**Comment by dasolari** [comment]
Era el firewall, muchas gracias!
