### ISSUE TITLE
Instrucciones Examen

### ISSUE THREAD

**Issue by vichoeq** [IIC2133-PUC/2020-1#245]
### Estimados, aquí están las instrucciones del examen

* El examen es el miércoles 8 a las 9:00. Tienen plazo hasta las 15:00 del mismo dia para entregar
* De 9:00 a 10:00 habrá una sesión de consultas por zoom. Si tu pregunta puede dar la respuesta a otros alumnos, envíala por un canal privado.
* Se habilitará una issue de dudas frecuentes. Cualquier duda que tengas, revisa si ya fue contestada ahi y si no agregala como comentario. Los ayudantes trataremos de responder lo más rápido posible.
* El examen consta de 4 preguntas. **Deberán contestar solo 3**. Estas preguntas son:
    * Algoritmos codiciosos y MST (Prim, Kruskal, Conjuntos disjuntos)
    * Programación dinámica (Problemas varios, Bellman-Ford,  Floyd-Warshall)
    * Árboles Rojo-Negro
    * Otra materia del curso (sorpresa!)
* El examen tiene su propia nota, es decir estas preguntas no se mezclan con las demás.
* La entrega es por el cuestionario en SIDING. Se habilitará un cuestionario para cada pregunta para poder distribuir facilmente la corrección. Si entregan 4 preguntas se eligirá arbitariamente cuales 3 corregir (no entreguen 4 preguntas)

### Aplican las demás reglas de las pruebas anteriores:

* El examen considera que tienen acceso a internet, libros y clases. Si van a usar este material, **expresenlo en sus propias palabras.**
* El examen es individual. No esta permitido preguntar ni responder acerca del examen a nadie que no sea parte del cuerpo docente del curso.
* El examen está diseñado para responderlo en 2 horas.

* Los ayudantes iremos respondiendo las dudas tan rápido como podamos durante todo el horario.
* El formato de entrega es por PDF. Puede contener lo siguiente:
    * Texto digital (Word, Latex)
    * Texto escrito a mano (por favor que la letra sea clara)
    * Algoritmos y diagramas *dibujados* en papel. (Edit: Herramientas digitales son bienvenidas, si quieren tomarse el tiempo)
    * Usar Scanner o aplicaciones de celular como CamScanner para digitalizar lo que hagan a mano. **Evitar fotografías.**

Saludos y éxito en el examen.
Vicho

**Comment by VicenteMerino** [comment]
Hola, en caso de que nos de el tiempo podemos contestar las 4 y que se consideren las mejores 3? O debemos explicitar cuáles queremos que nos revisen?

Saludos

**Comment by vichoeq** [comment]
@VicenteMerino los ayudantes no tienen tiempo para corregir 4 preguntas. Repito: si entregas 4 se eligirá arbitrariamente cuales 3 corregir. **La otra no se corregirá ni se podrá recorregir (se considerará como no entregada)**

**Comment by JoseAvanzada2019** [comment]
hola, puedo enviar mi examen completo por 3 cuestionarios? Tengo las preguntas enumeradas

**Comment by vichoeq** [comment]
Tu dices para cada cuestionario meter el examen completo? Supongo que sirve, la idea de tener cuestionarios separados es poder saber rapidamente cuantas respuestas hay de cada pregunta para distribuir la corrección.
