### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by tamaralues** [IIC2133-PUC/2020-1#25]
Hola,  no logro entender muy bien la parte del enunciado donde dicen;
"Luego, N lineas, donde la i-esima linea indica la cantidad Pi de puertas que tiene el terminal i".
Yo entiendo que (usando el ejemplo del enunciado) el terminal  0 tiene 2 puertas y que en el terminal 1  tiene 8? Es así?

**Comment by Arcoirisky** [comment]
No soy ayudante pero si el archivo dice algo como lo siguiente, sería:

2 // cantidad de terminales 
3 // 3 puertas para el primer terminal (i=1)
1 // 1 puerta para el segundo terminal (i=2)
INGRESAR ....
....
END
 
Creo que es lo mismo que dices :0 yo lo hice así y me dio todo

**Comment by santilaguna** [comment]
Confirmo, es como señala Arcoirisky
