### ISSUE TITLE
[T3] Correr tests en bash

### ISSUE THREAD

**Issue by cchauriye** [IIC2133-PUC/2020-1#252]
Hola!

¿Hay alguna manera simple de correr todos los test de una? Intenté hacer un script con _bash_ según lo que vi en internet pero no lo logré 😄 .

Gracias!

**Comment by VicenteMerino** [comment]
for i in {0..19}; do python3 src/solver.py tests/lunatic_$i.txt out/lunatic_$i.txt; don
Yo use ese comando, debes ir cambiando el lunatic por normal, dificil y facil

**Comment by cchauriye** [comment]
Gracias!!!

**Comment by caespinoza5** [comment]
¡Hola!

Pueden usar este comando: 
```bash 
for j in facil normal dificil lunatic;do for i in {0..19}; do echo $j\_$i.txt; time python3 src/solver.py tests/$j\_$i.txt out/lunatic_$i.txt; done; done
```

Espero que les sirva 😄
