### ISSUE TITLE
Cython - Qué subir T3

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#253]
Hola, estaba viendo el uso de Cython y me di cuenta que al hacer el setup, se origina un archivo C y al parecer para correr la tarea, ya no es necesario el código de Python, sino que solo este archivo, así que me queda la duda qué subir. Solo el solver.py y el archivo .c generado con Cython necesario para compilar la tarea?

**Comment by VicenteMerino** [comment]
Revisando bien, creo que lo que debería subir es el archivo .so, no el .c no se si eso es así?

**Comment by vichoeq** [comment]
Lo importante es estructurar tu programa de manera de poder ejecutarlo con el comando de Python3.

**Comment by VicenteMerino** [comment]
Gracias!
