### ISSUE TITLE
[Tarea 3]: Data Classes

### ISSUE THREAD

**Issue by kylevon** [IIC2133-PUC/2020-1#254]
¿Está permitido usar Data Classes?
 https://docs.python.org/3/library/dataclasses.html

pregunto porque es un feature que apareció en python 3.7 y no está en python 3.6.

De manera más general, ¿podemos usar todos los features nativos de python 3.7? ¿3.8? ¿3.9?

¡Gracias!

**Comment by vichoeq** [comment]
Hola, perdona que me haya demorado tanto en responder. ¿Qué hiciste al final?

**Comment by kylevon** [comment]
No lo usé, igual al parecer es marginal la mejora. No te preocupes! 😊
