### ISSUE TITLE
Soluciones alternativas

### ISSUE THREAD

**Issue by kylevon** [IIC2133-PUC/2020-1#255]
Hola, en el puzzle dificil_1.txt obtuve una solución alternativa:

![image](https://user-images.githubusercontent.com/46159219/87112535-1554eb80-c23a-11ea-96ed-56d970b00bbc.png)

El archivo de la izquierda es mi solución y el de la derecha es el que estaba en los tests. 

¿Se van a considerar estas soluciones alternativas en la evaluación?

Saludos,

Kyle.

**Comment by caespinoza5** [comment]
Citando el anuncio,

> Es importante recalcar que la solución de un puzzle puede NO ser única, y por lo tanto nuestra solución puede no ser la misma que la suya.

**Comment by kylevon** [comment]
¡Oh, lo siento por no ver eso! ¡Gracias!
