### ISSUE TITLE
Letra ^M (carriage-return character) en soluciones

### ISSUE THREAD

**Issue by kylevon** [IIC2133-PUC/2020-1#256]
En los archivos de solución hay un ^M en el output de esas soluciones. ¿Podemos usar: 
```diff -b```
 para ignorar esa diferencia cuando revisamos los resultados?

**Comment by vichoeq** [comment]
Recuerda que no se va a revisar igualdad de resultados (por lo tanto tampoco se va a revisar igualdad de archivos), ya que las soluciones no son únicas.

Pero si quieres revisar si son la misma, usa el comando que prefieras.

**Comment by kylevon** [comment]
Ok, gracias!
