### ISSUE TITLE
Duda Bonus [T3]

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#257]
Hola! quería saber si a pesar de no cumplir en el tiempo con algún test dicifil igual puedo acceder al bonus con los test lunatic. Lo anterior es que hay un test dificil (él 5) que se demora infinito y sin embargo hay test lunatic que me corren en menos de 10 segundos. Gracias!

**Comment by vichoeq** [comment]
Si, todos pueden participar del bonus. Advierto si que los tests que se usaran para la correccion no serán los mismos que les pasamos.
