### ISSUE TITLE
[ T4 ] Archivo test.zip dañado.

### ISSUE THREAD

**Issue by Nico-gf** [IIC2133-PUC/2020-1#259]
Al bajar el zip mi computador me dice que esta dañado. Intente bajarlo de varias maneras siempre con el mismo resultado.

**Comment by caespinoza5** [comment]
¡Hola!

Acabamos de subir el archivo .zip en Siding > Material Tareas. Me comentas por favor si descargándolo desde ahí te funciona.

**Comment by Nico-gf** [comment]
Ahi si. Graciaas
