### ISSUE TITLE
Duda Output Valgrind en Taller 0

### ISSUE THREAD

**Issue by NicolasCastillo24** [IIC2133-PUC/2020-1#26]
Hola! Estaba probando valgrind y viendo el output al correr 6_memoria.
Recibo los Invalid write, Invalid read y Uninitialized Value pero este ultimo ademas entrega 3 otros errores extra que dicen "Conditional jump or move depends on uninitialised value(s)", los 3 producidos por el Uninitialized Value.
Queria confirmar si este aviso es porque al correr J[3] (linea 107), C lo ve como (J+3) y avanza por J, pasando por "espacios/bloques" (?) que no han sido definidos? (J[1], J[2], J[3])? Y si es asi, J[0] no levanta el error porque se define automaticamente al inicializar J con malloc? o ando muy perdido?

**Comment by vichoeq** [comment]
> Recibo los Invalid write, Invalid read y Uninitialized Value pero este ultimo ademas entrega 3 otros errores extra que dicen "Conditional jump or move depends on uninitialised value(s)", los 3 producidos por el Uninitialized Value.

El "Conditional jump or move depends on uninitialised value(s)" aparece cuando estás haciendo una decisión (if, for, while, etc) en función de una variable que no ha sido inicializada. En particular, va a aparecer siempre que trates de hacer print de una variable no inicializada (la función printf hace muchas cosas por detrás)

> Queria confirmar si este aviso es porque al correr J[3] (linea 107), C lo ve como (J+3) y avanza por J, pasando por "espacios/bloques" (?) que no han sido definidos? (J[1], J[2], J[3])? Y si es asi, J[0] no levanta el error porque se define automaticamente al inicializar J con malloc? o ando muy perdido?

Estás al revés. **Definir** una variable significa decir que existe. **Inicializarla** es darle un valor (por primera vez). El ejemplo que queremos mostrar acá es que pasa cuando una variable está definida y no inicializada: todas las variables vienen sin inicializar por defecto. J es un arreglo de 10 celdas, por lo que todos los J[i] con i = 0 ... 9 están **definidos**, pero no inicializados.

**Comment by vichoeq** [comment]
J[3] es un solo elemento, no estás tocando  J[0] ni J[1] ni J[2]. Efectivamente, estás recibiendo los 3 errores por el print. Prueba comentarlo y verás.

**Comment by jcechavarri** [comment]
Hola @vichoeq !

Esta advertencia no es considerada para la Tarea 0, cierto?
