### ISSUE TITLE
Recorrecciones Tareas

### ISSUE THREAD

**Issue by isavega** [IIC2133-PUC/2020-1#260]
Hola! Como ya han mencionado antes,  el plazo de recorrección de tareas está abierto el 20 de julio a las 23.59.  Dado eso tengo unas preguntas:

- Donde mando mi solicitud de recorrección?
- Si quiero mandar a recorregir X tarea modificando algo pequeño, tengo que explicar que cambie y por qué? 
- Si quiero modificar algo más significativo en el código, cual es el criterio para saber el eventual descuento asociado? Existe un máximo de lineas que pueda modificar o algo así? (Teniendo claro que debo usar mi código original y no es el fin hacer la tarea de nuevo). 
-  En resumen, si modifico cualquier cosa, tengo que subir los cambios al mismo repositorio que me asignaron para la tarea X? Basta solo con lo evidenciado en el commit? 

Muchas gracias 😄

**Comment by caespinoza5** [comment]
¡Hola! En primer lugar, aclarar que tan solo el período de recorrección de la tarea 0 está abierto hasta el 20; el de la tarea 2 vence hoy (lunes 13) a las 23.59. Luego, citando el anuncio:

> 1. Deben abrir un issue en el repositorio de su tarea solicitando formalmente recorregir su tarea 0 y explicando por qué. Si hacen cambios en su código, deben indicar qué cambiaron y qué commit quieren que se revise. Tal como se explicó hace un par de anuncios, si estos cambios no cambian la lógica de su algoritmo, no llevan asociado descuento. En caso contrario, hay un descuento aplicado en proporción a la cantidad de cambios que hagan a su algoritmo.
>
>2. Deben enviar el link de dicha issue a caespinoza5@uc.cl con el encabezado [IIC2133] - Recorregir T0 - [Su nombre]. Ejemplo: [IIC2133] - Recorregir T0 - Juan Perez.
>
>Antes de enviar una solicitud de recorrección, favor asegurar:
>- Revisar en detalle la siguiente [issue](https://github.com/IIC2133-PUC/2020-1/issues/62). En particular, revisar la sección de cómo comprobar si su código es correcto.
>- Seguir el formato de impresión en consola establecido en el enunciado.
>- Que su tarea compile correctamente al ejecutar "make clean" y luego "make" en su repositorio.
>
>Los tests utilizados para la corrección se encuentran disponibles en Siding > Material Tareas > Tests Evaluación T0.

Por lo tanto, al modificar cualquier cosa efectivamente debes subir los cambios al repositorio de la tarea; favor subir todos los cambios de la recorrección en tan solo un commit, para así poder comparar lo nuevo con lo antiguo más fácilmente.

>¿cuál es el criterio para saber el eventual descuento asociado?

Esto se ve caso a caso, por lo que no puedo darte una respuesta concreta; sin embargo, cambios pequeños en la lógica del algoritmo no debieran llevar un descuento sobre 5 décimas o 1 punto, mientras que cambios más significativos pueden tener mayor descuento. Tal como planteas, la idea no es hacer la tarea de nuevo desde 0.
