### ISSUE TITLE
[T4] Orden de input 

### ISSUE THREAD

**Issue by Bizama** [IIC2133-PUC/2020-1#261]
Hola! Tenía una duda con respecto al input que nos entregan 
por ejemplo si tengo una fila que me dice 
0 4 3 significa que de 0 (que sería un punto de riego ) a 4 (que sería una fuente de agua) vale 3 
es válido que lo ponga en una matriz al revés? 

es decir, tener Matriz[0][4] = 3 y Matriz[4][0] = 3 

Gracias!

**Comment by vichoeq** [comment]
Hola, 

> 0 4 3 significa que de 0 (que sería un punto de riego ) a 4 (que sería una fuente de agua) vale 3

recuerda que el enunciado dice que eso significa que el punto 4 y el punto 0 **están conectados** con una cañería de costo 3, no hace referencia a que la conexión vaya "de un lado para el otro"

> es válido que lo ponga en una matriz al revés?

Modela el problema como tú quieras, mientras tu algoritmo sepa lo que significa cada cosa :)
