### ISSUE TITLE
judge.py no funciona

### ISSUE THREAD

**Issue by IngisRedd** [IIC2133-PUC/2020-1#262]
Conseguí una solucion "solve.py" para la tarea 4 que obtiene correctamente los resultados para los tests si aplico el comando de forma manual:
 python3 solve.py tests/test_XX.txt outputXX.txt

Pero al momento de correr "judge.py" me devuelve RUNTIME ERROR para todos los test:

![image](https://user-images.githubusercontent.com/39068534/87725311-e70f6880-c771-11ea-84c1-de1c46704161.png)

Puede ser que tenga algún problema con judge.py o con mi versión de python (Tengo la 3.8.2)?

**Comment by IngisRedd** [comment]
Se me olvidó aclarar que el programa corrector me devuelve RUNTIME ERROR para  todos los tests de manera inmediata, sin esperar 10 segundos para cada uno.

**Comment by vichoeq** [comment]
El judge entrega RUNTIME ERROR si tu programa se cae o termina con un código de salida distinto de 0 (al igual que en C).

Que se imprime en consola cuando ejecutas tu programa? Quiero ver el comando entero.

**Comment by hbkim94** [comment]
Tuve este mismo problema, y tenía relación a los parámetros adicionales entregados a `sub.process.call()`. 
```
Traceback (most recent call last):
  File "judge.py", line 21, in <module>
    python_run(command, timeout=10)
  File "judge.py", line 16, in python_run
    check=True
  File "/home/dae/.pyenv/versions/3.6.10/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
TypeError: __init__() got an unexpected keyword argument 'check'
```

**Comment by vichoeq** [comment]
Hm, perdon, yo estoy usando Python 3.8.3. Si es por eso entonces el RUNTIME ERROR es porque el judge.py se cayó :s 

@hbkim94 dice que lo que lo rompe es el argumento "check", asi que debería bastar con eliminar solo esa línea.

**Comment by vichoeq** [comment]
Pero si @IngisRedd esta usando Python 3.8.2 no debería ser ese el problema.

**Comment by IngisRedd** [comment]
Si commento "check" me funciona! Gracias! ¿Puedo entregar mi código tal como está (aunque haya que alterar judge.py para que funcione)? Y otra  cosa: ¿puedo usar código disponible en internet si lo cito?

**Comment by vichoeq** [comment]
> Si commento "check" me funciona!

Que raro eso, el parametro check es algo que está hace muchas versiones... :man_shrugging: 

> ¿Puedo entregar mi código tal como está?

Si, nosotros no vamos a tocar el judge.py. 

> ¿Puedo usar código disponible en internet si lo cito?

Si. Nadie va a leer tu código, pero si alguien más usa ese código va a ser detectado como copia, asique es bueno tener el respaldo por si llega a pasar.

Saludos
