### ISSUE TITLE
[T4] Número de aristas de cada test

### ISSUE THREAD

**Issue by hbkim94** [IIC2133-PUC/2020-1#263]
¡Hola! ¿Podemos asumir que el grafo de cada test es completo, tal y como se definió en el examen?

De antemano muchas gracias.

**Comment by vichoeq** [comment]
Puedes asumir muchas cosas, y esas cosas pueden o no ser correctas. Lo que estás asumiendo, ¿se cumple para los ejemplos? 
Y, si se cumple para los ejemplos, ¿se cumple para todos los tests?

**Comment by hbkim94** [comment]
Voy a interpretar tu respuesta como un "no, no puedes asumirlo". Gracias :joy:
