### ISSUE TITLE
[T4] no entregar

### ISSUE THREAD

**Issue by michimalonko** [IIC2133-PUC/2020-1#265]
Hola cree el repositorio, pero al final no haré la tarea, para que no se contabilice en las notas tengo que hacer algo? o simplemente no se considerara a pesar de que haya creado el repo?

**Comment by vichoeq** [comment]
Hola, te recomiendo que veas como se calcula la nota de tareas: #210 

O como decía el anuncio que les llegó a sus correos:

> Recuerden que esta tarea es opcional: en caso de hacerla, su nota de tareas sería el promedio de las 5 tareas (pero si les baja el promedio no la contaremos).

**Comment by michimalonko** [comment]
gracias!
