### ISSUE TITLE
Duda indices de terminales y puertas [Tarea0]

### ISSUE THREAD

**Issue by lothardp** [IIC2133-PUC/2020-1#27]
Al ocurrir uno de los eventos cierre o clausura, las puertas o terminales restantes mantienen su indice?
Por ejemplo si el terminal 1 tiene 5 puertas y se cierra la puerta 2, ¿las puertas 3 y 4 se "trasladan" a las posiciones 2 y 3 o mantienen sus indices 3 y 4 y simplemente  ya no existe una puerta 2? Misma pregunta si se clausura un terminal. Asumo que si se mantienen los indices pero no estoy 100% seguro.
Graciass

**Comment by jeschuwirth** [comment]
Hola @lothardp,

Efectivamente mantienen sus índices :)

Éxito!
