### ISSUE TITLE
Output con y sin valgrind son diferentes

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2133-PUC/2020-1#28]
Hola, hay alguna razón por la que el output de mi programa sea diferente cuando lo corro con valgrind que cuando lo corro sin?
(el output esperado me aparece con valgrind)

**Comment by jeschuwirth** [comment]
Hola @nrrosenberg,

Valgrind no debería afectar el comportamiento de tu código. ¿Puedes mostrar un pantallazo de los distintos out.txt para checkear cual puede ser el error?

**Comment by nrrosenberg** [comment]
La segunda imagen es con valgrind, la diferencia se da en el primer gate number del terminal 0. Lo que quería hacer era printear el número de puerta de todas las puertas de cada terminal, pero cuando me paso de las 3 puertas en un terminal, el valor de la primera puerta se cambia por un número largo que cambia cada vez que lo corro sin valgrind. De hecho, cuando son muchas puertas por terminal, se cambian más valores por números largos. Cuando lo corro con valgrind obtengo el resultado esperado






<img width="1021" alt="Captura de Pantalla 2020-04-07 a la(s) 23 48 51" src="https://user-images.githubusercontent.com/42253078/78742602-85e22880-792a-11ea-92f7-c02fde0a6ba9.png">
<img width="532" alt="Captura de Pantalla 2020-04-07 a la(s) 23 51 55" src="https://user-images.githubusercontent.com/42253078/78742719-cb9ef100-792a-11ea-802f-6535fed7849c.png">

**Comment by VicenteMerino** [comment]
Hola @nrrosenberg al final descubriste por qué te pasaba esto?

**Comment by arbiocanpion** [comment]
@nrrosenberg viendo tu problema, lo que puede suceder, es lo que indica @vichoeq  en la issue #64, este problema sucede porque Valgrind corre tu programa en un ambiente diferente, pero ademas Valgrind al ejecutar tu programa lo hace de un modo seguro, es decir, en algunos casos Valgrind nota una corrupción de memoria e impide que eso suceda. Por esta razón es que tu programa corre en Valgrind, pero no en modo normal, porque realmente si tiene un memory leak que produce segmentation fault, pero da el caso que Valgrind es capaz de suprimir esa secuencia.
Te recomendaria volver a ver el código, poniendo especial atención en los mallocs que tengas (en especial dentro de los for's o while's), ademas de revisar el output que te da valgrind en el modo valgrind --leak-check=full. este output te indicara al final las lineas donde tu programa debe estar teniendo problemas.

**Comment by nrrosenberg** [comment]
ya lo pude arreglar, muchas gracias!!
