### ISSUE TITLE
Uso de Heap vs Stack

### ISSUE THREAD

**Issue by lothardp** [IIC2133-PUC/2020-1#29]
Holaa,
Los inputs "grandes" que menciona el enunciado que serán utilizados para testear la tarea, ¿son lo suficientemente grandes como para causar un overflow si solo utilizaramos la memoria del stack?
De otro modo no encuentro sentido en utilizar malloc() para pedir mas memoria, sabiendo que hacer esto varias veces además toma mas tiempo de ejecución.
Y otra duda, subiran ejemplos de estos inputs grandes para poder testear la tarea??
Graciass

**Comment by NicolasLahsen** [comment]
Hola @lothardp! No te preocupes por el overflow en el stack, es más importante que le des vuelta a tu código para ver la correctitud de este antes de ver la eficiencia. Con respecto a los tests, sí, se subirán archivos más complejos para que puedas testear tu código más adelante.
Espero haberte ayudado,
Saludos!
