### ISSUE TITLE
Maquina Virtual - Instalación de Ubuntu en VirtualBox

### ISSUE THREAD

**Issue by isiguelfand** [IIC2133-PUC/2020-1#3]
Hola
Hace un par de días estoy tratando de instalar Ubuntu en VirtualBox, pero siempre entre el paso 8 y 10 de la Wiki (entre "preparar para instalar Ubuntu" y "eliminar disco") la máquina virtual se queda pegada y/o el mouse deja de funcionar dentro de ella. Tengo porcentaje de la memoria de video asignada y además intenté aumentando el número de monitores CPU. La aceleración 3D está deshabilitada (estas fueron las soluciones propuestas que encontré). También he intentado con distintas configuraciones de instalación de Ubuntu. recomienda alguna alternativa a Ubuntu?
Mi sistema operativo es Mac y tuve el mismo problema con kali linux. 
Muchas gracias!

**Comment by yerkko** [comment]
Si el problema te pasa en más de una distro, puede ser un problema de ownership del mouse de VirtualBox.
Intenta revisar este thread que encontré 
https://askubuntu.com/questions/592055/mouse-doesnt-work-in-the-guest-os-ubuntu-14-04-2-on-virtual-box-installed-on

De todas formas, si quieres una recomendación de distribución, Linux Mint y ElementaryOS son buenas alternativas para comenzar. Kali se usa más para seguridad informática.

**Comment by vichoeq** [comment]
Hola @isiguelfand , sigues teniendo este problema? Podríamos coordinar un hangouts con uno de los ayudantes para ayudarte a resolverlo.

**Comment by isiguelfand** [comment]
Hola!
Lo hice con parallels al final! Muchas gracias.
