### ISSUE TITLE
Formato Informe

### ISSUE THREAD

**Issue by InfiniteDreamX** [IIC2133-PUC/2020-1#30]
Hola,

El informe de la tarea 1 debe ser en algun formato especifico ? (markdown, latex, etc) 
Se puede hacer en lapiz y papel y escanearlo?

**Comment by yerkko** [comment]
Mientras sea pdf y no esté a mano (please 🤔), está bien. De necesitar añadir algún gráfico o dibujo, estos pueden ser fotos adjuntas en el archivo, pero el texto debe estar typeado. Si usas latex, Word, markdown, etc para llegar a este pdf es elección tuya. Si quieres usar latex, acá hay un template que recomiendo, pero su uso no es obligatorio 
https://github.com/open-source-uc/IIC1253-template
