### ISSUE TITLE
Hangouts con ayudante

### ISSUE THREAD

**Issue by cchauriye** [IIC2133-PUC/2020-1#31]
Hola! Podría pedir un hangouts para que me ayuden a configurar mi computador? Es un mac al que le instalé Parallels.

Gracias!

**Comment by nigfasa** [comment]
Estimad©, no hay ningun problema. Envie un correo nifaconi@uc.cl y le enviaré un link del hangout y las horas de disponibilidad. Vamos a settear Parallels, instalar ubuntu (windows necesita mayor cantidad de requerimientos) y seguir los pasos de la guia normal.
