### ISSUE TITLE
Código en main.c

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2020-1#32]
Hola! Estoy un poco perdido en cómo tenemos que enfrentar la tarea y qué se espera que seamos capaces de hacer. El código base de la tarea básicamente lee el input y imprime su información, dónde debemos nosotros escribir código? tenemos que crear nuestras estructuras de datos y la funciones para procesar los eventos? 
Disculpen, es que esta Tarea 0 está bien diferente a la de otros semestres.
Gracias y saludos!

**Comment by arbiocanpion** [comment]
Hola @fabarros!
Sobre tu primera duda, lo que se espera de ustedes en esta primera tarea es que construyan su propia estructura de datos que les permita resolver de manera satisfactoria el problema propuesto.
La idea del código base es orientarlos y que ustedes rellenen en los espacios comentados la incialización/interaccion, etc. de sus estructuras con el programa. Espécificamente en el archivo main.c hay algunas lineas (la 21, 28, 48,56, 64, 72, 80 y 87) en donde esta comentado lo que se recomienda que ustedes escriban. Por ejemplo en la linea 21 seria recomendable que hagas el init de tu estructura de datos que usaras para guardar las puertas.
Respecto a tu segunda pregunta, si, ustedes deben crear sus propias estructuras de datos para esta tarea, pero tienes a tu disposicion el material de los talleres que les hemos entregado para que lo tomes como inspiración sino, siempre puedes buscar algo en lo que te puedas basar o inspirar.(Te recomendaría fuertemente revisar el taller 0 la carpeta 7_structs).
Para ir cerrando, cualquier duda que tengas no dudes en hacerla llegar a los ayudantes a traves de este medio y mucho ánimo, pasar de Python a C es un poco rudo a veces, pero no te desanimes!, solo hay que dedicarle tiempo y tener paciencia.

**Comment by fabarros** [comment]
Entiendo.
Muchas gracias!
