### ISSUE TITLE
Ayudantía viernes 3 de abril

### ISSUE THREAD

**Issue by rodobkn** [IIC2133-PUC/2020-1#33]
Hola!

Quisiera saber donde se encuentra el video de la ayudantia del viernes 3 de abril. Sólo encuentro el enunciado.

saludos!

**Comment by yerkko** [comment]
Hello, están en el readme

[Ayudantías](https://github.com/IIC2133-PUC/2020-1/tree/master/Ayudant%C3%ADas)
