### ISSUE TITLE
Duda pods

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#34]
Hola no entiendo bien como va escalando el indice de pods: Está asociado a cada puerta en particular y va escalando cuando hay un abordaje nuevo, o va escalando segun llegan pods al terminal, o al titanic y estan asociados a uno de estos?

Saludos

**Comment by jeschuwirth** [comment]
Hola!

El ID de cada pod va asociado con cada puerta y cada terminal, por lo tanto el primer pod que sale de la puerta 0 del terminal 0 tiene id 0, si luego de ese sale el primer pod de la puerta 1 del terminal 0, entonces su ID también es 0 ya que es el primero de esa puerta.

Te dejo un ejemplo de input y output por si quedaron dudas :)

Input.txt
```
1
2
INGRESO 0 1 0
INGRESO 0 2 0
INGRESO 0 3 0
INGRESO 0 4 0
INGRESO 0 5 0
INGRESO 0 6 0
INGRESO 0 7 0
INGRESO 0 8 0
INGRESO 0 9 0
INGRESO 0 11 0
INGRESO 0 22 0
INGRESO 0 33 0
INGRESO 0 44 0
INGRESO 0 55 0
INGRESO 0 66 0
INGRESO 0 77 0
ABORDAJE 0 0
ABORDAJE 0 1
END
```


Output.txt
```
POD 0 0 0
1 0
3 0
5 0
7 0
9 0
22 0
44 0
66 0
POD 0 0 1
2 0
4 0
6 0
8 0
11 0
33 0
55 0
77 0
```

Éxito!

**Comment by Arcoirisky** [comment]
por qué el outpud de los pod es el id del ente y el tipo?
En el enunciado salía que es sin tipo

**Comment by Arcoirisky** [comment]
también creo que el formato para los PODs es terminal, puerta, id_pod
entonces el segundo output sería
POD 0 1 0

Quiero asegurarme de estar imprimiendo bien según el enunciado ;----; perdón por molestar

**Comment by jeschuwirth** [comment]
D:

No molestas en absoluto, son dudas muy muy válidas.

Tienes razón en ambos casos, el output que entregué fue con una pauta antigua de la tarea y no estaba actualizada al enunciado.

El output correcto sería:
```
POD 0 0 0 LOG
1
3
5
7
9
22
44
66
POD 0 1 0 LOG
2
4
6
8
11
33
55
77
```

Felicidades por estar tan atenta a las issues :DD
