### ISSUE TITLE
cierre puerta

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#35]
Hola, en el enunciado no se describe la lógica con la que ingresan los pasajeros de una puerta que se cierra. Debo asumir que es por orden de llegada en esa puerta, eligiendo prioritariamente?

**Comment by jeschuwirth** [comment]
Hola @VicenteMerino,

Los pasajeros reingresan a la terminal en el mismo orden que estaban en la cola, el pasajero que estaba en la posición 0 de la cola (más cerca de la puerta) entra primero al terminal y así.

Si te quedan dudas sigue comentando en esta issue :)
