### ISSUE TITLE
Duda estructuras de datos Tarea0

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#36]
Hola,

Estoy medio complicado con la tarea y estuve estudiando un poco de C, para entender mejor como funcionan los structs. Y pense en que se podrian modelar las terminales y las puertas como arrays de punteros dado que tienen un largo que se puede determinar antes de crearlos. Por otra parte solo quedaria por definir las estructuras de las colas que pense podrian ser una lista ligada que contuviera un estilo de "clase" para guardar el tipo y id de cada niño, adulto o robot. Esto esta mas o menos bien? o sigo muy perdido?

Ademas, estaba pensando que seria mas eficiente, crear una estructura de datos para la lista que parta con cierto largo y cuando se termine el espacio usar realoc para aumentar la memoria, o definir otra estructura y concetarla con un puntero a la nueva estructura?

Muchas gracias!

**Comment by Arcoirisky** [comment]
No sabría decirte si está bien responder a esto, no soy ayudante, pero hice algo similar a lo que dices y me funcionó bien O: 

Lo que si te sugiero es que vayas de a poco, yo empecé mi lucha con los terminales y las puertas. Luego que eso funcionara bien le fui metiendo personas y las funciones respecto a estas. así si algo me explotaba, tenía la base de que lo anterior estaba bien y solo debía concentrarme en lo nuevo que estaba agregando.

Un lápiz y papel también ayudan xD En mi caso el duelo de -> que tenía era impresionante

**Comment by yerkko** [comment]
Hola @danustilovsky , me podrías mandar dar tu dirección de email o enviar un correo a yachavez@uc.cl por favor?

No es nada serio, sólo preferiría continuar en privado 🤔
