### ISSUE TITLE
Prints base

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#37]
Hola, para poder entregar el output que nos piden entonces deberiamos borrar los printf que venian en el codigo base?

**Comment by caespinoza5** [comment]
¡Hola!

Así es. Los prints del archivo base son para guiarlos un poco con respecto a lo que está haciendo el programa al leer el input; sin embargo, el output debiese ser tal como lo menciona el **enunciado**.
