### ISSUE TITLE
Duda merge sort

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#38]
Hola, me quedó una duda con un resumen de la complejidad y no entendí por qué en merge sort la complejidad es O(n) para la memoria adicional. Y como puedo, en general, ver cuanto es la memoria adicional que pide un algoritmo?

Saludos

**Comment by Arcoirisky** [comment]
Hola! 
No soy ayudante ni nada pero yo lo entendí de esta forma:

Merge por definición termina usando una lista C adicional que termina trabajando bajo el orden O(2n) = O(n) del Merge. 

Sin importar el n de las listas A y B terminamos trabajando siempre con una memoria adicional O(n) al usar Merge.

Entonces, como MergeSort hace uso de este Merge que definimos en clases, podemos decir que usa esta memoria adicional del orden O(n)

Todo porque no podemos trabajar sobre una misma lista al juntar dos diferentes u-u (problema que creo que se resuelve con el último método de ordenación que vimos)

**Comment by Arcoirisky** [comment]
Si me equivoco aiua >->)

**Comment by Kitaps** [comment]
Así es :D
