### ISSUE TITLE
Almacenamiento de arrays en Heap y Stack: error de acceso en dirección de memoria

### ISSUE THREAD

**Issue by viantirreau** [IIC2133-PUC/2020-1#39]
Hola!

Tengo una duda sobre un problema que, afortunadamente, ya logré resolver, pero no entiendo por qué mi primer _approach_ no funcionaba. Tengo un `struct` para representar los terminales y, dentro de ellos, un atributo que guarda los punteros hacia cada puerta.
En mi primer intento, la función que crea el terminal se veía algo parecido a esto:
```C
Terminal *new_terminal(int id, int gate_count)
{
    Terminal *terminal = malloc(sizeof(Terminal));
    //... seteo otros atributos irrelevantes para el ejemplo
    // declaro la variable gates como un array (en stack?) de punteros a Gate
    Gate *gates[gate_count]; 
    for (int i = 0; i < gate_count; i++)
    {
        gates[i] = new_gate(i);
    }
    terminal->gates = gates;
    return terminal;
}
```
Con ese código, me estaba dando un SEGFAULT ya que, de alguna forma inexplicable, el primer elemento del array `gates` primero apuntaba a una dirección válida del tipo Gate, luego llamo a una función que agrega un pasajero en alguna puerta del terminal, y cuando vuelvo de esa función, el primer elemento de `gates` ahora apunta a 0x1, por lo que el programa se caía en la siguiente iteración.

Sin hacer absolutamente ninguna otra modificación en el código, con solo cambiar la función de `new_terminal` por algo como lo que sigue, ya funcionaba sin caerse :thinking:

```C
Terminal *new_terminal(int id, int gate_count)
{
    Terminal *terminal = malloc(sizeof(Terminal));
    //... seteo otros atributos irrelevantes para el ejemplo
    Gate **gates = malloc(gate_count * sizeof(Gate *));  // Único cambio!
    for (int i = 0; i < gate_count; i++)
    {
        gates[i] = new_gate(i);
    }
    terminal->gates = gates;
    return terminal;
}
```
¿Esto es esperable/explicable? ¿Será que al guardar los punteros de Gate en un _array_ en _stack_, al salir del _scope_ se saca del _stack_ y pierdo sus referencias?

Agradezco cualquier iluminación!!

**Comment by Arcoirisky** [comment]
Según yo, es lo que vimos en el taller de punteros. Específicamente la parte de:

Si X es un puntero que apunta a una variable de tipo T, entonces el tipo X es T*.

Por lo tanto, el tipo de:
*(T{n asteriscos}) = T{n-1 asteriscos}

**Comment by viantirreau** [comment]
Puede ser! 
Lo extraño es que en mis _header files_ definí que el atributo gates del `struct Terminal` es de tipo `Gate**` y no hubo errores ni warnings durante la compilación, con ambos mecanismos para guardar las referencias a las puertas. También es extraño que alcanzaba a ejecutarse una vez y recuperaba bien todos los atributos de `terminal->gates[0]`, así que me parece que tenía bien construidas las referencias 🤔. El problema surgía en la segunda llamada a una función que usaba esa información.

Gracias de todas formas!

**Comment by Arcoirisky** [comment]
O Quizas solo sea ** porque es un array de punteros. Onda el primer * para decir que es un array y el segundo de punteros. 

Y que te fallara en la siguiente ejecución puede ser que te leyera parte del primer elemento porque supongo que guardaba el elemento en vez del puntero al elemento 

O algo así 🤔 pero ya me estaría yendo por las ramas

**Comment by JohnTrombon** [comment]
Hola @viantirreau !  Tal y como dices, en tu primer approach declaras un arreglo en el stack y luego le pasas la referencia a tu struct, entonces al momento de retornar, tu función deja "disponible" la memoria que utilizó en el stack para que sea usada por el resto de tu programa, pudiendo perder los punteros almacenados en dicho arreglo (por más que estos últimos apunten al heap o a cualquier lado) . Para asegurar la persistencia de ese arreglo de punteros, es necesario ubicarlo en el heap tal como lo hiciste en tu segundo acercamiento.
Ahora, respondiendo a tu segundo comentario y las cosas que te parecieron extrañas: 

> Lo extraño es que en mis header files definí que el atributo gates del struct Terminal es de tipo Gate** y no hubo errores ni warnings durante la compilación, con ambos mecanismos para guardar las referencias a las puertas

En ambos mecanismos, lo que estás guardando en terminal -> gates es un arreglo de punteros, o equivalentemente, un puntero al primer elemento de dicho arreglo de punteros. Tu problema era que en el primer caso, ese puntero apuntaba a una posición de memoria en el stack, la cual es volátil. Pero en ningún momento se contradijo tu declaración de la struct, siempre a terminal -> gates le asignaste una variable con tipo Gate** y el compilador se mantuvo contento con eso.

> También es extraño que alcanzaba a ejecutarse una vez y recuperaba bien todos los atributos de terminal->gates[0], así que me parece que tenía bien construidas las referencias 

Mi teoría aquí es que este puntero apuntaba a una posición de memoria del stack que no alcanzó a ser sobrescrita por ningún otro pedazo de tu programa, entonces pudo recuperar correctamente el contenido del primer elemento de terminal -> gates.
Espero haberte ayudado!

**Comment by viantirreau** [comment]
Muchas gracias!! Fue muy clara tu explicación, te pasaste!

**Comment by viantirreau** [comment]
Dejo un link de referencia por si alguien más pasa por este problema!  🙌 
https://stackoverflow.com/a/35483568
