### ISSUE TITLE
Duda notación flecha vs punto

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2133-PUC/2020-1#4]
Hola, tengo duda con la notación que usan en el código de las matrices, usan un -> para asignar algo, pero no entiendo bien como funciona.

![image](https://user-images.githubusercontent.com/39094323/77125567-faf5c880-6a24-11ea-9d96-a340007e1b3a.png)

Además, que utilidad tiene declarar las funciones de las matrices en el archivo matrix.h si luego serán definidas en matrix.c?
Por último, por qué hay que pedir explícitamente memoria con malloc para la matriz, si cuando se pide memoria para cada fila de ella, implícitamente se está pidiendo la memoria necesaria para esta estructura?
Saludos, gracias por su tiempo.

**Comment by B-Dominguez** [comment]
Hola Ricardo, respondo en comentarios separados cada pregunta. Espero poder ayudarte y porfavor dime si algo no te queda claro.

> Hola, tengo duda con la notación que usan en el código de las matrices, usan un -> para asignar algo, pero no entiendo bien como funciona.
> 
> ![image](https://user-images.githubusercontent.com/39094323/77125567-faf5c880-6a24-11ea-9d96-a340007e1b3a.png)
> 

Escribir 'mat -> height' es el equivalente a escribir '(*mat).height'. Debes recordar que mat es del tipo '*Matrix', no del tipo 'Matrix'. Es decir, es un puntero a un objeto matriz, no el objeto mismo (Si esto no es claro revisa 4_punteros del taller 0). Por lo tanto, si quiero acceder al atributo 'height' del struct tipo 'Matrix', no puedo hacerlo como 'mat.height' [puntero.atributo]. Para facilitar este caso, que en C se da mucho, está la notación [puntero -> atributo], con la que podemos hacer 'mat -> height', que es equivalente a [(*puntero).atributo];  [loqueapuntaelpuntero.atributo]

**Comment by B-Dominguez** [comment]
> Además, que utilidad tiene declarar las funciones de las matrices en el archivo matrix.h si luego serán definidas en matrix.c?
Los archivos .h son los _header-files_, los .c para todo lo demás (el "contenido"). Así, los .h sirven para declarar funciones, structs y a veces variables para que sean visibles a otros módulos, cuyo funcionamiento o contenido se desarrollan en el .c . Esto es especialmente útil al momento de las importaciones ('#include ') y de la compilación. 
Al importar un módulo desde otro, por ej matrix a main, solo se importa matrix.h (y no matrix.c) a main.c . Además, si te fijas, al principio del .h se incluye (siempre) un '#pragma once', que significa que el archivo se compilará una sola vez. Así, se logran dos cosas. 

1. Al importar matrix.h desde main.c, solo se está importando la información justa que un archivo externo puede necesitar, y no todas las funciones, operaciones y variables internas que puedan haber en matrix.c
2. Se evita el error de que si importáramos matrix.c a main.c, matrix.c se compilaría dos veces (cuando el compilador pasa por el archivo main.c y cuando pasa por matrix.c)

Como bonus, permite una mejor legibilidad al humano y facilita mantener un orden estándar en el código.

**Comment by B-Dominguez** [comment]
> Por último, por qué hay que pedir explícitamente memoria con malloc para la matriz, si cuando se pide memoria para cada fila de ella, implícitamente se está pidiendo la memoria necesaria para esta estructura?

// Definimos el struct matriz
struct matrix
{
  /** La matriz en si: un arreglo de arreglos */
  int** matrix;
  /** El alto de la matriz */
  int height;
  /** El ancho de la matriz */
  int width;
};

**Comment by B-Dominguez** [comment]
> Por último, por qué hay que pedir explícitamente memoria con malloc para la matriz, si cuando se pide memoria para cada fila de ella, implícitamente se está pidiendo la memoria necesaria para esta estructura?

Lo que sucede, es que **la estructura no incluye las filas, las columnas y las entradas como atributos**, sino que incluye un puntero de punteros (`-> matrix`) a un arreglo que contiene punteros a filas, que a su vez (las filas) son arreglos de ints.
![image](https://user-images.githubusercontent.com/26129405/77192442-58d4ef80-6abb-11ea-86b1-75cd80db3db3.png)

Entonces cuando hago `Matrix* mat = malloc(sizeof(Matrix));`, estoy obteniendo espacio únicamente para el puntero de punteros `-> matrix` y para los ints '-> height' y '-> width'. 

Luego, cuando hago `mat -> matrix = malloc(height * sizeof(int*));`, estoy obteniendo espacio únicamente para el arreglo de punteros a filas. Notar que se usa height (número de filas) por sizeof(int*) (el tamaño en memoria de un **puntero** que apunta hacia ints, pero **no para los ints mismos**).

Por último, cuando hago  `mat -> matrix[row] = malloc(width * sizeof(int));`, estoy obteniendo espacio para los ints que van dentro de (apuntados por) cada fila.

Recuerda decirme si se te resuelven las dudas o te queda alguna!

**Comment by prochotito-rises** [comment]
Muchisimas gracias! Me quedó super claro todo
