### ISSUE TITLE
Solución Ayudantía 1

### ISSUE THREAD

**Issue by Oisangui** [IIC2133-PUC/2020-1#40]
Hola, podrían subir la solución de la ayudantía 1 por favor?
Gracias

**Comment by Arcoirisky** [comment]
Según yo, la solución de la ayudantía es el video!

**Comment by Oisangui** [comment]
En el video dijeron que tratarían de subir la solución a la brevedad.

**Comment by Arcoirisky** [comment]
Verdaaaad, recuerdo que me llego un mail con que se subió pero en vola era el video.

**Comment by Kitaps** [comment]
Hola, la ayudantía está subida desde ahora. 
Estaremos atentos para resolver sus dudas. 
Disculpen la demora. 
Exito estudiando para el examen ;D
