### ISSUE TITLE
Duda ayudantía 0 pregunta 1.2.

### ISSUE THREAD

**Issue by Fenho** [IIC2133-PUC/2020-1#42]
Hola, ¿Por qué se concluye que el tiempo de merge sort es theta(n*log(n)) si solo acotamos por arriba? ¿No debería solo pertenecer a O(n*log(n)) según el desarrollo?

**Comment by Arcoirisky** [comment]
Según yo, la cota mínima de ordenación es nlogn, entonces si tu cota máxima es nlogn queda como tetha de nlogn automáticamente. 

Al menos así lo entendí u-u

**Comment by NicolasLahsen** [comment]
Hola! @Fenho efectivamente la demostración fue solo para la cota superior, debiese ser O(n•logn). Disculpa las confusiones que esto pudo causar.

Saludos!

**Comment by vichoeq** [comment]
Pero efectivamente, como dijo @Arcoirisky , ya demostramos que los algoritmos que ordenan por comparacion e intercambio de elementos son Omega(n logn), por lo tanto la complejidad si es Theta.

**Comment by Fenho** [comment]
Gracias!
