### ISSUE TITLE
Legalidad de demostraciones 

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#43]
Hola! 
Según las slides todas las demostraciones se hacen por inducción pero ¿puedo demostrar por código? En discretas, la última materia, nos enseñan de esa forma y creo que es más fácil ver el orden de los algoritmos al programarlos. 

Sino, ¿podrían explicarme como hacen para sacar el T(n) con el cual consiguen demostrar MergeSort? El que luego usan para reducir hasta llegar a nlogn

**Comment by vichoeq** [comment]
Hola, las demostraciones que hemos hecho por inducción son porque funciona para esos algoritmos, pero no todo se demuestra por inducción (pero es una herramienta muy útil que deben practicar) 

No se a qué te refieres a "demostrar por código". Las demostraciones que hemos estado haciendo son sin el uso de un computador o programar nada: es una demostración matemática, y se espera que argumenten formalmente a la hora de demostrar.

Ojo que un calculo de complejidad no es una demostración. Dicho eso, la recurrencia de mergesort viene de lo siguiente:

El tiempo de Mergesort con un arreglo de largo n lo llamamos T(n).

Primero, si n = 1, entonces **T**(n) = 1.

En otro caso, mergesort lo que hace es dividir el arreglo en 2, y llamar a mergesort con cada mitad: **T**(n/2)

Pero si n es impar, uno de los sub arreglos va a tener un elemento extra. Por eso una de las mitades se llama con el piso de n/2 y la otra con el techo de n/2.

Es decir, hasta ahora **T**(n) = **T**(techo(n/2)) + **T**(piso(n/2))

Luego de hacer ambas llamadas, hacemos _merge_, lo cual ya vimos que toma n pasos.

Por lo tanto, si n > 1,  **T**(n) = **T**(techo(n/2)) + **T**(piso(n/2)) + n

Y esa es la recurrencia:

![image](https://user-images.githubusercontent.com/5317897/78612364-23f4c680-7837-11ea-8750-dc7a8a62f6d8.png)


Espero haber respondido tu pregunta, cualquier duda puedes contestar este issue.

**Comment by Arcoirisky** [comment]
Oooh gracias!!! 

Y con código me refería a que todo algoritmo correcto puede codificarse aunque sea en psudo código. Si puedo demostrar que todo sub algoritmo de mi algoritmo es correcto, además de que el algoritmo en total es finito y cumple su objetivo, entonces es correcto

**Comment by vichoeq** [comment]
Ah claro. Así demostramos que los algoritmos recursivos son correctos :)

**Comment by vichoeq** [comment]
O para demostrar que quicksort o mergesort son correctos, tenemos que demostrar primero que partition o merge son correctos, respectivamente.
