### ISSUE TITLE
Ayuda. Perdi mi tarea (??)

### ISSUE THREAD

**Issue by NicolasCastillo24** [IIC2133-PUC/2020-1#44]
Estoy trabajando con VScode en Mac y quise borrar un archivo .c dentro de la carpeta src. Pasa que se me desaparecieron todos los archivos de la carpera y ahora me aparece vacía. Los archivos no están en mi basurero tampoco, no los puedo encontrar. Tengo los archivos compilados .o, existe alguna forma de obtener mis archivos .c con eso? o donde pueden haber quedado?

**Comment by viantirreau** [comment]
😮 😨 
Hace cuánto hiciste push?
Si estás 100% seguro que no está en la papelera y los cambios desde el último commit son demasiados, leí que podías crear desde VSCode un archivo con exactamente el mismo nombre, en la misma ubicación que los .c que se te borraron y rogar por que con `CMD+Z` (en la ventana de edición del archivo, donde escribes código) te deshaga los cambios en el archivo y básicamente lo escriba de nuevo.

**Comment by yerkko** [comment]
Si hiciste commit anteriormente, quizás git stash o git reset te salven 🤔

**Comment by NicolasCastillo24** [comment]
Lo encontre! Estaba en la papelera pero por alguna razón salia que se borro a la misma hora que la ultima vez que borre algo (onda, salia 2am ???). Pero todo ok. Gracias coloro <3
