### ISSUE TITLE
Duda C2 - 2019-1 [Árbol AVL]

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#45]
Hola, tengo una duda sobre un ejercicio:

![image](https://user-images.githubusercontent.com/47841749/78514031-4a562b80-777d-11ea-862e-9faece9f5b60.png)

Básicamente por qué la función recursiva se define así, mi solución (que me gustaría que alguien me diga si es válida) es la siguiente: la cantidad de nodos mínima para un AVL de altura <h> es 0 si h=0 y 1 si h=1, tal cual dice la solución (caso base).

Luego si h>1

La cantidad de nodos mínimos es 

![image](https://user-images.githubusercontent.com/47841749/78514888-b76bc000-7781-11ea-9508-2f531d5aad31.png)

Esto debido a que si quiero llenar hasta una altura h-1 debo llenar el heap de nodos desde el nivel 1 hasta el h-1 (desde 0 hasta h-2 como se expresa en la sumatoria). Y para colocar el primer nodo en el nivel h debo sumar +1. 

Entonces finalmente tengo lo siguiente:

f(0) = 0
f(1) = 1
f(2) = 2<sup>0</sup>+1 =2<sup>0</sup>+f(1)
f(3)=2<sup>0</sup>+2<sup>1</sup>+1 = 2<sup>1</sup>+f(2)
f(4)=2<sup>0</sup>+2<sup>1</sup>+2<sup>2</sup>+1 = 2<sup>2</sup>+f(3)
...
f(n)=2<sup>0</sup> +... + 2<sup>n-1</sup>+2<sup>n</sup>+1=2<sup>n</sup>+f(n-1)

Entonces una solución alternativa a mi gusto es la siguiente:

```
min_nodes(h):
  if h= 0:
    return 0
  else if h=1:
    return 1
  return 2**h + min_nodes(h-1)
```

Espero alguien me puedan decir si mi solución es correcta o no, y además explicarme la solución propuesta.

**Comment by VicenteMerino** [comment]
Incluso pienso que ni siquiera es necesario hacerlo recursivo, sabiendo la fómula basta hacer:

```
min_nodes(h):
  nodos = 0
  for i in {0,...,h-2}:
    nodos += 2**i
  return nodos +1
```

**Comment by chocopiano** [comment]
Por lo que me dijeron, eso no entra

**Comment by Kitaps** [comment]
Efectivamente, como dice @chocopiano aun no ven esa materia, por lo que no entra. 
Saludos y éxito con el estudio.
