### ISSUE TITLE
Dudas array de punteros a struct

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#46]
Hola, tengo dudas de como implementar una lista de punteros a structs en C, he buscado harto pero no me queda claro. Queria ver la posibilidad de tener una reunion por Hangouts con algun ayudante que me pudiera ayudar a entender esto.

Muchas gracias!

**Comment by yerkko** [comment]
Te invito a revisar el taller de c, en especial el ejemplo de la matriz:
[Matriz](https://github.com/IIC2133-PUC/2020-1/blob/master/Talleres/Taller%200%20-%20Intro%20a%20C/src/7_structs/matrix.c)
En este caso, mat es un arreglo de punteros a int. Sin embargo, puedes cambiar los tipos a tu struct con facilidad en ambos malloc.

**Comment by danustilovsky** [comment]
Hola, perdon me exprese mal. Estoy tratando de implementar un puntero a un array que contiene punteros a structs, y no logro entender porque no funciona. He buscado en internet pero no he podido encontrar alguien que intente lo mismo. 

O queria saber si es igual de eficiente implementar un puntero a un array que contiene punteros a structs, que implementar un puntero a un array que contiene los structs directamente.

gracias

**Comment by Kitaps** [comment]
Podrías poner un ejemplo de a que te refieres?

**Comment by danustilovsky** [comment]
Hola, espero que se logre entender.

Tengo una struct "main" en mi codigo que funciona como estructura principal, la cual tiene como uno de sus miembros un array que la idea es que contenga pointers a otras struct que podrian ser terminales o puertas por ejemplo, y esta estructura se repite hasta llegar a las colas, que idealmente tendrian sus pointers almacenados en otro array. El problema es que cuando trato de asignar un puntero del struct2 al miembro que es un array de pointers del struct1, me tira un error que no logro solucionar. 

Entonces queria saber si eso es posible de implementar, o en otro caso, si vale la pena hacerlo de esta o es mejor simplemente almacenar las sub-structs en un array de structs y no vale la pena trabajar con tantos punteros?

**Comment by Arcoirisky** [comment]
Lo primero que se me ocurre preguntar es si estás pidiendo memoria extra para guardar estas estructuras en algún espacio de la memoria y que así su puntero no sea volátil al estar en el stack.

(No soy ayudante pero puede que tengas problemas con los scopes? Escuche por ahí que si haces cosas dentro de una función o algo dentro de { } al salir de este desaparece. Ahí mi duda si pides memoria)

**Comment by danustilovsky** [comment]
Hola, si estoy pidiendo memoria. Pero cuando trato de hacer p1->p2[0]->miembro, eso no me funciona

**Comment by Arcoirisky** [comment]
pero si estás guardando el puntero y no el elemento como en el ejemplo de las matrices está bien que no te funcione o: 
pero si guardas el elemento en p2[0] entonces ahí si deberías poder hacer p2[0] -> miembro
con el puntero deberías hacer algo como
tipo* elem = &p2[0]; 
y ese elem debería poder hacer elem -> miembro

No estoy segura si es 100% así, pero según el taller de punteros debería funcionar :s 

para hacer lo que quieres entonces deberías hacer algo como p2[0] = new_Tipo
con new_Tipo una "instancia" de la estructura que tiene en su interior miembro para hacer new_Tipo -> miembro o:

**Comment by Kitaps** [comment]
Mientras más directo mejor. 

Y como dice Arcoirisky, si es que quieres pasar un array o puntero tienes que haberlo pedido con memoria. 

Espero que hayas estado comiteando y pusheando, que se ve enredado lo que estás haciendo y es fácil enredarte.

**Comment by Kitaps** [comment]
@danustilovsky Hola, como te ha ido con esto? 

Si sigues con dudas mandame un correo para que lo veamos
