### ISSUE TITLE
Duda complejidad quickSelect.

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#47]
Hola, estaba viendo la clase 4 y mencionan que la complejidad de quickselect es O(n^2), sin embargo en esta prueba:

![image](https://user-images.githubusercontent.com/47841749/78609884-ae3a2c00-7831-11ea-80b7-5fd792ec2348.png)

y en este link:

https://stackoverflow.com/questions/5945193/average-runtime-of-quickselect

Mencionan que es O(n), alguien podria explicarme cual es la complejidad y por qué?

**Comment by yerkko** [comment]
Hello.
No he visto el video que mencionas, sin embargo, quickselect es O(n) en el mejor caso y caso promedio. O(n^2) en el peor. Podrías comentar el timestamp?

**Comment by Arcoirisky** [comment]
Esq en las slides hay un código que es claramente O(n^2) pero en la Ayudantia se ve como QS 
QS(A,I,f)
    If f-i >=0:
        p= Partition(A,i,f)
        QS(A,i, p-1)
        QS(A, p+1,f)

Supongo que es ese el que usan para la prueba

**Comment by VicenteMerino** [comment]
> Hello.
> No he visto el video que mencionas, sin embargo, quickselect es O(n) en el mejor caso y caso promedio. O(n^2) en el peor. Podrías comentar el timestamp?

Ups, pensé que se lo había puesto. Pero si busqué un poco y entendía por qué es eso, y hablaban de O(n^2) en el peor caso. Cambiaré el nombre a la issue para no crear confusión.
