### ISSUE TITLE
Duda ecuación de recurrencia

### ISSUE THREAD

**Issue by javiinostroza** [IIC2133-PUC/2020-1#48]
Hola, todavía me cuesta imaginar cómo se arman las ecuaciones de recurrencia. Por ejemplo para el peor caso de QuickSort 
![Screenshot from 2020-04-06 21-38-43](https://user-images.githubusercontent.com/26410892/78620962-632f1180-784f-11ea-90da-36c7b660abec.png)

Entiendo que para n>1 lo que hago es tomar un pivote tal que m o M queden vacías, entonces al tomar ese p me veo obligada a hacer (n-1) comparaciones. Pero no entiendo por qué T(n) es n+T(n-1) y no n*T(n-1).

**Comment by Arcoirisky** [comment]
será por el primer partition? que toma T(n) para el primer pivote. 
luego para el segundo toma T(n-1) porque quité un elemento, etc.
Se me ocurre realmente, por cómo me lo explicaron en #43 para MergeSort

**Comment by vichoeq** [comment]
Es exactamente eso. N es el tiempo que toma correr partition, y T(n-1) es el tiempo que toma quicksort en el peor caso con n-1 elementos.

**Comment by vichoeq** [comment]
Una explicación más detallada: El algoritmo es el siguiente:

```c
void quicksort(int* A, int i, int f) // Esto toma T(f-i+1).
{
     if(i<f)
     {
          int p = partition(A,i,f); // Esto toma f-i+1
          quicksort(A,i,p-1); // Esto toma T(p-i)
          quicksort(A,p+1,f); // Esto toma T(f-1)
     }
}
```
No olvidar que `f-i+1` es la cantidad de elementos entre los indices `f` e `i`, incluyendo ambos.

Nuestro algoritmo está haciendo 3 cosas que toman tiempos distintos, por lo tanto sumamos el tiempo que toman (la multiplicación que sugeriste solo tiene sentido cuando repetimos lo mismo una cierta cantidad de veces, como en un for)

Es decir, aparte del caso base, 

`T(f-i+1) = f-i+1 + T(p-i) + T(f-p)`

En el peor caso, tenemos que p resulta ser siempre el primer (o último) elemento. Dejémoslo como el primero: `p = i`. Por lo tanto,

`T(f-i+1) = f-i+1 + T(i-i) + T(f-i)`
`T(f-i+1) = f-i+1 + T(0) + T(f-i)`

`T(0)` queda fuera del if de la funcion, asique no aporta a la complejidad.

Ahora si sustituimos `f-i+1` por `n`, tenemos:

`T(n) = n + T(n-1)`

Espero que esto haya resuelto tu duda.

**Comment by javiinostroza** [comment]
Sii! muchas gracias! :smile:
