### ISSUE TITLE
Duda Ayudantía 1 P2

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#49]
Hola!
Quiero saber si estoy entendiendo bien la complejidad final del nuevo algoritmo con insertionSort.
entiendo que la parte normal de QS sea nlog(n/k)

que es porque para llegar a la iteración deseada tenemos que:
n/2^x = k (con k la cantidad de elementos que desamos para "detenernos")
aplicando log llegamos a que esa profundidad x = log(n/k) yaay

Mi problema es con la parte de insertionSort. Entiendo que ahora son k elementos y no n por lo que el peor caso es O(k²) y en el mejor O(k) que es a lo que estamos apuntando. Por lo tanto, como estamos suponiendo estos nuevos sub-arreglos como "semi-ordenados" decimos que es O(k)

Ahora, siguiendo la lógica de las sumatorias para la P1 de la misma ayudantía (saltándome todas sumatorias que practicamente son las mismas pero con un k extra), tendríamos que el número promedio de comparaciones sería menor a 2n(log(n/k)+1 + k) sumándole la k por el InsertSort

Es así como se llega que el nuevo algoritmo es O(nlog(n/k) + nk)?
Sino, estoy perdidísima. Aiua

**Comment by yerkko** [comment]
Si llamas a InsertionSort de manera individual para c/u de los sub-arrays, terminará de ordenarlos individualmente antes de pasar al otro. (Recordar que InsertionSort funciona de manera lineal sobre un arreglo) 
Cada uno tiene k elementos, y son n/k sub-arrays. Te queda finalmente n/k * O(k^2) = O(nk).

**Comment by yerkko** [comment]
A eso le añades el O(nlog(n/k).

-> IntroSort es O(nlog(n/k) + nk)

**Comment by Arcoirisky** [comment]
Oh baia, entonces digo que luego de log(n/k) iteraciones tendré n/k sub arreglos.
No me termina de convencer, en busqueda binaria separando los elementos en 2 termino con esta forma:
[1,2,3,4] 0 iteraciones 2⁰ = 1 sub arreglo = arreglo
[1,2] [3,4] 1 iteracion 2¹ = 2 sub arreglos
[1] [2] [3] [4] 2 iteraciones 2² = 4 sub arreglos 
por qué luego de n/k iteraciones obtengo n/k subarreglos? 

Quizás es muy básico pero no lo estoy viendo D: por eso no me lo compro ;--;

**Comment by yerkko** [comment]
En tu caso 
n = 4
k = 1
log(n/k) = 2 (Base 2)
Luego de 2 = (log(n/k) iteraciones quedas con 4 (n/k) arreglos

**Comment by Arcoirisky** [comment]
Aaah ahí zi. Tksm 💕
