### ISSUE TITLE
Instalacion de ubuntu 

### ISSUE THREAD

**Issue by tsgonzalez** [IIC2133-PUC/2020-1#5]
Hola, en el ultimo paso para instalar ubuntu  dice que hay que cerrar la pestaña, cuando la cierro y luego abro ubuntu de nuevo me pide que vuelva a instalar todo de nuevo. Estoy haciendo algo mal en ese ultimo paso? a otra compañera le pasa igual. (en mac)

**Comment by VicenteMerino** [comment]
Creo que no vale mucho la pena instalar Ubuntu en Mac por la optimización del ordenador para ese SO.

**Comment by VicenteMerino** [comment]
Además creo que C ya viene instalado en Mac, igual ojalá un ayudante te ayuda.

**Comment by vichoeq** [comment]
Hola, sigues teniendo este problema? Podríamos coordinar un hangouts con uno de los ayudantes para ayudarte a resolverlo.

**Comment by ChaparoD** [comment]
@vichoeq , a mi me pasa algo similar, lo dejo corriendo harto rato después de la instalación de Ubuntu pero hasta el momento (20 min) no me ha mostrado el siguiente paso en pantalla

**Comment by tsgonzalez** [comment]
Ya lo arregle, gracias igual!!
