### ISSUE TITLE
Estructura Prueba

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#50]
Hola!
Hace tiempo llevan diciendo que nos dirán el formato de la prueba, ya no puedo con la tensión y tenía que preguntar si saben algo al respecto o no :c 
Quizás hasta ya mandaron el mail explicando y no me ha llegado o algo.

**Comment by vichoeq** [comment]
Oh. Lo discutimos al final de la clase del lunes frente a muchos alumnos, pero aún hay ciertos detalles que tenemos que afinar, por lo que no hemos podido mandar un anuncio oficial. Te voy a decir lo que sí sabemos:

* La prueba consta de 3 preguntas.
* La prueba considera que tienen acceso a internet, libros y clases.
* La prueba es individual.
* La prueba se publicará el miércoles a las 14:00 y se entregará por SIDING el jueves a las 14:00
* El módulo de clases del miércoles será usado para hacer una sesión activa de dudas del enunciado.
* Durante el resto del tiempo, cualquier duda que tengan debe ser publicada aquí como issue. No responderemos correos ni mensajes directos.
* Los ayudantes iremos respondiendo las dudas tan rápido como podamos, pero no garantizamos responder pasadas las X horas del miércoles. (Aun no definimos la hora). Retomaremos actividad a partir de las 8:30 del jueves.
* El formato de entrega es por PDF. Puede contener lo siguiente:
    * Texto digital (Word, Latex)
    * Texto escrito a mano (porfavor que la letra sea clara)
    * Algoritmos y diagramas **dibujados** en papel 
    * Usar Scanner o aplicaciones de celular como CamScanner para digitalizar lo que hagan a mano. Evitar fotografías.

Eso por ahora, no se me ocurre más. Espero que sirva :)

**Comment by Arcoirisky** [comment]
Durante ese periodo solo los ayudantes pueden responder las issues?

**Comment by vichoeq** [comment]
Si, mejor, así evitamos que se den respuestas entre ustedes (aunque sea involuntariamente)

**Comment by Arcoirisky** [comment]
Te lloro

**Comment by vichoeq** [comment]
Ok me avisan por interno que es hasta el jueves a las 13:00, ya que esa es la hora en que la universidad supende actividades y no podemos pasarnos.
