### ISSUE TITLE
Duda Valgrind

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#51]
Hola,

Como se debuguea el código usando valgrind? Hay alguna forma de ir identificando donde está el leak memory o hay que hacerlo al ojo y viendo donde están los mallocs?

**Comment by Arcoirisky** [comment]
Al hacer valgrind te da un montón de texto en medio de la ejecución, si no lo hace, al final te dice qué debes de poner al final de la llamada para que te imprima el porqué de todo o: Al menos así lo iba debuggeando yo. 
Ya si eso no te resulta, queda mirar el código y ver que tengas la misma cantidad de malloc y free (además de que siempre se llegue al free correspondiente)

Oh y al borrar puede que tengas que hacerlo tipo "árbol" como:
Si terminales tiene i estaciones guardados, entonces debes liberar todas las estaciones, luego liberar terminales -> estaciones y luego terminales. 
ya si tienes más cosas dentro de otras a las cuales les pediste memoria, debes eliminarlas para cada una siguiendo la lógica anterior o: 

Al menos a mi me funcionó así

**Comment by yerkko** [comment]
Se hace tal como @Arcoirisky menciona. La verdad es que no tengo nada más que añadir (?)

Gracias por tanto Arcoirisky, perdón por tan poco.

**Comment by Arcoirisky** [comment]
@yerkko acepto respuestas en modo de agradecimiento (? No puedo intentar responder mis issues 😂

**Comment by VicenteMerino** [comment]
@Arcoirisky Te puedo hacer una pregunta, cual es la diferencia entre hacer free(estaciones) y free(terminales->estaciones) creo que por ahi podria andar mis problemas.

**Comment by Arcoirisky** [comment]
Terminales tiene un “atributo” (no c como se llaman para structs pero los veo como clases de Python) que es la súper array estaciones

Entonces para usarla debiste de hacer 
Terminal* terminales = malloc(Terminal)
terminales -> estaciones = malloc(sizeof(estaciones*)*nestaciones);

Algo así, luego a estaciones le metes cosas que seguramente también pedirás con malloc pero al final de tu programa liberaste dentro de un for, Yaay

Entonces sigue:

free(terminales -> estaciones) 
Que libera el segundo malloc que te escribí arriba, ósea, el pedazo de memoria que pedí reservar para mi súper array de estaciones 

Y luego hago free(terminales) que es el primer malloc que pedí. 

Mejor?

**Comment by yerkko** [comment]
Si liberas el puntero a una struct antes de liberar la struct misma, pierdes la referencia y la memoria sigue ocupada. Por eso tienes que liberarlas una por una en el for antes de poder liberar el array. (Recordar que un array es sólo un puntero a una dirección, luego el índice es un offset con respecto a esta dirección)

**Comment by VicenteMerino** [comment]
@Arcoirisky @yerkko Muchísimas gracias!!
