### ISSUE TITLE
Duda sift-up Heaps

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#52]
Hola!
Estaba viendo los algoritmos de Heaps y quedé complicada con el Sift-Up
Sabemos que un padre en la posición i tiene hijos en 2i y 2i-1 para i entre 1 y n
(pensando en las posiciones como "primera posicion" hasta la "n-ésima posicion")
con 2i como el hijo con mayor prioridad

PERO, al ingresar un elemento lo agrego al final del arreglo ¿cómo sé que soy un hijo 2i o un hijo 2i-1? lo pregunto porque en sift-up debo compararme con mi padre pero si no sé que tipo de hijo soy podría irme sin querer a un hijo de otro nodo en vez de a mi padre D: 

Lo estoy pensando en la forma de arreglo

**Comment by Arcoirisky** [comment]
Será acaso que si i es par soy el hijo de la izquierda y con i impar de la derecha? 
-quizás me respondí sola pero igual ayuda la confirmación-

**Comment by Kitaps** [comment]
Hola, 

porque 2i-1?
Si miro el ejemplo de la clase los hijos están en la posición 2i é 2i+1
![image](https://user-images.githubusercontent.com/10112117/78716834-9fb14a80-78ed-11ea-80dc-2ca6c2286743.png)
No debería haber prioridad entre hermanos en un heap. Lo importante es la prioridad entre el padre y los hijos. 

Si queda alguna duda o quieres discutir la respuesta me dices ;)

**Comment by Arcoirisky** [comment]
Nonononono, mi pregunta va más a
“Yo sé que soy un hijo... no sé cuál de los dos hijos... ¿cual es mi padre?”

**Comment by yadran** [comment]
Los hijos del nodo en la posición i del arreglo, están en las posiciones
2*i y 2*i+1.
No hay ninguna priorización (u orden) entre estos hijos, por lo que, cuando
hay que
hacer intercambios con el padre, hay que mirarlos a ambos.

Por otra parte, el padre del nodo en la posición i está en la posición i/2
(división entera);
p.ej., tanto para el nodo en la posición 4 como para el nodo en la posición
5, el padre
está en la posición 2.

--Yadran

**Comment by Arcoirisky** [comment]
Oooh claro, con división entera.
Gracias por lo de que los hijos no tienen orden de prioridad!! No lo sabía 😱
