### ISSUE TITLE
Algoritmos estables

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#55]
Hola
¿Que es lo que hace que un algoritmo de ordenación sea considerado estable?
Al parecer QuickSort no lo es (seguro por el partition que elige un pivote al azar) pero ¿que se considera estable? ¿El Orden?

**Comment by yerkko** [comment]
Un algoritmo estable, dado dos elementos con la misma key, mantendrá el orden en que ya estaban antes. Imagínate que estás ordenando structs usando como key un int que está adentro de estas. hay cierta información extra aparte de la key que te gustaría mantener en el orden en que estaba desde antes

**Comment by yadran** [comment]
Un algoritmo de ordenación es estable si cuando ordena dos datos con el
mismo
valor, los deja en el mismo orden relativo que tenían antes de ordenarlos.
--Yadran

**Comment by Arcoirisky** [comment]
aaah, entonces~ sin contar QuickSort, Partition, Heaps y HeapSort, nuestros algoritmos son estables ¿No?
