### ISSUE TITLE
QuickSort con MedianPartition

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#56]
Si con MedianPartition nos ahorramos de las subarrays desbalanceadas en partition ¿por qué seguimos usando el método random para elegir pivote?
Entiendo que para partition solo conviene más para encontrar al i-ésimo menor elemento y no solo tener la mediana pero ¿para QuickSort? 
En principio debería ser lo mismo, incluso mejor porque me asegura el O(nlogn) ¿No?

**Comment by vichoeq** [comment]
Hola, no se si entiendo bien tu pregunta...

> ¿por qué seguimos usando el método random para elegir pivote?

El escoger un pivote aleatoriamente es para evitar la posibilidad de forzar el peor caso manipulando el input. 

> Entiendo que _para_ partition solo conviene más _para_ encontrar al i-ésimo menor elemento y no solo tener la mediana pero ¿para QuickSort?

Me perdí entre tanto _para_

> En principio debería ser lo mismo, incluso mejor porque me asegura el O(nlogn) ¿No?

Asumo que te refieres a elegir como pivote la mediana... si siempre escogieramos la mediana como pivote, efectivamente quicksort sería O(nlogn), pero el problema es que no sabemos a priori donde está la mediana por lo que hay que encontrarla.

**Comment by Arcoirisky** [comment]
hmmm esq hay un ejercicio en el examen del 2017-1 que te pide hacer un medianPartition. De ahí surgió mi duda. 
Quizás si te cambio mi pregunta:
¿Usar medianPartition me asegura 100% que QuickSort tardará nlogn? ¿aún en el peor caso?
o ¿sólo me aumenta la probabilidad de que en el peor caso sea O(n²)?

**Comment by Arcoirisky** [comment]
Según yo, no debería. Porque ya no tendría el problema de tener subarreglos desbalanceados.

¿A que te refieres con que el problema sería encontrar la mediana? se supone que debe ser O(n) al igual que el partition normal pero me va formando subarreglos más equilibrados.

**Comment by vichoeq** [comment]
Pero recuerda que encontrar la mediana tambien puede ser O(n^2) en el peor caso...

**Comment by Arcoirisky** [comment]
Entonces lo que me acompleja es... Why
Quizás me he saltado algo pero entonces, como es posible hacer un medianpartition O(n) si termina siendo un QuickSelect que es O(n^2)

**Comment by vichoeq** [comment]
Ojo, dice tiempo promedio O(n)... tal como el tiempo de encontrar la mediana.

**Comment by vichoeq** [comment]
La palabra clave ahi es _promedio_

**Comment by Arcoirisky** [comment]
Aaah pos si. En promedio es O(n) 
Toh claro entonces xD gracias por salvarme del pánico
