### ISSUE TITLE
Preguntas Frecuentes I1

### ISSUE THREAD

**Issue by vichoeq** [IIC2133-PUC/2020-1#58]
# 0 

Entrega todo en un solo PDF.

Se lo más formal posible.

**Como regla general no pueden preguntar "puedo usar X técnica en Y pregunta?"**
### **Tienen autorización de utilizar los teoremas que estimen convenientes.**

# 1

## a

* No es necesario que demuestres correctitud, sólo que el arreglo queda como un heap.
* Puedes asumir que Sift Down es correcto.
* No importa el tipo de heap (max/min), asume uno de los 2 y demuestra para eso.
* Sé lo más formal posible
* El arreglo parte desde 0 y todos los indices hacia abajo se calculan correctamente.
* El indice 0 está incluido dentro del for.
* Puedes asumir que en lugar de 0 hasta n-1, los indices del heap van desde 1 a n. No cambia el problema. El for queda igual solo que termina en 1 en vez de 0.

## b

* Sí, la complejidad es O(n)
* **Hint:** No utilices la complejidad de siftdown, piensa cuantos pasos toma cada llamada.

# 2

## a

* El return sale del while true
* Devolver los elementos de B a A resetea el conjunto A al estado que tenía al comenzar la función (ya que es un conjunto por lo que no tiene noción de orden ni elementos repetidos)
* La demostración de no correctitud debe ser formal, pero no necesariamente matemática. Basta con que hagan un razonamiento riguroso. 
* No es necesario que modifiquen explicitamente el algoritmo, basta con decir qué se tiene que cambiar en la metodología / describir el cambio.
* Bogosort tiene una falla que lo hace ser no correcto; tu deber es encontrarla y corregirla. No es necesario que demuestren más allá de eso.
* Modifica solo lo que argumentes que es el problema.
* La complejidad del algoritmo resultante no importa, sólo que sea correcto.

## b

* No es necesario demostrar nada.
* Intenta relacionarlo con la razón por la que bogosort no es correcto.

# 3

* En la ayudantía se vió como trabajar con pisos y techos.
* Notación asintótica = notación O, omega, theta.
* Complejidad en el peor caso
* No es necesario que se preocupen de la memoria adicional

## a

* Merge 3-way ya está implementado y funciona
* Puedes asumir que merge de 3 listas, de n elementos en total, toma n pasos.

## b

* Merge k-way ya está implementado y funciona
* La complejidad en función de n y k quiere decir que **no** te puedes deshacer del k en la complejidad.

**Comment by camaruri** [comment]
en la 1, los indices que parten de n/2 a 0.
por ejemplo si es del i = {3,2,1,0} y después de que se hace para i = 3 el elemento que iba en el 2 cambia
Entonces para el nuevo siftdown debemos considerar el elemento que estaba antes en la posición 2 o la que quedo después del primer siftdown

**Comment by arbiocanpion** [comment]
Hola @camaruri 
Te respondere tu pregunta un poco mas general. Al hacer siftwdown para el primer índice, para el segundo índice el arreglo ya esta con los cambios que se le hicieron en la primera iteración.
Es decir, si el elemento que iba en la posición dos cambia con el de la posición tres dentro de la primera iteración, para la siguiente iteración en el for ( en este caso 2) el arreglo ya tendra hecho el cambio.

**Comment by chocopiano** [comment]
En la 2a me piden modificar el algoritmo para que quede correcto manteniendo la  lógica. Esa logica se refiere con ir tomando un elemento aleatorio ? Y de no ser así a que se refiere exactamente?

**Comment by danustilovsky** [comment]
Hola, en matematicas discretas se ve un teorema maestro para algoritmos, se puede ocupar en la pregunta 3?

**Comment by navarrodiego** [comment]
En la 2a se puede usar una cantidad de memoria muy grande para que funcione el algoritmo o hay que tener algún cuidado con esto?

**Comment by arbiocanpion** [comment]
Hola @chocopiano !
Al referirnos mantener la lógica, el enunciado se refiere que a solo debes cambiar la parte erronea del algoritmo. Ya que como se indica mas arriba 

> Bogosort tiene una falla que lo hace ser no correcto; tu deber es encontrarla y corregirla

Si tu crees que el error es tomar un elemento aleatorio, entonces modifica esa parte pero sin modificar el resto del algortimo.

**Comment by vichoeq** [comment]
@navarrodiego lo unico que importa es que el algoritmo sea correcto, la memoria y la complejidad no nos interesan :)

**Comment by hbkim94** [comment]
Hola! Debemos incluir pseudocódigo para la pregunta 3?

**Comment by vichoeq** [comment]
@hbkim94 nop, solo la ecuación de recurrencia para el tiempo que toma el algoritmo.

**Comment by isavega** [comment]
Pregunta 2

El while True considera que B sea un arreglo vacio? O esto es solo una definicion de B? Es decir, si B no es vacio, while true para?

Me suena raro que la definicion de B este debajo del while True, si no afecta se puede "sacar"?

**Comment by isavega** [comment]
Pregunta 2

Me faltó preguntar cual era el objetivo de Bogo(). Retornar una lista ordenada de largo cualquiera? O retornar una lista ordenada de largo = |A|?

**Comment by arbiocanpion** [comment]
Hola @isavega respondiendo a tus preguntas

1. En cada iteración del while True b se vuelve a convertir un arreglo vacio. El while True jamas parara si b no es vacio (solo pueden parar con un break o un return).

2. No, no se puede sacar la definicion de B debajo del while True

3. El objetivo de Bogo (al ser un algoritmo de ordenación) es entregar una lista ordenada de largo = |A|.

**Comment by vichoeq** [comment]
@isavega ... y con los elementos de A

**Comment by bvallejo1** [comment]
En la pregunta 2 dentro del segundo while, cuando dice que se extrae un elemento de A y se inserta al final de B, esta inserción implica mover los demás elementos a la izquierda?

**Comment by arbiocanpion** [comment]
Hola @bvallejo1!
B es un arreglo y por tanto al decir que se inserta el elemento al final de B, se esta diciendo que se esta agregando el elemento a B como si fuera un lista.
``` py
B = [1]
B.append(2)
print(B)
[1,2]
```

**Comment by TrigalJeruti** [comment]
Pregunta 2 a 
Con modificar BogoSort se refiere a cambiar, agregar o eliminar algo?

**Comment by arbiocanpion** [comment]
@TrigalJeruti  así es, la idea como indica el enunciado, es que tu identifiques las sección que falla del algoritmo e indiques como corregirla.

**Comment by bvallejo1** [comment]
En la 3 podemos asumir que los datos se dividen en partes iguales?

**Comment by yadran** [comment]
Sí, en tres partes tan iguales (en cuanto al número de datos de cada una)
como se pueda.  --Yadran

**Comment by cchauriye** [comment]
Hola! ¿Cuánto podemos cambiar el algoritmo? ¿Podemos básicamente escribir uno nuevo mientras mantenga la "lógica" que nosotros identificamos o debemos cambiar una línea nomás?

**Comment by fediaz3** [comment]
Hola!
En la 1.a hay que demostrar con algún método matemático formal o también se puede incluir dibujos y textos para la demostración? 
Gracias

**Comment by etoteiza** [comment]
Hola!
en la 3, así como se asume que se dividirá en 3 partes iguales, podemos asumir que también dividirá en k partes iguales?

**Comment by etoteiza** [comment]
Hola! Se puede usar el teorema maestro para resolver la recurrencia de Mergesort?

**Comment by vichoeq** [comment]
@cchauriye no recomiendo intentar modificar el código en sí, los que nos interesa es que digas que es lo que tiene que hacer el algoritmo para ser correcto bajo la logica que él mismo usa. Todo depende de tu definición de nuevo algoritmo... si tiene la misma lógica, qué lo hace distinto?

**Comment by vichoeq** [comment]
@fediaz3 matemático y formal tal como los que usamos en clases y ayudantías

**Comment by yerkko** [comment]
> Hola! ¿Cuánto podemos cambiar el algoritmo? ¿Podemos básicamente escribir uno nuevo mientras mantenga la "lógica" que nosotros identificamos o debemos cambiar una línea nomás?

Tu Bogo2.0 debe mantener la misma lógica de este, no puedes cambiar todo y tener QuickSort por ejemplo. Debes añadir/quitar/cambiar sólo lo estrictamente necesario

**Comment by vichoeq** [comment]
@etoteiza si, k partes iguales, es una generalización de mergesort despues de todo.

**Comment by niguzman** [comment]
Hola,
en la pregunta 3.b, la complejidad de Merge siempre es n*log_2(k) o ese dos cambia también dependiendo de k?

**Comment by vichoeq** [comment]
@niguzman la complejidad de merge efectivamente es siempre n*log_2(k), ese dos no cambia dependiendo del k.

**Comment by VicenteMerino** [comment]
Qué cosas somos libres de agregar en BogoSort? Podemos por ejemplo usar más argumentos, solicitar más memoria usando otro arreglo vacío, cambiar alguna de las condiciones?

**Comment by santilaguna** [comment]
Para el bogosort pueden agregar lo que estimen necesario, mientras no modifiquen la lógica del programa!

**Comment by silvamatias** [comment]
Hola! se puede usar el teorema maestro para la 3.a?
