### ISSUE TITLE
Interpretacion Valgrind 

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#59]
Hola! No me he podido manejar muy bien con Valgrind, entonces no entiendo bien cuando funciona correcto mi código. Esto me tira cuando hago valgrind:

Esto me sale al principio, donde van los Malloc:

<img width="1008" alt="Screen Shot 2020-04-08 at 11 24 53 PM" src="https://user-images.githubusercontent.com/17711310/78854898-79c09e80-79f0-11ea-9923-a19653881d0a.png">

Y esto me sale al final, donde van los free:

<img width="1007" alt="Screen Shot 2020-04-08 at 11 25 22 PM" src="https://user-images.githubusercontent.com/17711310/78854914-83e29d00-79f0-11ea-9c01-e8ad957a84da.png">

<img width="1004" alt="Screen Shot 2020-04-08 at 11 26 21 PM" src="https://user-images.githubusercontent.com/17711310/78854918-86dd8d80-79f0-11ea-9e08-b6212f796379.png">

Obviamente leo que hay 2 errores porque dice al final (¿o hay más?), pero también el Heap Summary esta bien? Porque dice que estoy usando 0 bytes al exit y que el heap total que se usan son 14 alloc y 14 frees, o sea en equilibrio.

Bueno, en resumen, mi pregunta es: mis únicos errores son esos dos que dice al final sobre Invalid read of size 8? Pero si esos dos son los únicos errores, por que me dice al principio: "Memcheck, a Memory error detector", eso significa que encontró un error o que se activó el detector?

Y aprovechando, como el HEAP Summary dice que no hay leaks, significa que se esta manejando bien la creación y eliminación de memoria?

Muchas gracias! Tengo hartas dudas!! 🙃🙃

**Comment by caespinoza5** [comment]
¡Hola!

Lo que te dice al principio es básicamente una presentación. Toda la parte antes de que aparece "Command ./simulate..." básicamente te dice que estás ocupando Valgrind y qué es.

Efectivamente esos dos errores son los únicos de tu programa. Cuando te aparezca "All heap blocks were freed -- no leaks are possible" significa que no tienes memory leaks (errores de memoria), por lo que estas manejando bien la memoria. Por lo tanto, solo te queda solucionar los errores que te aparecen para tener 0 errores y 0 leaks.

**Comment by miguelramirezv** [comment]
Bacán! Muchas gracias!

Entonces si uso "valgrind /.simulate tests/..." y al final me sale:

<img width="929" alt="Screen Shot 2020-04-08 at 11 51 38 PM" src="https://user-images.githubusercontent.com/17711310/78856267-48e26880-79f4-11ea-860d-6d9d26f0a998.png">

Significa que todo esta bien? O algún otro comando que me ayude a buscar más errores (por si los hay)?

**Comment by caespinoza5** [comment]
Así es; con eso tu programa esta libre de errores y de leaks de memoria. Cabe destacar que, como se mencionó en los talleres, errores que se produzcan en el stack de memoria (por ejemplo, en lecturas o escrituras inválidas en arrays definidos en stack de memoria) no son detectados por valgrind.

En el caso de tu código, no necesitas de otros comandos dado que tu programa funciona bien. Sin embargo, si quieres utilizar valgrind para detección más específica de errores en futuras tareas, te invito a leer este post donde se explica en detalle su uso: 

https://stackoverflow.com/questions/5134891/
