### ISSUE TITLE
Clases

### ISSUE THREAD

**Issue by camaruri** [IIC2133-PUC/2020-1#6]
Hola, en la clase pasada se dijo que la clase se estaba grabando para subirla. 
Donde las están subiendo?

**Comment by Kitaps** [comment]
Aun no las subimos, pero las subiremos a Canvas/Youtube en cuanto la U nos pase la cuenta.

**Comment by Kitaps** [comment]
> Estimad@s:
> 
> Acá les dejo el link a los dos videos de las clases pasadas:
> 
> Clase 1: https://youtu.be/lAjpFcZSdkY
> 
> Clase 2: https://youtu.be/OubQZldZIo4
> 
> Pensaba agregarlos al Github pero aún no puedo hacerlo. La lista de los links a todos los videos se encontrará en un archivo README.md en la carpeta de las clases del respositorio en Github del curso.
> 
> Cuando pueda hacer esto también les subiré las slides de la clase pasada.
> 
> Nos vemos mañana!
> 
> - Vicente

Ahí esá tu respuesta ;)
