### ISSUE TITLE
Test complejos - Tarea 0

### ISSUE THREAD

**Issue by josefinabengoa** [IIC2133-PUC/2020-1#61]
Hola! 

En la issue #29 dijeron que iban a subir tests más complejos para probar que funcione bien nuestra tarea, ya que la corrección se iba a hacer con archivos grandes (o eso tengo entendido). 
¿Los van a subir? Para ver si en estos casos nuestras tareas funcionan bien y corregir lo que sea necesario. 

Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Pronto se subirá un anuncio respecto a eso.
