### ISSUE TITLE
Tips para ejecución de Tareas

### ISSUE THREAD

**Issue by caespinoza5** [IIC2133-PUC/2020-1#62]
¡Hola!

Para ayudarlos en la tarea 0 (y futuras tareas), mencionaré un par de cosas útiles para que puedan asegurar que les irá bien. En siding se acaban de subir tests grandes, junto con sus soluciones respectivas. Responderé algunas dudas comunes que surgen sobre la corrección:

- **_¿Cómo sé si mi programa toma menos de 10 segundos?_**

Asumiendo que están evaluando el test _X.txt_ ubicado en la carpeta _tests/large/_, el comando que ejecutaremos es el siguiente:

`time ./simulate tests/large/X.txt > out.txt`

Al usar este comando, aparecen 3 tiempos: real, user y sys. El tiempo que debe ser menos de 10 segundos es el **real**.

- **_¿Qué pasa si en mi computador el programa toma menos de 10 segundos pero en el del ayudante corrector no?_**

Los tests fueron creados con un gran margen de tiempo: Si al ejecutar los tests grandes tu computador se está demorando cerca de los 10 segundos, es probable que alguna operación puedes optimizar. Además, las máquinas en donde se ejecutarán las tareas son bastante rápidas, por lo que probablemente se demorará un tiempo similar o menos que en tu computador.

- **_¿Que el programa tome menos de 10 segundos, se evalúa con o sin valgrind?_**

Para ver si su programa es eficiente y se ejecuta en menos de 10 segundos, se evalúa primero sin valgrind. Luego, para ver que esté libre de errores y leaks de memoria, se ejecuta nuevamente con valgrind, sin límite de tiempo. Cabe mencionar que si su programa no ejecuta antes de los 10 segundos sin valgrind, no se ejecuta con valgrind, por lo que no tendría puntaje asignado por ausencia de leaks y de errores (con ese test particular).

- **_¿Cómo puedo asegurar que el output de mi programa es correcto?_**

Para esto, pueden usar el comando `diff`. Por ejemplo, para comparar el resultado para el test grande test00.txt (asumiendo que este está en la carpeta tests/large/), pueden ejecutar:

`./simulate tests/large/test00.txt > out.txt`

`diff tests/large/logs/out00.txt out.txt`

Si el comando anterior no imprime nada, significa que su output es exactamente igual al esperado, por lo que es correcto. Si imprime algo, significa que está imprimiendo las diferencias, por lo que estaría incorrecto. En caso de que, al imprimir la diferencia, los dos archivos aparenten ser iguales, pueden probar correr el mismo comando con el flag `-b`, de la siguiente manera:

`diff -b tests/large/logs/out00.txt out.txt`

El cual no imprimirá nada si es que los archivos son iguales en contenido.

- **_¿Se asigna puntaje si mi output difiere con el output subido?_**

En el caso particular de esta tarea, el output es único por input. Por lo tanto, que el output sea distinto significa que el algoritmo es incorrecto, por lo que **no se asigna puntaje**. Cabe mencionar que si el output es incorrecto, tampoco se asigna puntaje por valgrind a ese test.

- **_¿Se evaluará con los mismos tests que nos subieron?_**

Los tests subidos son tests de referencia, por lo que **no se evaluará con los mismos**. Sin embargo, para los tests unitarios que prueban una función particular (los que fueron entregados con el repositorio), los tests con que se evaluará probará la misma función. Para los tests grandes, pueden asumir que el tamaño de input será similar, por lo que si su código se ejecuta antes de los 10 segundos y genera un output correcto, es 99.99% probable que también tendrá un output correcto con los tests a evaluar.

- **_Sospecho que mi programa funciona bien. ¿Hay alguna manera de ejecutar mi programa para muchos tests?_**

¡Si! En la consola de comando bash, pueden hacer un loop por todos los tests. Si ejecutan el siguiente comando:

`for i in {00..05}; do time ./simulate tests/large/test$i.txt > out.txt ; diff tests/large/logs/out$i.txt out.txt; done`

Con esto, por cada test grande están generando su output, tomando el tiempo y comparándolo con el output esperado. Si es que lo que se imprime en pantalla son solo los tiempos de ejecución (no muestra diferencias entre archivos), y además los tiempos "real" son menos de 10 segundos, tu programa funciona bien.

**Comment by atroncoso2** [comment]
Respecto de la sección de 
¿Cómo puedo asegurar que el output de mi programa es correcto?

Al ejecutar _diff_ me dice que todas las líneas son distintas a pesar de que a simple vista se ven exactamente iguales. Investigué un poco y me di cuenta que es probable que los saltos de línea que estoy utilizando sean distintas, lo que coincide con que al ejecutar _diff -b_ me dice que no hay diferencias. ¿Es válido si al ejecutar _diff -b_ me dice que no hay diferencias?

**Comment by caespinoza5** [comment]
Hola @atroncoso2 ,

Efectivamente utilizar `diff -b` es válido, ya que algunas veces la forma en que se representan los términos de línea puede variar (Entre CRLF y LF). Gracias por tu aporte; lo agregaré al issue.

**Comment by Arcoirisky** [comment]
Saben qué es lo que intenta hacer cada large test? 
Onda, por dar un ejemplo, el test 0 se dedica a liberar pods a montones(? 

Para poder diferenciar porqué algunos me dan diferentes y otros no 😪

**Comment by caespinoza5** [comment]
Los tests large miden eficiencia, por lo que no hay algo en particular que intente hacer cada test.

Para debuggear por qué algunos te dan y otros no, te recomiendo debuggear agregando printfs a tu programa y comparando manualmente algunas diferencias. Por ejemplo, si la primera línea que difiere es al abordar un POD, y difiere el ID 2, ¿Cuánto se ingresó ese pasajero? ¿La cola a la que abordó ese pasajero se cerró en algún punto? ¿El terminal en que ingresó ese pasajero se clausuró en algún punto?

Otra cosa que recomiendo es que por cada acción, verifiques que lo que queda está correcto. Por ejemplo, al abordar, verificar manualmente que la cola queda con n - 8 personas. Al clausurar un terminal con m personas, verificar que la cola que creas tiene ese largo antes de reingresar al otro terminal.

**Comment by Arcoirisky** [comment]
@caespinoza5 claro, que el problema es q solo muere en los grandes xD con los chicos voy 10/10 pero seguiré hoy tu consejo Thxs

**Comment by VicenteMerino** [comment]
Hola, me queda una duda. Cuál es la diferencia entre memory leaks y errores de memoria?

**Comment by vichoeq** [comment]
@VicenteMerino 

Un leak es memoria que solicitaste (malloc) y no devolviste (free). El tener leaks no hace que tu programa sea menos correcto, pero es un problema para el sistema operativo.

Un error de memoria puede ser uno de los siguientes:
* Acceso / asignación a una dirección de memoria inválida (como al salirse de un arreglo)
* Uso de una variable sin inicializar

En general los errores de memoria generarán bugs y comportamiento impredecible en tu programa, como "a veces funciona y a veces no" o el clásico "en mi PC funcionaba".

Cualquiera que sea, valgrind lo va a reportar y describir detalladamente, asi que preocupate de arreglarlos.

Saludos

**Comment by diegovaras97** [comment]
Hola, donde puedo encontrar los tests grandes?

**Comment by caespinoza5** [comment]
Puedes encontrarlos en el Siding del curso > Material Tareas > Tests grandes T0.
