### ISSUE TITLE
Output Tarea 0 Terminales Cerrados

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#63]
Hola! Leyendo la tarea entendí que cuando se cierra un terminal, el output debiera ser del estilo:

Terminal 0
Gate 0: 0
Gate 1: 0
Gate 2: 0

Pero los logs del tests/units/4_terminal_transfer.txt no imprime el terminal cerrado. Está bien? Los terminales que se cierran no hay que imprimirlos? Siguiendo la misma lógica, las Gates cerradas tampoco hay que imprimirlas?

Muchas gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Efectivamente, ni los terminales cerrados ni las gates cerradas se imprimen. Solo se imprime cuando hay un abordaje, y al finalizar la ejecución de la simulación, en donde te saltas los terminales cerrados y las puertas cerradas.

¡Saludos!

**Comment by Arcoirisky** [comment]
Si un terminal/puerta está abierto con 0 personas ahí sí debo imprimirlo no?

**Comment by caespinoza5** [comment]
Así es.
