### ISSUE TITLE
Cambios inesperados en mi programa

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2133-PUC/2020-1#64]
Hola, estoy teniendo un cambio muy raro en algunos valores de mi programa. 
Lo que estoy intentando hacer es crear un atributo del terminal en el que se va a guardar un arreglo de punteros a cada puerta de ese terminal. El terminal y las puertas se están creando bien, sin embargo cuando pido un print después de crear todos los terminales con sus puertas para revisar que esté todo bien, me di cuenta de que los valores de gate_number se cambian para algunas puertas, cuando son mas de 3 puertas, se cambia el gate_number de la primera puerta, y a medida que va creciendo el número de puertas por terminal, van creciendo los cambios inesperados.
Adjunto foto del output y del código donde creo los structs gate y terminal.
Sin embargo cuando probe el mismo codigo con valgrind, no me paso esto, y obtuve el resultado esperado.

<img width="604" alt="Captura de Pantalla 2020-04-09 a la(s) 20 57 45" src="https://user-images.githubusercontent.com/42253078/78952935-26f4ee80-7aa5-11ea-8469-52b72984eab2.png">
<img width="773" alt="Captura de Pantalla 2020-04-09 a la(s) 20 57 31" src="https://user-images.githubusercontent.com/42253078/78952936-26f4ee80-7aa5-11ea-8831-3e915059fc79.png">

**Comment by vichoeq** [comment]
Valgrind simula tu programa en un ambiente distinto, por lo que **si tiene problemas de memoria** es posible que obtengas resultados distintos. Qué dice valgrind respecto a los problemas de memoria?
