### ISSUE TITLE
Inputs

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#65]
Hola, podemos asumir que los inputs que nos dan son correctos? (No se generarian errores de borde o cosas asi)

**Comment by caespinoza5** [comment]
¡Hola!

Así es; todos los supuestos que se mencionaron en el enunciado se cumplen. Entre ellos:

- No se cerrarán puertas cerradas.
- No se cerrarán terminales cerrados.
- Si se cierra una puerta en un terminal significa que al menos hay una más abierta en el terminal.
- Al clausurar el terminal, el terminal al que se mueven estará abierto.
- No habrá láser en un índice inexistente en la cola.
- Si se aborda una cola, hay al menos 8 personas para abordar.

**Comment by VicenteMerino** [comment]
Y si me clausuran un terminal, no me pediran que ingrese a ese terminal?

**Comment by caespinoza5** [comment]
Correcto!
