### ISSUE TITLE
Terminales Clausurados

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2133-PUC/2020-1#66]
Hola:
Cuando se clausura un terminal, si se una persona ingresa al terminal; simplemente no lo ingresamos?
En ese caso, de igual forma mostramos en consola que ingreso, (dejamos el printf donde esta).
Gracias de antemano.

**Comment by caespinoza5** [comment]
¡Hola!

Una persona no ingresará a terminales clausurados, por lo que puedes ignorar ese caso. Recuerda que los printf es solo cuando se aborda o cuando finaliza la ejecución de tu programa.
