### ISSUE TITLE
Tarea 0, cierre de puertas

### ISSUE THREAD

**Issue by fjcroquevielle** [IIC2133-PUC/2020-1#68]
Puedo asumir que al cerrarse una puerta, independiente de cual sea, pueda cambiar el nombre de las que quedan?. Por ejemplo, si se cierra la puerta 0, reparto los pasajeros que conformaban dicha puerta, y después la puerta 1 pasará a ser la puerta 0, y así sucesivamente.

**Comment by caespinoza5** [comment]
No te recomiendo hacer eso, ya que al momento de abordar la puerta 1 más adelante, tendrás que hacer conversiones internas de índices (ya que la puerta 1 sería tu puerta 0 en ese caso), y además, al momento de imprimir lo que se solicita en TITANIC LOG, también tendrías que hacer todas las conversiones pertinentes.
