### ISSUE TITLE
Tarea 0 Error

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2133-PUC/2020-1#69]
Hola al imprimir los valores de la linked list me arroja el siguiente error 
`Conditional jump or move depends on uninitialised value(s) at 0x108B21: list_print (linked_list.c:44)` 
El programa igual funciona como es esperado, pero me gustaría que al correr valgrind diga 0 errores, alguien sabe porque podría tener este error?
Saludos

**Comment by cacosandon** [comment]
Hola!

Tiene pinta de que cuando creas un nodo no estás inicializando su valor (ya sea de el o del nodo siguiente) como NULL.

Me cuentas como te va!

**Comment by ljrodriguez1** [comment]
Exactamente estaba creando un nodo con su valor no inicializado, muchas gracias
