### ISSUE TITLE
[Tarea 0] Error en enunciado

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#7]
Hola!

Viendo el ejemplo del evento clausura me surgio una duda con el ejemplo. En el caso de los adultos se agregan a la nueva fila como B -> G -> C . Supongo que es porque B y G estan en un nivel mas adelante de las filas que C. Pero luego con los robots se agregan a la fila como F -> H, pero H estaba mas abajo en las filas. Entonces deberiamos respetar algun orden especifico (izq a derecha) o por nivel de fila (primero todas las posiciones 0 y luego las 1 y asi sucesivamente), o realmente no importa mientra se respeten las edades?

Gracias

**Comment by vichoeq** [comment]
Toda la razón, el ejemplo está mal. Los robots efectivamente deberían ordenarse H -> F, subiremos una versión corregida cuanto antes.

**Comment by vichoeq** [comment]
Listo!

**Comment by danustilovsky** [comment]
Gracias!!

**Comment by viantirreau** [comment]
Hola!
No estoy seguro si entendí bien :thinking: 
En el ejemplo asociado al comando `CLAUSURA`, cuando termino de agregar al adulto C, solo me restan las colas "robot F en puerta 2" y "robot H en puerta 3". Como el índice de la puerta 2 es menor que el 3, y ambos robots ahora se encuentran primeros en la fila, pienso que el orden que se especificaba antes de actualizar el enunciado era el correcto, es decir, F -> H.
¿Cómo sería otra interpretación?
Gracias!!

**Comment by miguelramirezv** [comment]
Hola! A mi no me quedó tan claro, lo sigo entendiendo como @viantirreau y que debería ser F->H. Lo que entiendo es que:

- primero hago una fila solo de los niños 
- Lo anterior lo hago así: fila 0 tiene niño primero? sí, lo pongo en la fila. fila 1 tiene niño primero? sí, lo pongo después en la fila. Etc, fila 0 tiene niño segundo? sí, lo pongo en la fila. fila 1 tiene niño tercero? no, queda hasta ahí y ahora ese va a ser mi primer lugar desde donde empiezo a ver los adultos
- Ojo que si el primer adulto de la fila 0 estaba en la posición 20 y el primer adulto de la fila 1 estaba en la posición 0, entonces para la fila de los adultos estos pasan a la posición 0 de las nuevas filas. Es decir, siempre el primer adulto de la fila 0 (si es que hay), entra primero el de la fila 1 
- después, las filas van a quedar partiendo de un adulto o robot o vacías. De esas filas hago una fila de los adulto y la concateno al final de la de los niños
- por último, me quedan filas que tiene solo robots o están vacías. Ahí hago 

Está bien? O debiera ser como por niveles que eso no lo entiendo muy bien.

**Comment by viantirreau** [comment]
Hola!
Yo lo entendí así:
- Toma todas las filas (de izquierda a derecha)
- Parte en cada una sacando el pasajero al principio de la cola. Mételo a la mega-fila en la posición adecuada. Si no hay pasajero, ignora esta fila y continúa con la que viene a su derecha.
- Repite hasta que todas las filas queden vacías

Creo que la diferencia está en el segundo paso: **siempre** sacas al pasajero en la _head_, y luego ves en qué posición de la gran fila debiese ir.

Saludos!

**Comment by Arcoirisky** [comment]
WAT?! No son un merge 3-way de todos los niños primero de todas las filas, luego todos los adultos de todas las filas y luego todos los robots de todas las filas?

**Comment by Arcoirisky** [comment]
onda, si tengo 3 filas y la fila 2 se quedo sin niños entonces el adulto espera hasta que todos los niños se pongan al frente de él para entrar?

**Comment by caespinoza5** [comment]
Lo que plantea @viantirreau es correcto; iteras sobre todas las filas, y por cada fila sacas lo que esté al frente (si es que hay), lo colocas en la mega fila y luego repites hasta que no hayan pasajeros. Visualmente, con la fila que está en el enunciado: 

![Untitled](https://user-images.githubusercontent.com/26394948/79052717-7141b100-7c06-11ea-8ab9-42b9f1b00cf5.png)

Inicialmente nuestra nueva cola estará vacía. La dividiremos por paréntesis para ver niños, adultos y robots, es decir, ()->()->(). Luego:

Queda gente en el terminal? Si. Iteremos:
Puerta 0: Sacamos a A. Nueva cola: (A)->()->()
Puerta 1: Sacamos a B. Nueva cola: (A)->(B)->()
Puerta 2: Sacamos a D. Nueva cola: (A->D)->(B)->()
Puerta 3: Sacamos a G. Nueva cola: (A->D)->(B->G)->()
Queda gente en el terminal? Si. Iteremos:
Puerta 0: No queda nadie.
Puerta 1: Sacamos a C. Nueva cola: (A->D)->(B->G->C)->()
Puerta 2: Sacamos a E. Nueva cola: (A->D->E)->(B->G->C)->()
Puerta 3: Sacamos a H. Nueva cola: (A->D->E)->(B->G->C)->(H).
Queda gente en el terminal? Si. Iteremos:
Puerta 0: No queda nadie.
Puerta 1: No queda nadie.
Puerta 2: Sacamos a F. Nueva cola: (A->D->E)->(B->G->C)->(H->F).
Puerta 3: No queda nadie.
Queda gente en el terminal? No.

La nueva cola resultante es la que se inserta en el terminal t2.

**Comment by Arcoirisky** [comment]
Y luego entran en orden niños, adultos y robots BAIA 
THXS

**Comment by miguelramirezv** [comment]
Gracias! No lo había entendido bien!!
