### ISSUE TITLE
Referencias vs valores 

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#70]
Hola, tengo una duda
En C ¿cómo puedo entregar valores de variables en vez de una referencia a estas? 
Me explico:

Supongamos que tengo a la persona P y quiero crear una nueva persona S con el id + tipo de P... si bien creo a S con un malloc y todo, tengo la sospecha de que el id de S no es simplemente el valor del id P, sino que está asociado a P a pesar de ser de S

¿Se entiende? Onda, si luego libero P y en su posición ubico a otra persona K ¿puede ser que los valores de S apunten a los valores de K? 

Literal estaría haciendo 
S -> id = P -> id;
¿Estoy pasando el valor del id de P o estoy haciendo una referencia? D:

**Comment by vichoeq** [comment]
Hola,

Como se mencionó en el taller, en C **todo** se pasa por valor. Por eso para pasar "referencias" lo que hacemos es pasar, por valor, la dirección de memoria de un dato.

Si lo que estás asignando no es un puntero, entonces no es una referencia. Por ejemplo el ID que mencionas, el valor que tenga va a ser el de la variable en el momento de la asignación, no importa lo que le pase a la variable después.

Si lo que asignas es un puntero, AHI si vas a tener problemas si es que luego eliminas la referencia original.

¿Se entiende?

**Comment by caespinoza5** [comment]
Si copias y pegas el siguiente ejemplo en https://www.onlinegdb.com/online_c_compiler puedes ver más claramente la diferencia:
```
#include <stdio.h>
#include <stdlib.h>

// Un globo tiene diametro
struct globo
{
    int diametro;
};

typedef struct globo Globo;

// Una persona tiene un globo y edad
struct persona{
    int edad;
    Globo* globo;
};
typedef struct persona Persona;

int main()
{
    Persona* p1 = malloc(sizeof(Persona));
    Persona* p2 = malloc(sizeof(Persona));
    p1->edad = 3;
    p2->edad = p1->edad;
    printf("p1 edad: %d, p2 edad: %d\n", p1->edad, p2->edad);
    p1->edad = 4;
    printf("p1 edad: %d, p2 edad: %d\n", p1->edad, p2->edad);
    p1->globo = malloc(sizeof(Globo));
    p1->globo->diametro = 4;
    p2->globo = p1->globo;
    printf("p1 diametro globo: %d, p2 diametro globo: %d\n", p1->globo->diametro, p2->globo->diametro);
    p2->globo->diametro = 5;
    printf("p1 diametro globo: %d, p2 diametro globo: %d\n", p1->globo->diametro, p2->globo->diametro);
    return 0;
} 
```
