### ISSUE TITLE
Datos Big

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#71]
Hola, hay algo que signifique cada test?

En mi caso solo me tiró igual con el test2 (al igual que a una compañera), lo cual me parece raro, considerando que las magnitudes de los datos son gigantes, que justo uno me tire que son iguales, y los otros llegan a tener mas de 100000 lineas distintas me parece demasiado extraño. Alguna idea de como podria debuguear esto?

Saludos

**Comment by Arcoirisky** [comment]
Agrego que son todos demasiado grandes como para alcanzar a ver los prints de número de listas y otras variables para el debuggeo ;—; ya lo intenté y llevo horas en un archivo para no ver nada ( ´Д`)y━･~~

**Comment by caespinoza5** [comment]
En general, para debuguear recomiendo encontrar la línea en que se produce el cambio.

Como primer paso, si se produce el cambio en un abordaje de PODS, por ejemplo, pueden ir al archivo de input, y eliminar todas las líneas siguientes después de ese abordaje (excepto END). Así el programa se ejecuta hasta la línea que ocurre el cambio.

Luego, una vez que tienen esto, pueden ver los pasajeros que abordaron el POD. entonces, si tienen id1, id2, ..., id8, recomiendo ver en qué punto ingresaron estos pasajeros, y si las puertas a las que ingresaron fueron cerradas, o si los terminales a los que ingresaron fueron clausurados. De tal manera, pueden ver si al ser reingresados fueron reingresados correctamente.

Otra cosa que pueden hacer para solo imprimir la información más concisa es imprimir sólo si se trata de los IDs que son distintos, o de las puertas o terminales que fueron involucrados; esto lo pueden hacer con un simple if.

También cuando ocurre alguna acción que involucre a una cola, pueden hacer un for por todos los elementos de la cola y asegurarse que respeten el orden (que no hayan adultos o robots en frente de niños, y que no hayan robots frente a los adultos). Si no respetan el orden, pueden hacer un printf("ERROR\n") y después simplemente buscan el "ERROR" en el archivo de output.

Por último, cuando hagan TITANIC LOG, vean que las cantidades de personas por puerta y por terminal son las mismas. Si el número de personas en el terminal es la misma que se espera, pero las puertas tienen distintos números, probablemente hay un error de ingreso en el terminal. Si las cantidades en una cola es la misma que se espera al finalizar la ejecución, pero el orden de las personas es distinto o hay distintas personas, probablemente hay un error en el ingreso a la cola (puede haber problemas de consideración de niños, adultos o robot).

Espero que les sea útil esta información.

**Comment by vichoeq** [comment]
La otra opcion en vez de borrar lineas es poner un END prematuro: las lineas que haya abajo no serán leidas.

**Comment by VicenteMerino** [comment]
Mi caso al menos, los aordajes se me imprimen igual, pero los pasajeros que quedan me empiezan a fallar, lo que me hace pensar que el problema en clausura, cierre o laser, pero es complicado encontrar que acción especifica del input provocó esto, ya que las ids se imprimen despues de que se procesó todo el input. En todo caso los largos si son iguales y seguramente es lo que mencionas en el último punto (los largos de ambos archivos son los mismos).

**Comment by Arcoirisky** [comment]
Lo raro de todo es que si funcionan en el test2. Ese es el mayor problema para mi. Ya que en ese test hay abordajes, lasers, cierres y clausuras

**Comment by atroncoso2** [comment]
A mi también me funciona perfecto el test2 mientras que los otros no... Si me puedes avisar cuando lo soluciones lo agradecería mucho.

**Comment by Arcoirisky** [comment]
@atroncoso2 mira la issue #7

**Comment by Arcoirisky** [comment]
Entendí mal clausura y ahora me van más tests

**Comment by VicenteMerino** [comment]
@atroncoso2 Eso mismo, yo creo que igual debes tener mal la funcion clausura, revisa bien en el enunciado como es la entrada al clausurar un terminal y como lo estás haciendo tu.

**Comment by atroncoso2** [comment]
Si, lo estoy revisando ahora. Hasta ahora calza perfecto con mi problema. 
Muchas gracias!
