### ISSUE TITLE
Valgrind en mac

### ISSUE THREAD

**Issue by camaruri** [IIC2133-PUC/2020-1#73]
No he podido usar valgrind en MAC, no se si enverdad se puede usar aca o necesariamente hay que usar virtualBox. 
Lo otro que queria saber es si virtualBox es muy necesario para MAC.
trate de instalar valgrind con brew install valgrind pero no me funciono.
Gracias

**Comment by miguelramirezv** [comment]
Hola! Yo tengo mac y la lamentablemente única forma para usar valgrind es la máquina virtual 👎 De hecho, yo la tengo solo para eso!
