### ISSUE TITLE
Duda .h Structs

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#74]
Hola, estaba creando mis Structs y tratando de seguir el ejemplo del taller para cada una cree un archivo .h y .c . El problema es que para poder pedir memoria debo hacer incluide de los .h entre las diferentes structs y me quedo un problema como de "llamados circulares".

Hay alguna forma de arreglar esto? o tal vez es correcto poder hacer un gran archivo con todos los structs?

Gracias

**Comment by vichoeq** [comment]
Hola, si tu programa tiene un ciclo en los includes, no lo vas a poder compilar. Tienes que separar los archivos de manera de que no se te generen ciclos. Si, poner todos los structs en un mismo archivo va a funcionar, pero eso es un caos.

Mi recomendación es separar los structs de manera jerárquica, y hacer los includes de mas chico a mas grande:

Por ejemplo, mi modelación para esta tarea fue 

* personas
* colas de personas
* puertas
* terminales
* titanic
* main

Cada uno de estos hace include del anterior :)
