### ISSUE TITLE
Eficiencia de la tarea

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#75]
Hola,

Con los tests grandes me percaté de que elegí una pésima forma de implementar la tarea en términos de eficiencia. Solo utilicé listas ligadas para guardar toda la información. Quería ver si puedo hacer unos cambios e implementar un struct tipo matriz de arreglos como la del ejemplo del taller de C que nos hicieron. Quería saber si hacer esto es una buena idea, o algún otro consejo para mejorar la eficiencia.

Saludos y gracias de antemano

**Comment by viantirreau** [comment]
Hola!
Lo que dices suena muy buena idea, todo lo que esté definido al inicio de la ejecución con tamaño fijo (que no se necesita eliminar ni agrega una vez que el programa corre), lo puedes almacenar en _arrays_ y ganar el dulce acceso en O(1). Ojo que una matriz tiene a todas sus filas con igual cantidad de columnas. Si hicieras esto acá, probablemente tendrías harto desperdicio de memoria por tener celdas vacías en "filas" que simplemente son más cortas.

**Comment by arbiocanpion** [comment]
Hola @matumartinez 
Como indica @viantirreau hacer una matriz de arreglos no considero que sea la idea mas óptima de implementar la solución en esta tarea, ya que como tienes que cada terminal tiene diferente numero de puertas, puede usar mucha memoria innecesariamente. Como recomendación te diria que te atrevas a buscar soluciones un poco menos tradicionales, ya que esa es una de las ventajas de c, al no haber nada definido, tu puedes generar tus propias estructuras de datos  que se adapten a tu necesidad. Por último te recomendaria fuertemente basarte en el material que les subimos en el taller 0 e ir sacando ideas de ahí  (esta bien documentado todo). 

P.d. Lo de las listas ligadas es útil hasta cierto punto, pero abusar de ellas las vuelve un arma de doble filo.

**Comment by tpcantergiani** [comment]
Siguiendo con esta pregunta:
Yo solo ocupe listas ligadas para las colas de las puertas, intentando hacer mas eficiente la tarea.
El resto lo hice con listas de punteros, para irme guiando entre terminales, gates y colas.
Con los  test chicos funciona perfecto.
Pero para los test grandes, los tiempos son enormes:
![image](https://user-images.githubusercontent.com/44327650/79054398-6e4cbd80-7c12-11ea-98bf-5a6a4760ca8c.png)
A alguien mas le pasa?
Sera problema de mi computador>
Llevo varios días intentando bajar la eficiencia, sin resultados.

**Comment by matumartinez** [comment]
Se me ocurré que yo hice algo parecido a lo tuyo, pero a mi los tests me demoran aprox 22 minutos, no sé si el computador tenga algo que ver eso si.

**Comment by caespinoza5** [comment]
Si están teniendo tiempos muy largos, recomiendo que revisen las listas ligadas del taller 0, en la parte de structs. Revisen bien, en esa estructura, cuánto se demora agregando elementos en los inicios y finales de la lista. Vean si con eso pueden guiarse.
