### ISSUE TITLE
test a manito ejemplo enunciado Clausura

### ISSUE THREAD

**Issue by Arcoirisky** [IIC2133-PUC/2020-1#76]
Hi~ hice un test para el ejemplo del enunciado clausura o: Está horrible pero funciona xD
```
2
4
1
INGRESO 0 0 0
INGRESO 0 1 0
INGRESO 0 2 0
INGRESO 0 3 0
INGRESO 0 4 0
INGRESO 0 5 0
INGRESO 0 6 0
INGRESO 0 7 0
INGRESO 0 8 1
INGRESO 0 9 1
INGRESO 0 10 1
INGRESO 0 11 1
INGRESO 0 12 1
INGRESO 0 13 1
INGRESO 0 14 1
INGRESO 0 15 1
INGRESO 0 16 2
INGRESO 0 17 2
INGRESO 0 18 2
INGRESO 0 19 2
LASER 0 0 1
LASER 0 0 1
LASER 0 0 1
LASER 0 0 1
LASER 0 1 0
LASER 0 1 0
LASER 0 1 2
LASER 0 2 2
LASER 0 2 2
LASER 0 3 0
LASER 0 3 0
LASER 0 3 0
CLAUSURA 0 1
END
```
Output:
```
TITANIC LOG
TERMINAL 1
GATE 0: 8
0
2
6
9
15
13
19
18
END LOG
```
para el que quiera y lo necesite o:

**Comment by danustilovsky** [comment]
@Arcoirisky Hola!

Una preguntita, en el output de tu test no deberia ser: 
TITANIC LOG
TERMINAL 1
GATE 0: 8
0
2
6
9
13
15
18
19
END LOG

Ya que 13 esta en una puerta de menor indice que 15, y lo mismo con 18 y 19?

Gracias!

**Comment by Arcoirisky** [comment]
Es por la issue #7 que es así 
Sacas a un ente si o si de cada puerta y lo metes al terminal nuevo

**Comment by danustilovsky** [comment]
Gracias!!

**Comment by caespinoza5** [comment]
Para ser más preciso con los conceptos, más que meterlo al termminal nuevo de inmediato, lo metes a la cola que estás armando. Una vez que colocas a todos en la cola que estás armando, metes esta cola en el terminal nuevo.

**Comment by Arcoirisky** [comment]
@caespinoza5 hay alguna diferencia?

**Comment by caespinoza5** [comment]
Sí.

Imagina tienes dos terminales, T0 y T1. Supongamos que R = Robots y A = Adultos.
El T0 Se ve así:
T0
Cola 0: R1
Cola 1: A1

El T1 Se ve así:
Cola 0: A2
Cola 1: 

Ahora, tiene clausura(T0, T1). 
- Sin hacer la fila auxiliar, primero ingresas R1 y luego A1. Te quedaría lo siguiente:
Iteración 1: Ingresamos R1 a T1.
Cola 0: A2
Cola 1: R1
Iteración 2: Ingresamos A1 a T1.
Cola 0: A2
Cola 1: A1->R1

- Haciendo la fila auxiliar, ingresas R1 y luego A1 ordenadamente a la fila auxiliar, quedándote (A1)->(R1). Luego ingresas esta fila al terminal T1. Te quedaría lo siguiente:
Iteración 1: Ingresamos A1 a T1.
Cola 0: A2
Cola 1: A1
Iteración 2: Ingresamos R1 a T1.
Cola 0: A2->R1
Cola 1: A1

¿Se entiende?

**Comment by Arcoirisky** [comment]
100/10 
Yo te doy la diferencia que encontré antes de leerte
Con tu forma mi tarea está completa 
Te amo
Te deseo todos los memes de gatitos del mundo
