### ISSUE TITLE
Error Valgrind

### ISSUE THREAD

**Issue by danustilovsky** [IIC2133-PUC/2020-1#77]
Hola, cuando corro mi programa con Valgrind me sale que no tengo ningun error o leak pero me aparece esto: "error calling PR_SET_PTRACER, vgdb might block". A que se puede deber?

Gracias

**Comment by vichoeq** [comment]
Ese es un pequeño error que tiene valgrind al correrlo en Windows, pero no afecta su comportamiento (hasta donde hemos notado).

En resumen, nada de que preocuparse :)
