### ISSUE TITLE
Error Valgrind

### ISSUE THREAD

**Issue by figarcia3** [IIC2133-PUC/2020-1#78]
Hola me aparece este error y main.c no tiene cambios.
![Captura de pantalla de 2020-04-11 19-19-49](https://user-images.githubusercontent.com/48328327/79056956-c216d100-7c29-11ea-8c36-63224aca467a.png)

**Comment by caespinoza5** [comment]
¡Hola! Dos cosas:

Los `logs` son los outputs esperados de su programa, para que ustedes puedan ver si su programa ejecuta correctamente; no son los input. Por lo tanto, el archivo que debes llamar es, en este caso, '2_terminal_enqueue.txt'.

En segundo lugar, el path de la primera carpeta no debiese tener el slash inicial. Es decir, para ejecutar tu programa debes llamarlo como` ./simulate tests/unit/2_terminal_enqueue.txt`. Prueba con eso.

¡Saludos!

**Comment by figarcia3** [comment]
gracias!
