### ISSUE TITLE
Problema diff

### ISSUE THREAD

**Issue by fabarros** [IIC2133-PUC/2020-1#79]
Hola! estoy testeando mi código y en cada large test, cuando uso diff o diff -b para comparar me falla (imprime cosas), sin embargo estuve revisando los out.txt y son iguales, tiene hasta la misma cantidad de líneas. Hay alguna otra forma de probar el código?
 
Gracias, Saludos!

**Comment by vichoeq** [comment]
Curioso. Podrías adjuntar tu output y el archivo con el que lo estás comaparando? A ver si es otra cosa.

**Comment by dasolari** [comment]
Me pasa lo mismo, al hacer diff o diff -b se me imprimen los id de muchos pasajeros, pero al comparar la cantidad de líneas entre los archivos, me dice que tienen la misma cantidad y al comparar los outputs, se ve que son iguales.

**Comment by caespinoza5** [comment]
Recomiendo revisar si están teniendo la misma cantidad de espacios. Imprimir `GATE 0: 3` es distinto que imprimir `GATE 0: 3 ` o `GATE 0 : 3` por ejemplo.

Si pueden, respondan a esta misma issue adjuntando una imagen de lo que les muestra en diferencias, para ver si podemos orientarlos mejor.

**Comment by fabarros** [comment]
Finalmente el problema era mi código. En particular la función laser efectivamente eliminaba un pasajero pero no al pasajero correcto, entonces tenía la misma cantidad de líneas (misma cantidad de pasajeros) pero desde que aparecían los lasers empezaban las diferencias en mi output.

Gracias! Saludos.

**Comment by dasolari** [comment]
Me di cuenta que también me pasó lo mismo que a @fabarros. La función láser estaba eliminando a la persona equivocada.
Gracias!!
