### ISSUE TITLE
Código base [T0]

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#8]
Tengo entendido que en los semestres anteriores subían un código base.  Nos darán uno o no? Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Tal como aparece en el enunciado, los repositorios bases fueron creados durante la madrugada del día de hoy. Debieses tener acceso a tu repositorio base accediendo a `https://github.com/IIC2133-PUC/T0-2020-1-{usuario}`, reemplazando `{usuario}` por tu nombre de usuario de Github.

En caso de no haber respondido la encuesta donde se solicitaban los nombres de usuario, debes enviar un correo a caespinoza5@uc.cl indicando tu nombre de usuario.

Me avisas cómo te va.

**Comment by Kitaps** [comment]
https://github.com/IIC2133-PUC/T0-2020-1-chocopiano

**Comment by chocopiano** [comment]
La pifie total. Muchas gracias jajajaja!
