### ISSUE TITLE
Duda informe

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#80]
Hola, para los eventos debemos calcular la complejidad según nosotros programamos cada uno, o hay alguna regla general que deba cumplir para todos. Además que tan precisa debe ser la explicacion? Si tengo por ejemplo dos for basta decir que O(n²) o O(n*m) o debo ir calculando las sumatorias por ejemplo, como se hacia para selection sort?

**Comment by VicenteMerino** [comment]
Además hay que calcular la complejidad tanto en tiempo como en memoria?

**Comment by vichoeq** [comment]
Hola

Una idea general sirve perfecto, como dices por ejemplo dos for basta decir que O(n²). Lo importante es que el razonamiento sea correcto.

No es necesario calcular complejidad en memoria :)

**Comment by miguelramirezv** [comment]
Hola! Tengo cuatro preguntas:

Los eventos son ingreso, abordaje, etc? 

El análisis es solo sobre el tiempo?

Se espera un mínimo de extensión o si puedo explicarlo todo en 1 plana está bien?

El formato de latex que mandaron, si completo bien cada ítem (ajustándolo a la tarea) está bien?

Muchas gracias!!
