### ISSUE TITLE
Error: Exec format error

### ISSUE THREAD

**Issue by NicolasCastillo24** [IIC2133-PUC/2020-1#81]
Hola!
Hasta ahora he estado trabajando desde mi compu (en una carpeta local) sin tocar el repositorio. Resulta que copie **todo** lo de esta carpeta y la subí al repositorio para luego bajarla desde mi maquina virtual y usar valgrind (No tengo un editor de texto en la MV). Pasa que desde Ubuntu me sale el error:
bash: ./simulate:  cannot execute binary file: Exec format error
al correr $ ./simulate tests/unit/...
Pero corriendo lo mismo desde la carpeta, en el mismo estado, macOS funciona bien :(

**Comment by caespinoza5** [comment]
¿Aseguraste hacer `make clean` antes de hacer `make`?

**Comment by NicolasCastillo24** [comment]
Eso era! jaja ahora entiendo lo que pasaba. Gracias!
