### ISSUE TITLE
Test Grandes

### ISSUE THREAD

**Issue by lothardp** [IIC2133-PUC/2020-1#82]
Hola, 
¿Podemos asumir que los test grandes con los que probaran si la tarea corre en menos de 10 segundos son parecidos a los que entregaron de prueba? En el sentido de que lo que "escala" es la cantidad de gente que ingresa pero no la cantidad de terminales ni de puertas por terminal. Ya que en los que nos pasaron hay miles de ingresos, pero no hay mas de 10 terminales ni 10 puertas por terminal. 
Sorry lo rebuscado de la pregunta jaja pero creo que influye en como modelamos las estructuras. 
Gracias!

**Comment by caespinoza5** [comment]
¡Hola!

Puedes asumir que se utilizarán tests parecidos. Para más información respecto a la evaluación, te recomiendo que veas la issue [62](https://github.com/IIC2133-PUC/2020-1/issues/62).
