### ISSUE TITLE
Se revisará código?

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#84]
Bueno, lo que dice el titulo, el programa me corre perfect pero tengo funciones o variables que declaré pero que al final no usé pero me da lata borrar :(

**Comment by vichoeq** [comment]
Lo único que importa es funcionalidad, nadie va a leer tu código :)

**Comment by caespinoza5** [comment]
Dicho lo anterior, sí se revisará que tu código sea auténtico (creado por ti), o bien si ocupas recursos encontrados en la web o del taller, que sean correctamente referenciados (Colocando el link o el taller de donde encontraste dicho recurso). Pero en términos de puntaje, el código en sí no tiene asignado puntaje.

**Comment by tsgonzalez** [comment]
hola!
Eso de las referencias debe mencionarse en el informe?
Ya que se supone que nadie leerá nuestro código.
