### ISSUE TITLE
Acceso por indices

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#85]
Hola, mi duda es que si tengo un arreglo por ejemplo int A*[10]

y quiero acceder a A[9], qué es lo que hace C por detrás accede al valor iterando? O sencillamente encuentra el valor por indice en O(1)?

**Comment by vichoeq** [comment]
Hola, hicimos énfasis sobre esto en el taller de C,

El operador A[i] es syntactic sugar para (A + i * sizeof(int)) (en este caso es un arreglo de ints), lo que permite acceso para leer y escribir en esa dirección de memoria en O(1)
