### ISSUE TITLE
Duda complejidad clausura

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#86]
Hola, para clausura necesito la cantidad total de personas en el terminal. Aqui basta decir sea k la cantidad de personas en el terminal o tengo que decir k_m la cantidad de personas en la puerta m y tomar la suma?

**Comment by Arcoirisky** [comment]
Diría que no es necesaria la M ya que K la incluye, pero si podrías decir sea K_j la suma de m_i personas en las puertas del terminal K_j con j el índice del terminal e i el índice de puerta

En caso de querer ser más específico

**Comment by arbiocanpion** [comment]
Hola @VicenteMerino 
Como indica @Arcoirisky basta con decir sea K la cantidad de gente de la terminal clausurada. Esto debido a que como estas cerrando toda una terminal y la fusionas en una fila, realmente lo que te interesara es el numero total de gente que hay en la terminal, no el numero de personas por puerta.
