### ISSUE TITLE
Valgrind --leak-check=full

### ISSUE THREAD

**Issue by miguelramirezv** [IIC2133-PUC/2020-1#87]
Hola! Cuando uso valgrind me salen problemas de memoria:

<img width="1167" alt="Screen Shot 2020-04-12 at 12 25 18 PM" src="https://user-images.githubusercontent.com/17711310/79074183-eec5f980-7cb8-11ea-873b-603022f2ab9f.png">

Y después me dice que agregue al comando "--leak-check=full" al final para más detalles de los leaks. Pero cuando lo hago me sale esto:

<img width="1173" alt="Screen Shot 2020-04-12 at 12 25 05 PM" src="https://user-images.githubusercontent.com/17711310/79074196-056c5080-7cb9-11ea-9381-f40df1321efb.png">

Finalmente no tiene problemas de leak o no es así como funciona el comando? Y como funcionaría si no?

Gracias!!

**Comment by caespinoza5** [comment]
El comando debiese ser `valgrind --leak-check=full ./simulate <path_to_file>` . Si notas en tu output, te aparece que estás llamando mal al archivo en el segundo caso, ya que te dice "uso correcto: ./simulate PATH_TO_INPUT", mientras que tu le estás entregando dos argumentos, PATH_TO_INPUT y "--leak-check=full".
