### ISSUE TITLE
Segfault al checkear puntero nulo

### ISSUE THREAD

**Issue by mistico0121** [IIC2133-PUC/2020-1#88]
Hola, estoy complicado con esto ya que en verdad no sé que está pasando y a pesar de que estoy siguiendo tutoriales de internet, ninguno al parecer tiene este problema.

Cuando intento crear una lista ligada, debo checkear si la cabeza de la lista está vacia, es decir, intento ver si el puntero a la cabeza es NULL, y si lo es, convertir el nodo que le paso a la función en la head de la lsita. Sin embargo, al intentar checkear, solo por intentar referenciarlo me tira el siguiente error.

`typedef struct List {    Node* head;
	} List;`

    void InsertarFinal(List* list, Persona* persona)
	{
		printf("WEENa\n");
		Node* node = create_node(persona);
		printf("m3n\n");
		if ((list->head) == NULL){

			//list->head = node;
			printf("%s\n", "estamos aca");
		}
	}

==2875== Use of uninitialised value of size 8
==2875==    at 0x108B04: InsertarFinal.2985 (in /home/maxpower/Desktop/EDD/T0-2020-1-mistico0121/src/simulate/structest)
==2875==    by 0x108A1D: main (in /home/maxpower/Desktop/EDD/T0-2020-1-mistico0121/src/simulate/structest)
==2875== 
==2875== Invalid read of size 8
==2875==    at 0x108B04: InsertarFinal.2985 (in /home/maxpower/Desktop/EDD/T0-2020-1-mistico0121/src/simulate/structest)
==2875==    by 0x108A1D: main (in /home/maxpower/Desktop/EDD/T0-2020-1-mistico0121/src/simulate/structest)
==2875==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==2875== 
==2875== 
==2875== Process terminating with default action of signal 11 (SIGSEGV)
==2875==  Access not within mapped region at address 0x0
==2875==    at 0x108B04: InsertarFinal.2985 (in /home/maxpower/Desktop/EDD/T0-2020-1-mistico0121/src/simulate/structest)
==2875==    by 0x108A1D: main (in /home/maxpower/Desktop/EDD/T0-2020-1-mistico0121/src/simulate/structest)
==2875==  If you believe this happened as a result of a stack
==2875==  overflow in your program's main thread (unlikely but
==2875==  possible), you can try to increase the size of the
==2875==  main thread stack using the --main-stacksize= flag.
==2875==  The main thread stack size used in this run was 8388608.

Que error estoy cometiendo?

**Comment by mistico0121** [comment]
Lo arreglé. Me faltó hacerle malloc(sizeof(List)) al momento de instanciarla. Disculpa las molestias.

**Comment by Arcoirisky** [comment]
Oh oh reabre la issue!!  Plzzz por si alguien más tiene el mismo problema O:!!
