### ISSUE TITLE
Plazo T0

### ISSUE THREAD

**Issue by mihenriquez** [IIC2133-PUC/2020-1#89]
Estimados/as,

Estoy creando esta issue con la pequeña esperanza de que puedan considerar entregar más tiempo para la tarea 0 de EDD. Pese a que ya se dió una semana más, esto fue debido a que por la prueba ya existía una alta carga esa semana. 

Desde esa fecha hasta ahora he invertido muchísimo tiempo en la tarea, pero al ser un lenguaje nuevo bien mañoso y debido a que a diferencia de cursos pasados de programación, no solo este no se puede caer, sino que tiene que dar un output perfecto, sin leaks de memoria y en un tiempo determinado, lo que implica que nuestra nota será bastante binaria, y en muchos casos no reflejará ni un poco de nuestro esfuerzo. Yo personalmente tengo dos pruebas el miércoles y una el martes, y bueno, sin alargarme más, simplemente no  me la puedo. Muchos compañeros/as han expresado casos similares al mío, y por lo tanto de parte de todos ellos y ellas, quería solicitarles por más tiempo ( aunque sea hasta el viernes).

Saludos

**Comment by fabarros** [comment]
Se agradecería mucho. 10 horas de Debugeo por aquí, el proyecto de Arqui sufrirá las conscuencias.

**Comment by VicenteMerino** [comment]
Yo pienso que estaría bien que dieran más plazo. Encuentro que la tarea está brutal y a mi me tomó mucho tiempo realizarla (la partí el 2 de abril y la terminé ayer en la noche) y sin ser exagerado encuentro que me demoré unas 40-50 horas en hacerla. Considerando que esto es un curso de 10 créditos (10 horas semanales) y que nos dieron cerca de 3 semanas para hacerla gasté entre 13-17 horas semanales en realizarla, mucho más de lo que se espera que usemos en un solo curso. Esto sin considerar que tuvimos una prueba entremedio, siento que la carga académica ha sido altísima. Comento esto no solo para que ojalá les puedan dar más tiempo a mis demás compañeros que aun no la terminan, sino para que lo tengan en cuenta a la hora de preparar las otras tareas y que no tengamos que explotar con la carga nuevamente :(.

Saludos.

**Comment by Arcoirisky** [comment]
Apoyo que para quienes recién inician en C la tarea, comparado a semestres anteriores, se nota que tiene más amor con el pensamiento de que estamos encerrados en la casa y todo ese asunto pero, no por eso estamos en nada ni tenemos más tiempo ;—;

Muchos cursos se han empeñado en seguir con normalidad o incluso darnos más carga inconscientemente por la misma razón “estamos en casa” y acumular todo eso con otros proyectos, tareas, evaluaciones, etc. Nos está haciendo sufrir más que en un semestre normal. 

No son pocos los que ya no dormimos ni 4 horas... Y estamos iniciando el semestre.

Entiendo que es importante seguir con la materia y las evaluaciones para no perder tiempo, pero mientras más dudas se resuelvan ahora menos trabajo será entender los problemas en el futuro. 

Quizás es el pánico hablando por nosotros pero un poco de luz para estas pobres almas en desgracia serán bien utilizadas. 

Piénsenlo y vean la planificación o: tampoco queremos destruir a los nosotros del futuro xD

**Comment by rodobkn** [comment]
En mi caso personal, se me cortó hoy día la luz de la casa, y aunque tengo la tarea relativamente avanzada, hoy día le quería dedicar el tiempo suficiente para terminarla, sin embargo no le he podido dedicar nada de tiempo, dado el inconveniente anteriormente mencionado.

Pero si hacemos una reflexión más profunda, que pasaría si otros alumnos también se le corta la luz, y empezaron la tarea más tarde puesto que tenían entregas de otros ramos antes. En realidad sería una situación super estresante, y yo creo que hay que tomar en consideración esos posibles eventos, puesto que con la cuarentena cada vez habrán mas imprevistos de lo normal, y solucionarlos también es más difícil.

Estoy escribiendo esto del celular, con la poca batería que me queda y con el 4g por si se lo preguntan, para que no crean que es fake.

Saludos!

**Comment by isiguelfand** [comment]
Yo estoy muy de acuerdo con mis compañeros. Además creo importante considerar que para mucho de nosotros, hacer está tarea incluía varias horas de aprender un lenguaje de programación casi desde 0 (aun considerando que asistimos al taller), solos y de forma remota, lo que por lo menos a mí se hace mucho más difícil.

**Comment by kelseyfranken** [comment]
Yo también estoy de acuerdo con mis compañeros. Le he dedicado muchísimo tiempo a la tarea y aún me queda mucho, además muchos ramos han puesto demasiadas evaluaciones por lo que esta costando seguir el ritmo de la modalidad online. Yo creo que afecta mucho el tener que aprender c de forma remota, sin poder preguntarles directamente a los ayudantes o  a los profesores nuestras dudas.

**Comment by yerkko** [comment]
Estamos discutiendo sus propuestas y posibles soluciones con el resto del equipo. Les haremos saber a qué deliberación se llega.

🤔

**Comment by nabenitez** [comment]
Me sumo a los comentarios de arriba. En mi caso recién pude partir post prueba, tenía otras más durante la semana y más entregas de otros ramos. Creo que se debería considerar que el semestre no es como cualquier otro y la verdad cuesta mucho más ser eficiente. Al igual que @Arcoirisky últimamente he estado sacrificando bastantes horas de sueño para poder cumplir. Por lo demás, no es trivial el aprender C, incluso con el material de apoyo :(.

**Comment by tpcantergiani** [comment]
Yo personalmente he dedicado bastantes horas esta semana a la tarea.
Y me frustra pensar que a pesar de esto, tendré un uno, por que la tarea no corre perfectamente. Y debo sacrificar otros ramos para salvar esta tarea.

**Comment by raespinoza4** [comment]
Yo también estoy de acuerdo con mis compañer@s ya que para muchos fue necesario aprender c desde 0, hemos tenido (y tendremos) muchas evaluaciones y entregas pero pese a ello le hemos dedicado mucho tiempo a la tarea (a veces sacrificando otras entregas) y como mencionan en el comentario de arriba, lo que más me frustra es la posiblidad de tener un 1 si no logro hacer que mi tarea funcione perfectamente.

**Comment by vichoeq** [comment]
Hola a todos. se extiende el plazo de la Tarea. Ahora mismo estoy escribiendo el anuncio en el SIDING. (Es largo así que tenganme paciencia)

**Comment by vichoeq** [comment]
Listo. Revisen su correo 💜

**Comment by Arcoirisky** [comment]
@vichoeq gracias por tanto y perdón por tan poco

**Comment by PaoloFabia** [comment]
Hola!

Muchas gracias por aplazar la tarea, creo que algo admirable del DCC es que siempre escuchan a los estudiantes y se intentan llegar a acuerdos.

Mi mensaje es principalemente de agradecimiento por su dedicación en responder issues y estar atentos al desarrollo del curso en su totalidad. Tremendas respuestas y muy bien elaboradas, son un gran equipo docente!

Muchos saludos.
