### ISSUE TITLE
como correr Tarea 0

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2133-PUC/2020-1#9]
Hola clone el repositorio para la tarea, luego hice make y corri la tarea de la siguiente manera `./simulate test/0_gate_enqueue.txt` el output del programa fue `Segmentation fault (core dumped)`, creo que esto es un error, no se si debemos solucionarlo nosotros o hay un error en como estoy corriendo la tarea.

Saludos

**Comment by caespinoza5** [comment]
¡Hola!

Para correr la tarea, tienes que colocar la ruta completa del archivo, que en este caso sería `tests/unit/0_gate_enqueue.txt`

Luego, se ejecutaría de la siguiente manera:

`./simulate tests/unit/0_gate_enqueue.txt`

**Comment by JohnTrombon** [comment]
¡Hola! 
Como tip general te recomiendo correr tu programa con valgrind cada vez que obtengas un segmentation fault, asi valgrind te entrega con más detalle el origen de tu error.
En este caso, valgrind te habría dicho (entre otras cosas) que hay un error en la llamada a la función que lee del archivo en la linea 19 de main.c, lo que te puede dar un indicio que el error estaba en la ruta al archivo.
¡Saludos!

**Comment by ljrodriguez1** [comment]
muchas gracias a ambos, la verdad es que se me paso por completo eso y incluso corri valgrind pero al no estar tan familiarizados con c no entendi el error, pero con su solucion me funciona perfecto.

Saludos

**Comment by Kitaps** [comment]
Volvi a abrir la issue porque podría haber quienes tengan el mismo problema ;)
