### ISSUE TITLE
Entregable

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2133-PUC/2020-1#90]
Hola, que es lo que se debe subir a GitHub? Basta con subir los codigos del src?

**Comment by Arcoirisky** [comment]
Ya había hecho una issue sobre lo mismo, mientras tengas lo necesario para que al hacer make funcione todo bien

**Comment by yerkko** [comment]
Si al hacer make esté el compilado y luego con ./simulate corre, todo bien
