### ISSUE TITLE
Tests intermedios

### ISSUE THREAD

**Issue by pbyoma** [IIC2133-PUC/2020-1#91]
Hola, quería saber si existe la posibilidad de que suban tests que sean un punto intermedio entre los chicos y los largos, ya que es muy difícil encontrar los errores en tantas lineas.

**Comment by jeschuwirth** [comment]
Hola @pbyoma,

lo comentaré con los otros ayudantes, por ahora te recomiendo crear a mano los test con los casos que quieres probar.

**Comment by caespinoza5** [comment]
Mientras tanto, te recomiendo lo siguiente:

- Prueba tu programa con los tests pequeños. Si están funcionando bien con esos tests, significa que vas bien encaminado.

- Revisa el test propuesto en [esta issue](https://github.com/IIC2133-PUC/2020-1/issues/76); con eso puedes asegurarte de que la clausura de un terminal está funcionando bien.

- Revisa lo discutido en [esta issue](https://github.com/IIC2133-PUC/2020-1/issues/71): Ahí se dan recomendaciones para que puedas revisar el funcionamiento de tu programa con los tests grandes.

- Revisa detalladamente el ejemplo dado paso a paso en [esta issue](https://github.com/IIC2133-PUC/2020-1/issues/7).

- En [esta issue](https://github.com/IIC2133-PUC/2020-1/issues/63) se aclaran un par de dudas frecuentes de enunciado.

Me avisas cómo te va.

**Comment by caespinoza5** [comment]
Hola @pbyoma,

Como se mencionó en el último anuncio, parte del desafío es que como alumnos analicen sus algoritmos para verificar que sean correctos y además creen sus propios tests para guiarse. Es por esto que no se subirán más tests por el momento.

Dicho lo anterior, si generas algún test particular y quieres asegurar que tu output es correcto, podrías subir el test en esta issue (si es muy grande, lo subes en formato .zip), y sin problemas entrego el output esperado de ese test lo antes posible.

Quedaré atento.
