### ISSUE TITLE
Error test grande

### ISSUE THREAD

**Issue by dacampos1** [IIC2133-PUC/2020-1#93]
Hola, cuando intento con los test grandes tengo el siguiente error. Vi las líneas que salen pero no se que podría estar mal considerando que con los otros test funcionaba.
![Captura de Pantalla 2020-04-12 a la(s) 23 30 47](https://user-images.githubusercontent.com/42916420/79090086-86a60080-7d16-11ea-9585-160b1d549def.png)

**Comment by caespinoza5** [comment]
¡Hola!

¿Estás seguro que el nombre del archivo es test00.text y no test00.txt?

**Comment by dacampos1** [comment]
Holaa, sii cuando lo hice ahi me equivoque ahora pude ver donde ocurria el error. Gracias
