### ISSUE TITLE
CLASE LUNES 6/04

### ISSUE THREAD

**Issue by chocopiano** [IIC2133-PUC/2020-1#94]
Hola, es posible que suban el video de la clase del lunes pasado? Gracias!

**Comment by chocopiano** [comment]
Porfa

**Comment by yerkko** [comment]
Estamos en proceso, disculpa la demora :)

**Comment by caespinoza5** [comment]
¡Hola!

Ya fueron subidas. Las puedes encontrar en el README de la carpeta Clases del repositorio [(Aquí)](https://github.com/IIC2133-PUC/2020-1/tree/master/Clases).

Gracias por su paciencia.

**Comment by chocopiano** [comment]
Gracias!
