### ISSUE TITLE
Segmentation fault al asignar NULL a una variable

### ISSUE THREAD

**Issue by prochotito-rises** [IIC2133-PUC/2020-1#97]
Hola, tengo problemas al hacer lo sgte.:
`anterior -> sgte = NULL`
Donde anterior es un puntero a un Nodo.
Saludos.

**Comment by yerkko** [comment]
Podrías dar más detalles de qué entrega valgrind please?

**Comment by prochotito-rises** [comment]
=10143== Invalid read of size 8
==10143==    at 0x1095BE: cola_del (cola.c:337)
==10143==    by 0x10983E: main (main.c:29)
==10143==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==10143== 
==10143== 
==10143== Process terminating with default action of signal 11 (SIGSEGV)
==10143==  Access not within mapped region at address 0x8
==10143==    at 0x1095BE: cola_del (cola.c:337)
==10143==    by 0x10983E: main (main.c:29)
==10143==  If you believe this happened as a result of a stack
==10143==  overflow in your program's main thread (unlikely but
==10143==  possible), you can try to increase the size of the
==10143==  main thread stack using the --main-stacksize= flag.
==10143==  The main thread stack size used in this run was 8388608.
==10143== 
==10143== HEAP SUMMARY:
==10143==     in use at exit: 96 bytes in 4 blocks
==10143==   total heap usage: 6 allocs, 2 frees, 1,136 bytes allocated
==10143== 
==10143== 16 bytes in 1 blocks are still reachable in loss record 1 of 4
==10143==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10143==    by 0x108846: cola_append (cola.c:22)
==10143==    by 0x1097AA: main (main.c:18)
==10143== 
==10143== 16 bytes in 1 blocks are still reachable in loss record 2 of 4
==10143==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10143==    by 0x108846: cola_append (cola.c:22)
==10143==    by 0x1097BD: main (main.c:19)
==10143== 
==10143== 16 bytes in 1 blocks are still reachable in loss record 3 of 4
==10143==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10143==    by 0x108846: cola_append (cola.c:22)
==10143==    by 0x1097E3: main (main.c:21)
==10143== 
==10143== 48 bytes in 1 blocks are still reachable in loss record 4 of 4
==10143==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10143==    by 0x1087DB: cola_init (cola.c:9)
==10143==    by 0x10975B: main (main.c:10)
==10143== 
==10143== LEAK SUMMARY:
==10143==    definitely lost: 0 bytes in 0 blocks
==10143==    indirectly lost: 0 bytes in 0 blocks
==10143==      possibly lost: 0 bytes in 0 blocks
==10143==    still reachable: 96 bytes in 4 blocks
==10143==         suppressed: 0 bytes in 0 blocks
==10143== 
==10143== For counts of detected and suppressed errors, rerun with: -v
==10143== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault

**Comment by prochotito-rises** [comment]
ya lo arreglé disculpa, era un error tonto
