### ISSUE TITLE
Variación de medición "time"

### ISSUE THREAD

**Issue by matumartinez** [IIC2133-PUC/2020-1#98]
Hola,

Cuando uso "time" antes de la instrucción para ejecutar un test (con los grandes), a veces me entrega 12 segundos, a veces 17 y ayer me entregaba 9 y a veces 15 (probando el comando consecutivamente en el mismo test). ¿Cómo hago para estar seguro de estar cumpliendo que ejecute en menos de 10 segundos? No sé si a alguien más le habrá pasado o es un problema de mi computador (o quizás porque tengo un poco de memory leak).

Saludos

**Comment by caespinoza5** [comment]
¡Hola! Tal como se menciona en [esta issue](https://github.com/IIC2133-PUC/2020-1/issues/62), los tests que se ocuparán para evaluar (similares a los tests grandes entregados) están pensados con márgenes de tiempo bastante grandes. Si te está dando tiempos cercanos o mayores a 10 segundos en promedio, te recomiendo que revises si existe algún proceso que puedes optimizar.

Las máquinas en donde se ejecutarán los códigos son bastante potentes, por lo que es probable que tu código se ejecute en un tiempo igual o menor que en tu computador; sin embargo, si quieres irte a la segura, te recomiendo optimizar tu programa hasta llegar a un tiempo promedio menor a 10 segundos (e idealmente tiempo máximo menor a 10 segundos).

**Comment by yerkko** [comment]
Como complemento al comentario de Cristóbal y como paréntesis estadístico, los experimentos serios se repiten varias veces. Si aumentas tu 'n' o número de experimentos, reducirás enormemente la varianza. Te recomiendo hacer un comando en bash o python que corra el script varias veces y reporte el tiempo en un txt, con eso puedes hacer un análisis más claro de tu algoritmo.
Hay gran variabilidad en el desempeño por varios motivos. Si usas windows quizás haya una actualización en proceso, quizás chrome esté usando muchos recursos, etc. Generar un ambiente de testing no es trivial, sin embargo, puedes tomar diferentes medidas con el fin de tener resultados más replicables y eliminar varianza experimental.

**Comment by matumartinez** [comment]
Estoy usando una máquina virtual Ubuntu soportada por 2GB de RAM (mi computador es un Mac de 4GB de RAM), no sé si tiene algo que ver.

**Comment by robertov1** [comment]
Hola @matumartinez  

A mi me pasaba lo mismo. Pero era porque estaba ejecutando el comando:

 time ./simulate tests/large/test01.txt

Pero con este comando, que es con el que lo corrigen:

time ./simulate tests/large/test01.txt > out.txt

Bajó considerablemente el tiempo.
Ojalá te sirva

**Comment by matumartinez** [comment]
@robertov1 gracias por el aporte! Acabo de probarlo como tu dices y me bajó a tiempos cercanos a los 9 segundos.
