### ISSUE TITLE
Error indice laser

### ISSUE THREAD

**Issue by dacampos1** [IIC2133-PUC/2020-1#99]
Hola,tengo problemas con el indice del pasajero que elimina el láser.  Según veo el indice es mucho mayor que la cantidad de pasajeros de la lista. Revise mi función de ingreso de pasajeros pero no he podido encontrar el error. No sé si alguien más tiene un problema similar.

**Comment by cho19** [comment]
Hola! 

Yo tuve un problema idéntico y era la clausura, había una condición que hacía que no se trasladaran los pasajeros de un terminal a otro (y por eso me faltaban)

Ojalá te sirva!

**Comment by dacampos1** [comment]
Hola, gracias por responder. Lo que pasa esque tengo problemas en el test00 large en la línea 17639 que es mucho antes de la primera clausura :(

**Comment by caespinoza5** [comment]
Si es anterior a la primera clausura, probablemente sea un error con los cierres de las puertas. Te recomiendo que revises de qué terminal y qué indice es la puerta que tiene problemas (Por ejemplo, terminal 0, índice 2), y luego, revises si han cerrado otras puertas de ese mismo terminal antes. Quizás puede haber un problema en el reingreso de una puerta cerrada al terminal.

**Comment by dacampos1** [comment]
Estaba revisando y tampoco hay ningún cierre en el terminal 1 hasta esa línea, solo hay abordajes y laser en la puerta y he corrido varias pruebas y no encuentro que tenga fallas ahí.

**Comment by caespinoza5** [comment]
Revisa entonces la política de ingreso que estás ocupando. ¿Estás asegurándote que estás colocando al pasajero en la fila que tiene menos pasajeros de su tipo? ¿Estás actualizando la fila correctamente?

Lo otro que te recomiendo hacer es plantear tus propios tests de prueba pequeños: puedes hacer un terminal con 3 puertas donde ingresen en orden aleatorio 30 personas en total (10 robots, 10 niños y 10 adultos), y revises manualmente que las filas tienen las cantiades correctas (comparándolo con una ejecución que hayas hecho a mano del algoritmo).

En particular, puedo asegurar que la ejecución del programa con todos los inputs de tests grandes y pequeños es correcta (es decir, no hay acciones inválidas).

**Comment by dacampos1** [comment]
Hola hice este test podrías darme el output correcto??
1
3
INGRESO 0 1 0
INGRESO 0 2 1
INGRESO 0 3 2
INGRESO 0 4 2
INGRESO 0 5 0
INGRESO 0 6 1
INGRESO 0 7 1
INGRESO 0 8 2
INGRESO 0 9 2
INGRESO 0 10 0
INGRESO 0 11 0
INGRESO 0 12 1
INGRESO 0 13 0
INGRESO 0 14 2
INGRESO 0 15 2
INGRESO 0 16 1
INGRESO 0 17 0
INGRESO 0 18 1
INGRESO 0 19 1
INGRESO 0 20 2
INGRESO 0 21 0
INGRESO 0 22 0
INGRESO 0 23 1
INGRESO 0 24 2
INGRESO 0 25 2
INGRESO 0 26 0
INGRESO 0 27 0
INGRESO 0 28 1
INGRESO 0 29 2
INGRESO 0 30 1
END

**Comment by caespinoza5** [comment]
```
TITANIC LOG
TERMINAL 0
GATE 0: 10
1
11
21
27
7
18
19
4
14
25
GATE 1: 11
5
13
22
2
12
28
30
8
20
24
29
GATE 2: 9
10
17
26
6
16
23
3
9
15
END LOG
```

**Comment by dacampos1** [comment]
Tengo el mismo output por lo que supongo que mi ingreso esta bien, agregue a ese mismo ejemplo varios eventos laser y abordaje para probar si eran esos y también funcionan bien.
Sólo tengo problemas cuando intento correr los test grandes, valgrind solo me indica que el error es en laser pq claramente no pudo encontrar el indice.

![Captura de Pantalla 2020-04-16 a la(s) 16 56 37](https://user-images.githubusercontent.com/42916420/79506090-68385180-8003-11ea-96b4-4e09f2eb6ffb.png)

**Comment by caespinoza5** [comment]
Mmm, no estoy muy seguro a qué se debe exactamente tu error, más allá de que es en esa función. Más que nada recomiendo revisar casos bordes (revisar eliminación de primer elemento, último elemento, de algún elemento borde entre niños/adultos y adultos/robots (eliminación último niño o primer adulto o último adulto o primer robot), etc). 
Puedes también hacer una función que cada vez que se elimine una persona, revises manualmente (iterando desde el primer elemento de la cola hasta el último) que el nuevo largo de la cola es igual al largo anterior - 1, y en caso contrario, hagas printf("ERROR\n") para que después lo puedas buscar en el archivo de output.

Al momento en que se ejecuta ese laser, dicha fila tiene 450 personas, por lo que el índice es válido.

**Comment by kelseyfranken** [comment]
Me pasa el mismo error, tampoco se por que es :((

**Comment by caespinoza5** [comment]
Considerando que no hay cierres ni clausuras, si cortan el archivo con END después de la línea 17639 y buscan cuántos ingresos hay en el terminal 1 (ctrl+F "INGRESO 1"), verán que hay **2943 ingresos** en el terminal 1.

Si buscan cuántos abordajes hay en el terminal 1 (ctrl+F "ABORDAJE 1"), verán que son **29 abordajes** en las puertas del terminal 1.

Si buscan cuántos laser hay en el terminal 1 (ctrl+F "LASER 1") verán que hay **12 laser** (13 en total, pero antes de la línea 17639 hay 12) en ese terminal.

Esto significa que en total hay 2943 - 29*8 - 12 = 2699 personas en total en ese terminal.

Si al llegar a la línea 17639, hacen un printf de la suma de la cantidad de personas en el terminal 1 (Pueden hacer un printf de este número al momento de hacer un laser para debbugear), ¿Les da esa cantidad?

**Comment by kelseyfranken** [comment]
A mi me pasa que me tira error en el test00 en el LASER 3 3 2276, solo hay ingresos y abordajes que afectan ese terminal antes

**Comment by camaruri** [comment]
Tengo el mismo problema y no he podido ver por que es

**Comment by kelseyfranken** [comment]
@camaruri yo al final lo pude arreglar, era un error de copy paste que no cambié un adult por un kid. Pero lo caché poniendo un END justo antes de la linea de láser que me tiraba error y fui analizando los cambios en la fila, había un cierto punto que me ingresaba mal a las personas y ahí fui cachando por que!

**Comment by camaruri** [comment]
Estaba revisando las entradas que le llegan a laser y parecen estar bien.
Pero tengo errores aunque no pase nada mas que ingresos antes del laser.
Por lo que pude darme cuenta dentro de mi lista ligada que recorre el laser tengo elementos que la memoria fue liberada o no tiene nada. Pero eso solo con los ingresos no me deberia pasar.
No se si hay una forma de asegurarse que cada nodo reciba la memoria que le pedi.
Porque me pasa con inputs grandes nomas.
Gracias

**Comment by camaruri** [comment]
probe con mostrar cuando malloc del nodo retorna NULL y no me pasa nunca eso.
Ademas no se porque me pasa siempre en el mismo nodo
